// apps/dashboard/app/components/ModelSearchPopover.vue
<script setup lang="ts">
import { getProviderLabel } from "../../lib/provider-accounts";
import type { ModelListItem as DashboardModelListItem, ModelSearchItem } from "../../lib/dashboard-api-types";
import type { ModelStats } from "../../lib/model-stats";

type ModelListItem = ModelSearchItem;

const dashboardApi = useDashboardApi();
const route = useRoute();

const desktopOpen = ref(false);
const mobileOpen = ref(false);
const search = ref("");
const detailModel = ref<ModelListItem | null>(null);
const copiedModelId = ref<string | null>(null);
const pendingModelId = ref<string | null>(null);

const detailOpen = computed({
  get: () => detailModel.value !== null,
  set: (value: boolean) => {
    if (!value) detailModel.value = null;
  },
});

const { data, refresh } = await useAsyncData("layout-model-search", () => dashboardApi.models.search(), {
  default: () => [] as ModelListItem[],
});
const sharedFullModels = useNuxtData<DashboardModelListItem[]>("dashboard-models");
const { data: fullModelData, execute: loadFullModels, status: fullModelStatus } = useAsyncData("dashboard-models", () => dashboardApi.models.list(), {
  immediate: false,
});

const models = computed<ModelListItem[]>(() => data.value ?? []);
const fullModels = computed(() => fullModelData.value ?? sharedFullModels.data.value ?? []);
const fullModelById = computed(() => new Map(fullModels.value.map((model) => [model.id, model])));
const detailModelStats = computed<ModelStats | undefined>(() => detailModel.value ? fullModelById.value.get(detailModel.value.id)?.stats : undefined);
const isLoadingDetailStats = computed(() => detailModel.value !== null && !detailModelStats.value && fullModelStatus.value === "pending");
const filteredModels = computed(() => {
  const term = search.value.trim().toLowerCase();

  if (!term) return models.value;

  return models.value.filter((model) => {
    const providers = model.providers.map(getProviderLabel).join(" ");
    return `${model.id} ${providers}`.toLowerCase().includes(term);
  });
});

watch(() => route.fullPath, () => {
  desktopOpen.value = false;
  mobileOpen.value = false;
  search.value = "";
});

function selectModel(model: ModelListItem) {
  detailModel.value = model;
  desktopOpen.value = false;
  mobileOpen.value = false;
  if (!fullModelById.value.get(model.id)?.stats) void loadFullModels();
}

async function copyModelId(modelId: string) {
  await navigator.clipboard.writeText(modelId);
  copiedModelId.value = modelId;
  window.setTimeout(() => {
    if (copiedModelId.value === modelId) copiedModelId.value = null;
  }, 2000);
}

async function setModelEnabled(model: ModelListItem, enabled: boolean) {
  pendingModelId.value = model.id;
  const previousValue = model.isEnabled;
  model.isEnabled = enabled;

  try {
    const result = await dashboardApi.models.setEnabled({ modelId: model.id, enabled });
    if (!result.success) throw new Error(result.error);
    await refresh();
    const updatedModel = models.value.find((item) => item.id === model.id);
    if (updatedModel) detailModel.value = updatedModel;
  } catch (error) {
    model.isEnabled = previousValue;
    console.error(error);
  } finally {
    pendingModelId.value = null;
  }
}
</script>

<template>
  <div class="max-w-xl">
    <UiPopover v-model:open="desktopOpen" :content="{ align: 'start', sideOffset: 4 }" class="hidden md:block">
      <button
        type="button"
        role="combobox"
        :aria-expanded="desktopOpen"
        class="hidden h-9 w-full cursor-pointer items-center justify-between gap-2 whitespace-nowrap rounded-lg border border-border bg-background px-2.5 text-xs font-normal shadow-xs outline-none transition-all hover:bg-input/50 hover:text-accent-foreground focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 sm:px-3 sm:text-sm md:inline-flex"
      >
        <span class="flex min-w-0 items-center gap-2">
          <UiIcon name="i-lucide-search" class="size-4 text-muted-foreground" />
          <span class="truncate text-muted-foreground">Search models...</span>
        </span>
        <UiIcon name="i-lucide-chevron-down" class="size-4 shrink-0 text-muted-foreground" />
      </button>

      <template #content>
        <div class="w-[min(92vw,30rem)] p-0">
          <div class="flex h-11 items-center gap-2 border-b border-border px-3">
            <UiIcon name="i-lucide-search" class="size-4 shrink-0 text-muted-foreground" />
            <input
              v-model="search"
              class="h-10 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50"
              placeholder="Search model ID or provider..."
              autocomplete="off"
            >
          </div>
          <div class="max-h-[320px] overflow-y-auto p-1">
            <p v-if="filteredModels.length === 0" class="py-6 text-center text-sm text-muted-foreground">No model found.</p>
            <div v-else class="space-y-1">
              <p class="px-2 py-1.5 text-xs font-medium text-muted-foreground">Models</p>
              <button
                v-for="model in filteredModels"
                :key="model.id"
                type="button"
                class="flex w-full cursor-pointer items-start gap-2 rounded-sm px-2 py-1.5 text-left text-sm outline-none transition-colors hover:bg-accent hover:text-accent-foreground"
                @click="selectModel(model)"
              >
                <div class="min-w-0 flex-1">
                  <p class="truncate font-mono text-xs sm:text-sm">{{ model.id }}</p>
                  <div class="mt-1 flex flex-wrap gap-1">
                    <UiBadge v-for="provider in model.providers" :key="`${model.id}-${provider}`" variant="outline" class="text-[10px]">
                      {{ getProviderLabel(provider) }}
                    </UiBadge>
                  </div>
                </div>
              </button>
            </div>
          </div>
        </div>
      </template>
    </UiPopover>

    <button
      type="button"
      role="combobox"
      :aria-expanded="mobileOpen"
      class="inline-flex h-9 w-full cursor-pointer items-center justify-between gap-2 whitespace-nowrap rounded-lg border border-border bg-background px-2.5 text-xs font-normal shadow-xs outline-none transition-all hover:bg-input/50 hover:text-accent-foreground focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 sm:px-3 sm:text-sm md:hidden"
      @click="mobileOpen = true"
    >
      <span class="flex min-w-0 items-center gap-2">
        <UiIcon name="i-lucide-search" class="size-4 text-muted-foreground" />
        <span class="truncate text-muted-foreground">Search models...</span>
      </span>
      <UiIcon name="i-lucide-chevron-down" class="size-4 shrink-0 text-muted-foreground" />
    </button>

    <UiDialog v-model:open="mobileOpen" :ui="{ content: 'p-0 sm:max-w-md' }">
      <template #content>
        <div class="border-b border-border px-4 py-3">
          <p class="text-sm font-semibold">Search Models</p>
          <p class="mt-1 text-xs text-muted-foreground">Find a model and tap to view details</p>
        </div>
        <div class="flex h-11 items-center gap-2 border-b border-border px-3">
          <UiIcon name="i-lucide-search" class="size-4 shrink-0 text-muted-foreground" />
          <input v-model="search" class="h-10 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground" placeholder="Search model ID or provider...">
        </div>
        <div class="max-h-[60vh] overflow-y-auto p-1">
          <p v-if="filteredModels.length === 0" class="py-6 text-center text-sm text-muted-foreground">No model found.</p>
          <button
            v-for="model in filteredModels"
            :key="`mobile-${model.id}`"
            type="button"
            class="flex w-full cursor-pointer items-start gap-2 rounded-sm px-2 py-1.5 text-left text-sm outline-none transition-colors hover:bg-accent hover:text-accent-foreground"
            @click="selectModel(model)"
          >
            <div class="min-w-0 flex-1">
              <p class="truncate font-mono text-xs sm:text-sm">{{ model.id }}</p>
              <div class="mt-1 flex flex-wrap gap-1">
                <UiBadge v-for="provider in model.providers" :key="`mobile-${model.id}-${provider}`" variant="outline" class="text-[10px]">
                  {{ getProviderLabel(provider) }}
                </UiBadge>
              </div>
            </div>
          </button>
        </div>
      </template>
    </UiDialog>

    <UiDialog v-model:open="detailOpen" :ui="{ content: 'gap-0 sm:max-w-md' }">
      <template #content>
        <div v-if="detailModel" class="space-y-3" :class="detailModel.isEnabled === false ? 'opacity-70' : ''">
          <div class="flex items-start justify-between gap-2">
            <button
              type="button"
              :title="`Copy model ID ${detailModel.id}`"
              :aria-label="`Copy model ID ${detailModel.id}`"
              class="-m-1 flex min-w-0 flex-1 items-center gap-1.5 rounded-md p-1 text-left transition-colors hover:bg-accent/50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
              @click="copyModelId(detailModel.id)"
            >
              <span class="flex size-3 shrink-0 items-center justify-center">
                <UiIcon :name="copiedModelId === detailModel.id ? 'i-lucide-check' : 'i-lucide-copy'" class="size-3" />
              </span>
              <span class="min-w-0 flex-1 overflow-hidden break-all font-mono text-sm font-semibold leading-5 [display:-webkit-box] [-webkit-box-orient:vertical] [-webkit-line-clamp:2]" :title="detailModel.id">
                {{ detailModel.id }}
              </span>
            </button>
            <div class="flex shrink-0 items-center gap-1.5">
              <span class="text-[11px] text-muted-foreground">{{ detailModel.isEnabled ? 'On' : 'Off' }}</span>
              <UiSwitch
                :model-value="detailModel.isEnabled"
                :disabled="pendingModelId === detailModel.id"
                :title="detailModel.isEnabled ? 'Disable model' : 'Enable model'"
                @update:model-value="setModelEnabled(detailModel, $event)"
              />
            </div>
          </div>

          <div class="flex flex-wrap items-center gap-1">
            <UiBadge v-for="provider in detailModel.providers" :key="provider" variant="secondary" class="text-xs">
              {{ getProviderLabel(provider) }}
            </UiBadge>
            <NuxtLink
              v-if="detailModel.isEnabled"
              :to="`/dashboard/playground?model=${encodeURIComponent(detailModel.id)}`"
              class="inline-flex h-5 items-center justify-center gap-1 rounded-md px-1.5 text-[11px] hover:bg-accent/50"
            >
              <UiIcon name="i-lucide-flask-conical" class="size-3" />
            </NuxtLink>
          </div>

          <ModelFeatureBadges :meta="detailModel.meta" />
          <UiSkeleton v-if="isLoadingDetailStats" class="h-24 rounded-lg" />
          <ModelStatsPanel v-else-if="detailModelStats" :stats="detailModelStats" :label="detailModel.id" compact />
        </div>
      </template>
    </UiDialog>
  </div>
</template>

// apps/dashboard/components/layout/model-search-popover.tsx
"use client";

import { useState, useCallback } from "react";
import { useRouter } from "next/navigation";
import { ChevronDown, Copy, Check, Search, FlaskConical, Brain, Wrench, Eye, Calendar, BarChart3, ArrowDown, ArrowUp } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import {
  Command,
  CommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command";
import {
  Dialog,
  DialogContent,
} from "@/components/ui/dialog";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { UsageSparkline } from "@/components/dashboard/shared/usage-sparkline";
import { cn } from "@/lib/utils";
import { usePlaygroundPreset } from "@/lib/playground-preset-context";
import { setModelEnabled } from "@/lib/actions/models";
import type { ModelMeta } from "@opendum/shared/proxy/models";
import type { ModelStats } from "@/lib/model-stats";

interface ModelSearchItem {
  id: string;
  providers: string[];
  meta?: ModelMeta;
  isEnabled: boolean;
  stats: ModelStats;
}

interface ModelSearchPopoverProps {
  models: ModelSearchItem[];
  className?: string;
}

function formatTokens(tokens: number): string {
  if (tokens >= 1000000) {
    return `${(tokens / 1000000).toFixed(1)}M`;
  }
  if (tokens >= 1000) {
    return `${Math.round(tokens / 1000)}K`;
  }
  return tokens.toString();
}

function formatDate(dateStr: string): string {
  const parts = dateStr.split("-");
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  const year = parts[0];
  const month = months[parseInt(parts[1], 10) - 1];
  return `${month} ${year}`;
}

function formatDuration(duration: number | null): string {
  if (duration === null) {
    return "-";
  }

  if (duration >= 1000) {
    return `${(duration / 1000).toFixed(2)}s`;
  }

  return `${duration}ms`;
}

function formatHourLabel(time: string): string {
  const date = new Date(time);
  return date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
}

function ModelDetailContent({
  model,
  onClose,
}: {
  model: ModelSearchItem;
  onClose: () => void;
}) {
  const router = useRouter();
  const { setPreset } = usePlaygroundPreset();
  const [copied, setCopied] = useState(false);
  const [isEnabled, setIsEnabled] = useState(model.isEnabled);
  const [isUpdating, setIsUpdating] = useState(false);
  const meta = model.meta;
  const stats = model.stats;

  const dailyValues = stats.dailyRequests.map((point) => point.count);
  const durationValues = stats.durationLast24Hours.map((point) => point.avgDuration ?? 0);
  const durationLabelPoints = [
    stats.durationLast24Hours[0],
    stats.durationLast24Hours[Math.floor(stats.durationLast24Hours.length / 2)],
    stats.durationLast24Hours[stats.durationLast24Hours.length - 1],
  ].filter((point): point is { time: string; avgDuration: number | null } => Boolean(point));
  const maxDailyRequests = Math.max(...dailyValues, 0);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(model.id);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Failed to copy model ID");
    }
  };

  const handleEnabledChange = useCallback(async (checked: boolean) => {
    setIsEnabled(checked);
    setIsUpdating(true);

    try {
      const result = await setModelEnabled(model.id, checked);
      if (!result.success) {
        throw new Error(result.error);
      }
    } catch (error) {
      setIsEnabled(!checked);
      toast.error(
        error instanceof Error ? error.message : "Failed to update model status"
      );
    } finally {
      setIsUpdating(false);
    }
  }, [model.id]);

  return (
    <div className={`space-y-3 ${!isEnabled ? "opacity-70" : ""}`}>
      <div className="flex items-start justify-between gap-2">
        <button
          type="button"
          onClick={handleCopy}
          title="Copy model ID"
          aria-label={`Copy model ID ${model.id}`}
          className="flex min-w-0 flex-1 items-center gap-1.5 rounded-md p-1 -m-1 text-left transition-colors hover:bg-accent/50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
        >
          <span className="flex size-3 shrink-0 items-center justify-center">
            {copied ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
          </span>
          <span
            className="min-w-0 flex-1 overflow-hidden text-sm font-mono font-semibold leading-5 whitespace-normal break-all [display:-webkit-box] [-webkit-box-orient:vertical] [-webkit-line-clamp:2]"
            title={model.id}
          >
            {model.id}
          </span>
        </button>
        <div className="flex items-center gap-1.5 shrink-0">
          <span className="text-[11px] text-muted-foreground">
            {isEnabled ? "On" : "Off"}
          </span>
          <Switch
            checked={isEnabled}
            onCheckedChange={handleEnabledChange}
            disabled={isUpdating}
            title={isEnabled ? "Disable model" : "Enable model"}
          />
        </div>
      </div>

      {/* Row 2: Provider badges + Play */}
      <div className="flex flex-wrap items-center gap-1">
        {model.providers.map((provider) => (
          <Badge key={provider} variant="secondary" className="text-xs">
            {provider}
          </Badge>
        ))}
        {isEnabled && (
          <Button
            variant="ghost"
            size="xs"
            className="h-5 px-1.5 text-[11px]"
            title="Try in Playground"
            onClick={() => {
              setPreset({ modelId: model.id });
              onClose();
              router.push("/dashboard/playground");
            }}
          >
            <FlaskConical className="h-3 w-3" />
          </Button>
        )}
      </div>

      {/* Model metadata */}
      {meta && (
        <div className="space-y-1.5 text-xs text-muted-foreground">
          <div className="flex items-center gap-1.5 flex-wrap">
            {meta.contextLength && (
              <span className="inline-flex items-center gap-1 tabular-nums" title="Input tokens">
                {formatTokens(meta.contextLength)}
                <ArrowDown className="h-3 w-3 shrink-0" />
              </span>
            )}
            {meta.contextLength && meta.outputLimit && <span>·</span>}
            {meta.outputLimit && (
              <span className="inline-flex items-center gap-1 tabular-nums" title="Output tokens">
                {formatTokens(meta.outputLimit)}
                <ArrowUp className="h-3 w-3 shrink-0" />
              </span>
            )}
            {meta.knowledgeCutoff && (
              <>
                <span>·</span>
                <span className="inline-flex items-center gap-1">
                  <Calendar className="h-3 w-3 shrink-0" />
                  {formatDate(meta.knowledgeCutoff)}
                </span>
              </>
            )}
          </div>

          {(meta.reasoning || meta.toolCall || meta.vision) && (
            <div className="flex flex-wrap gap-1">
              {meta.reasoning && (
                <Badge variant="outline" className="text-[11px] py-0 h-5">
                  <Brain className="h-3 w-3 mr-1" />
                  Reasoning
                </Badge>
              )}
              {meta.toolCall && (
                <Badge variant="outline" className="text-[11px] py-0 h-5">
                  <Wrench className="h-3 w-3 mr-1" />
                  Tools
                </Badge>
              )}
              {meta.vision && (
                <Badge variant="outline" className="text-[11px] py-0 h-5">
                  <Eye className="h-3 w-3 mr-1" />
                  Vision
                </Badge>
              )}
            </div>
          )}
        </div>
      )}

      {/* Stats */}
      <div className="rounded-md border border-border/70 bg-muted/20 p-2 sm:p-2.5 space-y-2">
        <div className="flex items-center justify-between text-[11px] text-muted-foreground">
          <span className="inline-flex items-center gap-1">
            <BarChart3 className="h-3 w-3 shrink-0" />
            30d
          </span>
          <span className="tabular-nums">{maxDailyRequests.toLocaleString()} peak</span>
        </div>

        <div className="grid grid-cols-3 gap-1.5">
          <div className="rounded border border-border/60 bg-background/70 px-1.5 py-1 sm:px-2 sm:py-1.5">
            <p className="text-[10px] text-muted-foreground truncate">Requests</p>
            <p className="text-xs sm:text-sm font-semibold text-foreground tabular-nums truncate">{stats.totalRequests.toLocaleString()}</p>
          </div>
          <div className="rounded border border-border/60 bg-background/70 px-1.5 py-1 sm:px-2 sm:py-1.5">
            <p className="text-[10px] text-muted-foreground truncate">Success</p>
            <p className="text-xs sm:text-sm font-semibold text-foreground tabular-nums truncate">
              {stats.successRate === null ? "-" : `${stats.successRate}%`}
            </p>
          </div>
          <div className="rounded border border-border/60 bg-background/70 px-1.5 py-1 sm:px-2 sm:py-1.5">
            <p className="text-[10px] text-muted-foreground truncate">Latency</p>
            <p className="text-xs sm:text-sm font-semibold text-foreground tabular-nums truncate">{formatDuration(stats.avgDurationLastDay)}</p>
          </div>
        </div>

        <div className="rounded border border-border/60 bg-background/70 px-1.5 py-1 sm:px-2 sm:py-1.5">
          <UsageSparkline
            values={durationValues}
            color="var(--chart-2)"
            ariaLabel={`Average duration trend for ${model.id} over last 24 hours`}
            emptyLabel="No duration data"
            className="h-6"
            height={24}
          />
          <div className="mt-0.5 grid grid-cols-3 text-[9px] text-muted-foreground">
            {durationLabelPoints.map((point) => (
              <span key={point.time} className="text-center truncate">
                {formatHourLabel(point.time)}
              </span>
            ))}
          </div>
        </div>

        <UsageSparkline
          values={dailyValues}
          color="var(--chart-1)"
          ariaLabel={`Requests trend for ${model.id}`}
        />
      </div>
    </div>
  );
}

export function ModelSearchPopover({ models, className }: ModelSearchPopoverProps) {
  const [desktopOpen, setDesktopOpen] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [detailModel, setDetailModel] = useState<ModelSearchItem | null>(null);

  const handleSelect = (model: ModelSearchItem, closeSearch: () => void) => {
    closeSearch();
    setDetailModel(model);
  };

  const handleDetailClose = () => {
    setDetailModel(null);
  };

  const renderCommandContent = (close: () => void) => (
    <>
      <CommandInput placeholder="Search model ID or provider..." />
      <CommandList>
        <CommandEmpty>No model found.</CommandEmpty>
        <CommandGroup heading="Models">
          {models.map((model) => (
            <CommandItem
              key={model.id}
              value={`${model.id} ${model.providers.join(" ")}`}
              onSelect={() => {
                handleSelect(model, close);
              }}
              className="items-start gap-2"
            >
              <div className="min-w-0 flex-1">
                <p className="truncate font-mono text-xs sm:text-sm">{model.id}</p>
                <div className="mt-1 flex flex-wrap gap-1">
                  {model.providers.map((provider) => (
                    <Badge key={`${model.id}-${provider}`} variant="outline" className="text-[10px]">
                      {provider}
                    </Badge>
                  ))}
                </div>
              </div>
            </CommandItem>
          ))}
        </CommandGroup>
      </CommandList>
    </>
  );

  const triggerClassName = cn(
    "h-9 w-full justify-between rounded-lg border-border bg-background px-2.5 text-xs font-normal sm:px-3 sm:text-sm",
    className
  );

  return (
    <>
      <div className="hidden md:block">
        <Popover open={desktopOpen} onOpenChange={setDesktopOpen}>
          <PopoverTrigger asChild>
            <Button
              variant="outline"
              role="combobox"
              aria-expanded={desktopOpen}
              className={triggerClassName}
            >
              <span className="flex min-w-0 items-center gap-2">
                <Search className="h-4 w-4 text-muted-foreground" />
                <span className="truncate text-muted-foreground">Search models...</span>
              </span>
              <ChevronDown className="h-4 w-4 shrink-0 text-muted-foreground" />
            </Button>
          </PopoverTrigger>
          <PopoverContent align="start" className="w-[min(92vw,30rem)] p-0">
            <Command>{renderCommandContent(() => setDesktopOpen(false))}</Command>
          </PopoverContent>
        </Popover>
      </div>

      <div className="md:hidden">
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={mobileOpen}
          onClick={() => setMobileOpen(true)}
          className={triggerClassName}
        >
          <span className="flex min-w-0 items-center gap-2">
            <Search className="h-4 w-4 text-muted-foreground" />
            <span className="truncate text-muted-foreground">Search models...</span>
          </span>
          <ChevronDown className="h-4 w-4 shrink-0 text-muted-foreground" />
        </Button>
        <CommandDialog
          open={mobileOpen}
          onOpenChange={setMobileOpen}
          title="Search Models"
          description="Find a model and tap to view details"
          className="p-0"
        >
          {renderCommandContent(() => setMobileOpen(false))}
        </CommandDialog>
      </div>

      <Dialog open={detailModel !== null} onOpenChange={(open) => { if (!open) handleDetailClose(); }}>
        <DialogContent className="sm:max-w-md gap-0">
          {detailModel && (
            <ModelDetailContent model={detailModel} onClose={handleDetailClose} />
          )}
        </DialogContent>
      </Dialog>
    </>
  );
}
