// apps/dashboard/app/pages/dashboard/accounts/[provider].vue
<script setup lang="ts">
import type { AccountQuotaInfo, ProviderDetailData, QuotaGroupDisplay, QuotaProviderKey } from "../../../../lib/dashboard-api-types";
import { BY_KEY, getProviderFromSlug, type ProviderAccountKey } from "../../../../lib/provider-accounts";

definePageMeta({ middleware: "auth", layout: "dashboard" });

const route = useRoute();
const dashboardApi = useDashboardApi();
const selectedProvider = computed(() => getProviderFromSlug(String(route.params.provider)) ?? String(route.params.provider));
const providerMeta = computed(() => selectedProvider.value in BY_KEY ? BY_KEY[selectedProvider.value as ProviderAccountKey] : null);

type Account = ProviderDetailData["accounts"][number];
type QuotaSummaryGroup = Pick<QuotaGroupDisplay, "name" | "displayName"> & {
  remainingRequests: number;
  maxRequests: number;
  usedRequests: number;
  remainingFraction: number;
  percentUsed: number;
  accounts: number;
};

const QUOTA_PROVIDERS = new Set<string>(["antigravity", "copilot", "codex", "gemini_cli", "kiro", "openrouter"]);

const { data, error, pending, refresh } = await useAsyncData(
  () => `dashboard-accounts-detail-${selectedProvider.value}`,
  () => dashboardApi.accounts.byProviderDetailed({ provider: selectedProvider.value }),
  { server: false, watch: [selectedProvider] }
);

const detailData = computed<ProviderDetailData | null>(() => data.value ?? null);
const accounts = computed(() => detailData.value?.accounts ?? []);
const activeAccountCount = computed(() => accounts.value.filter((account) => account.isActive).length);
const isLoadingAccounts = computed(() => pending.value || (!detailData.value && !error.value));
const pinnedProviders = computed(() => new Set(detailData.value?.pinnedProviders ?? []));
const supportedModels = computed(() => detailData.value?.supportedModels ?? []);
const disabledModelsByAccountId = computed(() => detailData.value?.disabledModelsByAccountId ?? {});
const supportsProviderQuota = computed(() => QUOTA_PROVIDERS.has(selectedProvider.value));
const quotaByAccountId = ref<Record<string, AccountQuotaInfo>>({});
const quotaErrorByAccountId = ref<Record<string, string>>({});
const quotaLoadingByAccountId = ref<Record<string, boolean>>({});
let quotaQueueRunId = 0;

const quotaCapableAccounts = computed(() => accounts.value.filter((account) => toQuotaProvider(account.provider)));
const activeQuotaAccounts = computed(() => quotaCapableAccounts.value.filter((account) => account.isActive));
const quotaSummaryGroups = computed<QuotaSummaryGroup[]>(() => {
  const groups = new Map<string, QuotaSummaryGroup>();

  for (const account of activeQuotaAccounts.value) {
    const quota = quotaByAccountId.value[account.id];
    if (quota?.status !== "success") continue;

    for (const group of quota.groups) {
      if (![group.remainingRequests, group.maxRequests, group.usedRequests].every(Number.isFinite) || group.maxRequests <= 0) continue;

      const groupKey = `${group.name}:${group.displayName}`;
      const current = groups.get(groupKey) ?? {
        name: group.name,
        displayName: group.displayName,
        remainingRequests: 0,
        maxRequests: 0,
        usedRequests: 0,
        remainingFraction: 0,
        percentUsed: 0,
        accounts: 0,
      };

      current.remainingRequests += group.remainingRequests;
      current.maxRequests += group.maxRequests;
      current.usedRequests += group.usedRequests;
      current.accounts += 1;
      groups.set(groupKey, current);
    }
  }

  return Array.from(groups.values())
    .map((group) => ({
      ...group,
      remainingFraction: group.maxRequests > 0 ? Math.max(0, Math.min(1, group.remainingRequests / group.maxRequests)) : 0,
      percentUsed: group.maxRequests > 0 ? Math.round(Math.max(0, Math.min(100, (group.usedRequests / group.maxRequests) * 100))) : 0,
    }))
    .sort((a, b) => a.displayName.localeCompare(b.displayName));
});

function toQuotaProvider(provider: string): QuotaProviderKey | null {
  return QUOTA_PROVIDERS.has(provider) ? provider as QuotaProviderKey : null;
}

function setQuotaLoading(accountId: string, loading: boolean) {
  quotaLoadingByAccountId.value = loading
    ? { ...quotaLoadingByAccountId.value, [accountId]: true }
    : Object.fromEntries(Object.entries(quotaLoadingByAccountId.value).filter(([key]) => key !== accountId));
}

function pruneQuotaState() {
  const accountIds = new Set(accounts.value.map((account) => account.id));
  quotaByAccountId.value = Object.fromEntries(Object.entries(quotaByAccountId.value).filter(([accountId]) => accountIds.has(accountId)));
  quotaErrorByAccountId.value = Object.fromEntries(Object.entries(quotaErrorByAccountId.value).filter(([accountId]) => accountIds.has(accountId)));
  quotaLoadingByAccountId.value = Object.fromEntries(Object.entries(quotaLoadingByAccountId.value).filter(([accountId]) => accountIds.has(accountId)));
}

async function loadAccountQuota(account: Account, forceRefresh = false, runId?: number) {
  const provider = toQuotaProvider(account.provider);
  if (!provider || quotaLoadingByAccountId.value[account.id]) return;
  if (!forceRefresh && (quotaByAccountId.value[account.id] || quotaErrorByAccountId.value[account.id])) return;

  setQuotaLoading(account.id, true);
  quotaErrorByAccountId.value = { ...quotaErrorByAccountId.value, [account.id]: "" };

  try {
    const result = await dashboardApi.accounts.quota({ provider, accountId: account.id, forceRefresh });
    if (runId !== undefined && runId !== quotaQueueRunId) return;
    if (!result.success) throw new Error(result.error);

    quotaByAccountId.value = { ...quotaByAccountId.value, [account.id]: result.data };
    quotaErrorByAccountId.value = Object.fromEntries(Object.entries(quotaErrorByAccountId.value).filter(([accountId]) => accountId !== account.id));
  } catch (error) {
    if (runId !== undefined && runId !== quotaQueueRunId) return;
    const message = error instanceof Error ? error.message : "Failed to fetch quota data";
    quotaErrorByAccountId.value = { ...quotaErrorByAccountId.value, [account.id]: message };
  } finally {
    setQuotaLoading(account.id, false);
  }
}

async function runQuotaQueue() {
  const runId = ++quotaQueueRunId;
  const enabledFirstAccounts = [
    ...quotaCapableAccounts.value.filter((account) => account.isActive),
    ...quotaCapableAccounts.value.filter((account) => !account.isActive),
  ];

  for (const account of enabledFirstAccounts) {
    if (runId !== quotaQueueRunId) return;
    if (quotaLoadingByAccountId.value[account.id]) {
      while (quotaLoadingByAccountId.value[account.id] && runId === quotaQueueRunId) {
        await new Promise((resolve) => setTimeout(resolve, 100));
      }
      if (runId !== quotaQueueRunId) return;
    }
    await loadAccountQuota(account, false, runId);
  }
}

function quotaPercentRemaining(group: QuotaSummaryGroup): number {
  return Math.max(0, Math.min(100, Math.round(group.remainingFraction * 100)));
}

function quotaBarColor(group: QuotaSummaryGroup): string {
  const percentRemaining = quotaPercentRemaining(group);
  if (percentRemaining <= 10) return "bg-red-500";
  if (percentRemaining <= 25) return "bg-orange-500";
  if (percentRemaining <= 50) return "bg-yellow-500";
  return "bg-green-500";
}

function handleQuotaRefresh(accountId: string) {
  const account = accounts.value.find((account) => account.id === accountId);
  if (account) loadAccountQuota(account, true);
}

watch(
  () => accounts.value.map((account) => `${account.id}:${account.provider}:${account.isActive}`).join("|"),
  () => {
    pruneQuotaState();
    runQuotaQueue();
  },
  { immediate: true }
);

function handlePinnedToggled() {
  refresh();
}

function handleAccountConnected() {
  refresh();
}
</script>

<template>
  <div class="space-y-6">
    <div class="sticky top-0 z-20 -mx-5 bg-background px-5 sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
      <div class="border-b border-border pb-4 pt-3">
        <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h2 class="inline-flex items-center gap-2 text-xl font-semibold">
              <ProviderPinButton
                v-if="providerMeta"
                :provider-key="providerMeta.key"
                :pinned="pinnedProviders.has(providerMeta.key)"
                @toggled="handlePinnedToggled"
              />
              {{ providerMeta?.label ?? selectedProvider.replaceAll('_', ' ') }}
              <UiBadge v-if="accounts.length > 0" variant="outline" class="text-xs tabular-nums">{{ activeAccountCount }}/{{ accounts.length }}</UiBadge>
            </h2>
          </div>
          <div class="flex w-full items-center gap-2 sm:w-auto">
            <AddAccountDialog
              v-if="providerMeta"
              :initial-provider="providerMeta.key"
              trigger-class="flex-1 sm:w-auto sm:flex-none"
              @connected="handleAccountConnected"
            />
          </div>
        </div>
      </div>
    </div>

    <DashboardDataNotice :error="error" />

    <section v-if="!isLoadingAccounts && accounts.length === 0" class="scroll-mt-24 space-y-4 md:space-y-2">
      <div class="space-y-3 pt-1">
        <p class="text-sm text-muted-foreground">{{ providerMeta?.emptyMessage ?? 'No accounts connected yet.' }}</p>
        <div v-if="supportedModels.length" class="space-y-2">
          <p class="text-xs font-medium text-muted-foreground">Supported models ({{ supportedModels.length }}):</p>
          <div class="flex flex-wrap gap-1.5">
            <UiBadge
              v-for="model in supportedModels"
              :key="model"
              variant="secondary"
              class="text-xs font-normal"
            >
              {{ model }}
            </UiBadge>
          </div>
        </div>
      </div>
    </section>
    <section v-else-if="accounts.length > 0" class="scroll-mt-24 space-y-4 md:space-y-2">
      <div v-if="supportsProviderQuota" class="space-y-2 pb-2">
        <div class="flex gap-2">
          <UiIcon name="i-lucide-gauge" class="size-4 text-muted-foreground" />
        </div>

        <div v-if="quotaSummaryGroups.length > 0" class="grid gap-2 md:grid-cols-2 xl:grid-cols-3">
          <div v-for="group in quotaSummaryGroups" :key="group.name" class="rounded-md border border-border/70 bg-muted/20 p-3">
            <div class="flex items-start justify-between gap-2 text-xs">
              <div class="flex min-w-0 items-center gap-1.5">
                <p class="truncate font-medium text-foreground">{{ group.displayName }}</p>
                <span class="shrink-0 text-[10px] text-muted-foreground">{{ group.accounts }} account{{ group.accounts === 1 ? '' : 's' }}</span>
              </div>
              <span class="font-mono text-xs text-muted-foreground">{{ quotaPercentRemaining(group) }}%</span>
            </div>
            <div class="mt-2 h-1.5 overflow-hidden rounded-full bg-muted">
              <div class="h-full transition-all duration-300" :class="quotaBarColor(group)" :style="{ width: `${quotaPercentRemaining(group)}%` }" />
            </div>
          </div>
        </div>
        <div v-else-if="activeQuotaAccounts.length > 0" class="grid gap-2 md:grid-cols-2 xl:grid-cols-3" aria-hidden="true">
          <div v-for="index in Math.min(activeQuotaAccounts.length, 3)" :key="index" class="rounded-md border border-border/70 bg-muted/20 p-3">
            <div class="flex items-center justify-between gap-2">
              <div class="flex min-w-0 items-center gap-1.5">
                <UiSkeleton class="h-3 w-24" />
                <UiSkeleton class="h-2.5 w-14" />
              </div>
              <UiSkeleton class="h-3 w-8" />
            </div>
            <div class="mt-2 h-1.5 overflow-hidden rounded-full bg-muted">
              <UiSkeleton class="h-full w-4/5 rounded-full" />
            </div>
          </div>
        </div>
      </div>

      <div class="grid gap-3 grid-cols-[repeat(auto-fill,minmax(320px,1fr))]">
        <ProviderAccountCard
          v-for="account in accounts"
          :key="account.id"
          :account="account"
          :show-tier="providerMeta?.showTier"
          :supported-models="supportedModels"
          :disabled-models="disabledModelsByAccountId[account.id] ?? []"
          :quota-info="quotaByAccountId[account.id] ?? null"
          :quota-error="quotaErrorByAccountId[account.id] ?? null"
          :is-quota-loading="Boolean(quotaLoadingByAccountId[account.id])"
          @changed="refresh"
          @refresh-quota="handleQuotaRefresh"
        />
      </div>
    </section>
  </div>
</template>

// apps/web/src/pages/dashboard/[provider].tsx
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { BY_KEY, getProviderFromSlug, type ProviderAccountKey } from "../../lib/provider-accounts";
import type { ErrorHistoryResult, ProviderDetailData, ProviderStats, QuotaGroupDisplay, QuotaProviderKey } from "../../lib/dashboard-api-types";
import { useDashboardApi } from "../../hooks/useDashboardApi";
import { useDashboardAudit } from "../../hooks/useDashboardAudit";
import { dashboardDataKeys, useDataVersion } from "../../hooks/useDashboardDataInvalidation";
import { useAccountQuotaMonitor } from "../../hooks/useAccountQuotaMonitor";
import { readCachedAccountStats, writeCachedAccountStats } from "../../hooks/useAccountStatsCache";
import { AddAccountDialog } from "../../components/AddAccountDialog";
import { DashboardDataNotice } from "../../components/DashboardDataNotice";
import { ProviderAccountCard } from "../../components/ProviderAccountCard";
import { ProviderPinButton } from "../../components/ProviderPinButton";
import { UiBadge } from "../../components/ui/UiBadge";
import { UiSkeleton } from "../../components/ui/UiSkeleton";

type Account = ProviderDetailData["accounts"][number];
type ErrorHistoryEntry = Extract<ErrorHistoryResult, { success: true }>["data"]["entries"][number];

const QUOTA_PROVIDERS = new Set<string>(["antigravity", "codex", "kiro", "openrouter", "siliconflow", "command_code", "zenmux"]);
const PROVIDER_DETAIL_REFRESH_MS = 30_000;

function toQuotaProvider(provider: string): QuotaProviderKey | null {
  return QUOTA_PROVIDERS.has(provider) ? (provider as QuotaProviderKey) : null;
}

function decodeAccountHash(hash: string): string | null {
  const raw = hash.startsWith("#") ? hash.slice(1) : hash;
  const id = raw.startsWith("account-") ? raw.slice("account-".length) : raw;
  if (!id) return null;
  try {
    return decodeURIComponent(id);
  } catch {
    return id;
  }
}

export default function ProviderPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const dashboardApi = useDashboardApi();
  const { isAuditMode } = useDashboardAudit();
  const providerSlug = location.pathname.split("/").filter(Boolean).pop() ?? "";
  const selectedProvider = getProviderFromSlug(providerSlug) as ProviderAccountKey;
  const providerMeta = BY_KEY[selectedProvider];

  const detailKey = dashboardDataKeys.accountsDetail(selectedProvider);
  const detailVersion = useDataVersion(detailKey);

  const [detailData, setDetailData] = useState<ProviderDetailData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);
  const [accountStatsById, setAccountStatsById] = useState<Record<string, ProviderStats>>({});
  const [accountStatsCursorById, setAccountStatsCursorById] = useState<Record<string, string>>({});
  const [errorHistoryByAccountId, setErrorHistoryByAccountId] = useState<Record<string, ErrorHistoryEntry[] | null>>({});
  const [errorHistoryErrorByAccountId, setErrorHistoryErrorByAccountId] = useState<Record<string, string | null>>({});
  const [highlightedAccountIds, setHighlightedAccountIds] = useState<Set<string>>(new Set());
  const highlightTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const loadDetail = useCallback(async () => {
    setIsLoading(true);
    try {
      const data = await dashboardApi.accounts.byProviderDetailed({ provider: selectedProvider });
      setDetailData(data);
      setError(null);
    } catch (err) {
      setError(err as Error);
    } finally {
      setIsLoading(false);
    }
  }, [dashboardApi, selectedProvider]);

  useEffect(() => {
    void loadDetail();
  }, [loadDetail, detailVersion]);

  useEffect(() => {
    const timer = setInterval(() => void loadDetail(), PROVIDER_DETAIL_REFRESH_MS);
    return () => clearInterval(timer);
  }, [loadDetail]);

  const accounts = useMemo(() => {
    const current = detailData?.accounts ?? [];
    return [...current].sort((a, b) => {
      const aActive = a.isActive ? 0 : 1;
      const bActive = b.isActive ? 0 : 1;
      if (aActive !== bActive) return aActive - bActive;
      return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
    });
  }, [detailData]);

  const activeAccountCount = accounts.filter((account) => account.isActive).length;
  const pinnedProviders = useMemo(() => new Set(detailData?.pinnedProviders ?? []), [detailData]);
  const supportedModels = detailData?.supportedModels ?? [];
  const supportedModelsByAccountId = detailData?.supportedModelsByAccountId ?? {};
  const disabledModelsByAccountId = detailData?.disabledModelsByAccountId ?? {};
  const modelHealthByAccountId = detailData?.modelHealthByAccountId ?? {};
  const supportsProviderQuota = QUOTA_PROVIDERS.has(selectedProvider);

  // Account stats
  useEffect(() => {
    const accountIds = accounts.map((account) => account.id);
    if (accountIds.length === 0) return;
    void (async () => {
      const cached = await readCachedAccountStats(accountIds);
      const next: Record<string, ProviderStats> = {};
      for (const [index, entry] of cached.entries()) {
        if (entry && accountIds[index] === entry.accountId) next[entry.accountId] = entry.stats;
      }
      if (Object.keys(next).length > 0) setAccountStatsById((current) => ({ ...current, ...next }));
    })();
    void (async () => {
      try {
        const response = await dashboardApi.accounts.stats({ accountIds, cursors: accountStatsCursorById });
        setAccountStatsCursorById((current) => ({ ...current, ...response.cursors }));
        if (response.stats) {
          setAccountStatsById((current) => ({ ...current, ...response.stats }));
          void writeCachedAccountStats(response.stats);
        }
      } catch (err) {
        console.error("Failed to load account stats:", err);
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [accounts, dashboardApi]);

  // Error history
  useEffect(() => {
    const accountIds = accounts.map((account) => account.id);
    if (accountIds.length === 0) return;
    void (async () => {
      try {
        const result = await dashboardApi.accounts.errorHistories({ accountIds, limit: 20 });
        if (!result.success) return;
        const next: Record<string, ErrorHistoryEntry[] | null> = {};
        for (const [accountId, value] of Object.entries(result.data)) {
          if (value.success) next[accountId] = value.data.entries;
        }
        setErrorHistoryByAccountId(next);
        setErrorHistoryErrorByAccountId({});
      } catch (err) {
        setErrorHistoryErrorByAccountId(Object.fromEntries(accountIds.map((id) => [id, (err as Error).message])));
      }
    })();
  }, [accounts, dashboardApi]);

  // Quota monitor
  const { quotaByAccountId, quotaErrorByAccountId, quotaLoadingByAccountId, runQuotaQueue } = useAccountQuotaMonitor({
    accounts,
    quotaCapableAccounts: accounts.filter((account) => supportsProviderQuota),
    toQuotaProvider,
  });

  useEffect(() => {
    if (!supportsProviderQuota) return;
    const timer = setTimeout(() => {
      void runQuotaQueue(undefined, { refreshExisting: false });
    }, 400);
    return () => clearTimeout(timer);
  }, [supportsProviderQuota, runQuotaQueue, accounts.length]);

  // Hash highlight
  useEffect(() => {
    const raw = location.hash.startsWith("#") ? location.hash.slice(1) : location.hash;
    if (!raw.startsWith("account-")) return;
    const id = decodeAccountHash(raw);
    if (!id) return;
    setHighlightedAccountIds((current) => {
      const next = new Set(current);
      next.add(id);
      return next;
    });
    if (highlightTimer.current) clearTimeout(highlightTimer.current);
    highlightTimer.current = setTimeout(() => {
      setHighlightedAccountIds(new Set());
      highlightTimer.current = null;
    }, 2500);
    navigate(location.pathname, { replace: true });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [location.hash]);

  // Quota summary groups
  const quotaSummaryGroups = useMemo(() => {
    const groups = new Map<string, { displayName: string; name: string; remainingFraction: number; maxRequests: number; usedRequests: number; accounts: number }>();
    for (const account of accounts) {
      const quota = quotaByAccountId[account.id];
      if (!quota) continue;
      for (const group of quota.groups) {
        const existing = groups.get(group.name);
        if (!existing) {
          groups.set(group.name, { name: group.name, displayName: group.displayName, remainingFraction: 0, maxRequests: 0, usedRequests: 0, accounts: 0 });
        }
        const current = groups.get(group.name)!;
        current.accounts += 1;
        current.remainingFraction = Math.max(current.remainingFraction, group.remainingFraction);
        current.maxRequests = Math.max(current.maxRequests, group.maxRequests);
        current.usedRequests = Math.max(current.usedRequests, group.usedRequests);
      }
    }
    return [...groups.values()];
  }, [quotaByAccountId, accounts]);

  const quotaPercentRemaining = (group: { remainingFraction: number }) => Math.round(group.remainingFraction * 100);
  const quotaBarColor = (group: { remainingFraction: number }) => {
    const percent = quotaPercentRemaining(group);
    if (percent > 50) return "bg-emerald-500";
    if (percent > 20) return "bg-yellow-500";
    return "bg-destructive";
  };

  const handleAccountConnected = () => void loadDetail();
  const handleAccountRenamed = () => void loadDetail();
  const handleAccountActiveUpdated = () => void loadDetail();
  const handleAccountDeleted = () => void loadDetail();
  const handleAccountErrorsResolved = () => void loadDetail();

  const isLoadingAccounts = isLoading || (!detailData && !error);

  return (
    <div className="space-y-6">
      <div className="dashboard-header-divider">
        <div className="flex min-h-9 flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <h2 className="inline-flex min-h-9 items-center gap-2 text-xl font-semibold">
            {providerMeta ? <ProviderPinButton providerKey={providerMeta.key} pinned={pinnedProviders.has(providerMeta.key)} readonly={isAuditMode} /> : null}
            {providerMeta?.label ?? selectedProvider.replaceAll("_", " ")}
            {accounts.length > 0 ? <UiBadge variant="outline" className="text-xs">{activeAccountCount}/{accounts.length}</UiBadge> : null}
          </h2>
          <div className="flex w-full items-center sm:w-auto">
            {providerMeta ? (
              <AddAccountDialog initialProvider={providerMeta.key} readonly={isAuditMode} triggerClass="flex-1 sm:w-auto sm:flex-none" onConnected={handleAccountConnected} />
            ) : null}
          </div>
        </div>
      </div>

      <DashboardDataNotice error={error} />

      {!isLoadingAccounts && accounts.length === 0 ? (
        <section className="scroll-mt-24 space-y-4 md:space-y-2">
          <div className="space-y-3 pt-1">
            <p className="text-sm text-muted-foreground">{providerMeta?.emptyMessage ?? "No accounts connected yet."}</p>
            {supportedModels.length ? (
              <div className="space-y-2">
                <div className="flex flex-wrap gap-1.5">
                  {supportedModels.map((model) => (
                    <UiBadge key={model} variant="secondary" className="text-xs font-normal">{model}</UiBadge>
                  ))}
                </div>
              </div>
            ) : null}
          </div>
        </section>
      ) : accounts.length > 0 ? (
        <section className="scroll-mt-24 space-y-4 md:space-y-2">
          {supportsProviderQuota && quotaSummaryGroups.length > 0 ? (
            <div className="space-y-2 pb-2 md:mb-4 md:rounded-xl md:border md:border-border md:bg-card md:p-4">
              <div className="grid gap-x-6 gap-y-3" style={{ gridTemplateColumns: `repeat(${quotaSummaryGroups.length}, minmax(0, 1fr))` }}>
                {quotaSummaryGroups.map((group) => (
                  <div key={group.name} className="space-y-1.5">
                    <div className="flex items-start justify-between gap-2 text-xs">
                      <div className="flex min-w-0 items-center gap-1.5">
                        <p className="truncate font-medium text-foreground">{group.displayName}</p>
                        <span className="shrink-0 text-[10px] text-muted-foreground">{group.accounts} account{group.accounts === 1 ? "" : "s"}</span>
                      </div>
                      <span className="font-mono text-xs text-muted-foreground">{quotaPercentRemaining(group)}%</span>
                    </div>
                    <div className="h-1.5 overflow-hidden rounded-full bg-muted">
                      <div className={cnBar(quotaBarColor(group))} style={{ width: `${quotaPercentRemaining(group)}%` }} />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ) : null}

          {isLoadingAccounts ? <UiSkeleton className="h-96 rounded-xl" /> : null}

          <div className="dashboard-card-grid">
            {accounts.map((account) => (
              <ProviderAccountCard
                key={account.id}
                id={account.id}
                account={{ ...account, stats: accountStatsById[account.id] }}
                showTier={providerMeta?.showTier}
                supportedModels={supportedModelsByAccountId[account.id] ?? supportedModels}
                disabledModels={disabledModelsByAccountId[account.id] ?? []}
                modelHealth={modelHealthByAccountId[account.id] ?? {}}
                errorHistory={errorHistoryByAccountId[account.id] ?? null}
                errorHistoryError={errorHistoryErrorByAccountId[account.id] ?? null}
                quotaInfo={quotaByAccountId[account.id] ?? null}
                quotaError={quotaErrorByAccountId[account.id] ?? null}
                quotaLoading={quotaLoadingByAccountId[account.id] ?? false}
                highlight={highlightedAccountIds.has(account.id)}
                readonly={isAuditMode}
                onRenamed={handleAccountRenamed}
                onActiveUpdated={handleAccountActiveUpdated}
                onDeleted={handleAccountDeleted}
                onErrorsResolved={handleAccountErrorsResolved}
              />
            ))}
          </div>
        </section>
      ) : null}
    </div>
  );
}

function cnBar(color: string): string {
  return `h-full transition-all duration-300 ${color}`;
}
