// apps/dashboard/app/components/AddAccountDialog.vue
<script setup lang="ts">
import type { ProviderAccountKey } from "../../lib/provider-accounts";
import { cn } from "../../lib/utils";

type Provider = ProviderAccountKey;
type FlowType = "oauth_redirect" | "device_code" | "api_key" | "api_key_with_account_id";

interface ProviderConfig {
  name: string;
  description: string;
  flowType: FlowType;
  apiKeyPortalUrl?: string;
  apiKeyPlaceholder?: string;
  accountIdPlaceholder?: string;
  accountIdLabel?: string;
}

const props = withDefaults(
  defineProps<{
    initialProvider?: Provider | null;
    triggerClass?: string;
  }>(),
  {
    initialProvider: null,
    triggerClass: "",
  }
);

const emit = defineEmits<{
  connected: [result: { provider: Provider; email: string; isUpdate: boolean }];
}>();

const dashboardApi = useDashboardApi();

const providerConfigs: Record<Provider, ProviderConfig> = {
  antigravity: { name: "Antigravity", description: "Access Gemini & Claude via Google OAuth", flowType: "oauth_redirect" },
  gemini_cli: { name: "Gemini CLI", description: "Access Gemini 2.5 Pro & 3 models", flowType: "oauth_redirect" },
  qwen_code: { name: "Qwen Code", description: "Access Qwen Coder models", flowType: "device_code" },
  copilot: { name: "Copilot", description: "Access GitHub Copilot chat models", flowType: "device_code" },
  codex: { name: "Codex", description: "Access GPT-5 Codex models", flowType: "device_code" },
  kiro: { name: "Kiro", description: "Access Claude via Kiro OAuth", flowType: "oauth_redirect" },
  nvidia_nim: { name: "Nvidia", description: "Access NIM models with direct API key", flowType: "api_key", apiKeyPortalUrl: "https://build.nvidia.com/settings/api-keys", apiKeyPlaceholder: "nvapi-..." },
  ollama_cloud: { name: "Ollama Cloud", description: "Access Ollama Cloud via OpenAI-compatible API", flowType: "api_key", apiKeyPortalUrl: "https://ollama.com/settings/keys", apiKeyPlaceholder: "ollama_..." },
  openrouter: { name: "OpenRouter", description: "Access OpenRouter free models via API key", flowType: "api_key", apiKeyPortalUrl: "https://openrouter.ai/settings/keys", apiKeyPlaceholder: "sk-or-v1-..." },
  groq: { name: "Groq", description: "Access ultra-fast LLM inference via Groq API", flowType: "api_key", apiKeyPortalUrl: "https://console.groq.com/keys", apiKeyPlaceholder: "gsk_..." },
  cerebras: { name: "Cerebras", description: "Access ultra-fast open-source models via Cerebras API", flowType: "api_key", apiKeyPortalUrl: "https://cloud.cerebras.ai", apiKeyPlaceholder: "csk-..." },
  kilo_code: { name: "Kilo Code", description: "Access free & auto-routed models via Kilo Gateway", flowType: "api_key", apiKeyPortalUrl: "https://app.kilo.ai", apiKeyPlaceholder: "sk-..." },
  workers_ai: { name: "Workers AI", description: "Access open-source models on Cloudflare's global network", flowType: "api_key_with_account_id", apiKeyPortalUrl: "https://dash.cloudflare.com/?to=/:account/ai/workers-ai", apiKeyPlaceholder: "Bearer token...", accountIdPlaceholder: "e.g. 1a2b3c4d5e6f...", accountIdLabel: "Cloudflare Account ID" },
};

const oauthProviders: Provider[] = ["antigravity", "codex", "kiro", "gemini_cli", "qwen_code", "copilot"];
const apiKeyProviders: Provider[] = ["ollama_cloud", "openrouter", "nvidia_nim", "groq", "cerebras", "kilo_code", "workers_ai"];

const open = ref(false);
const minimumStep = computed(() => (props.initialProvider ? 2 : 1));
const step = ref(minimumStep.value);
const provider = ref<Provider | null>(props.initialProvider);
const callbackUrl = ref("");
const apiKey = ref("");
const cfAccountId = ref("");
const authUrl = ref("");
const oauthState = ref<string | null>(null);
const oauthCodeVerifier = ref<string | null>(null);
const deviceCodeInfo = ref<{ provider: "qwen_code" | "copilot" | "codex"; deviceCode: string; userCode: string; verificationUrl: string; codeVerifier?: string } | null>(null);
const copiedLink = ref(false);
const copiedDeviceCode = ref(false);
const isApiKeyVisible = ref(false);
const isLoading = ref(false);
const isFetchingUrl = ref(false);
const isPolling = ref(false);
const errorMessage = ref("");
let pollingTimer: ReturnType<typeof setTimeout> | null = null;

const selectedConfig = computed(() => (provider.value ? providerConfigs[provider.value] : null));
const dialogOpen = computed({
  get: () => open.value,
  set: (value: boolean) => {
    if (!value && isLoading.value) return;
    open.value = value;
  },
});
const displayedSteps = computed(() => (props.initialProvider ? [2, 3] : [1, 2, 3]));
const shouldPreventOutsideClose = computed(() => {
  const flowType = selectedConfig.value?.flowType;
  return isPolling.value || (step.value === 2 && (flowType === "api_key" || flowType === "api_key_with_account_id")) || (step.value === 3 && flowType === "oauth_redirect");
});

watch(open, (value) => {
  if (value) {
    step.value = minimumStep.value;
    provider.value = props.initialProvider;
    return;
  }

  resetForm();
});

watch([open, step, provider], async () => {
  if (!open.value || step.value !== 2 || !provider.value || !selectedConfig.value) return;

  errorMessage.value = "";
  authUrl.value = "";
  oauthState.value = null;
  oauthCodeVerifier.value = null;
  deviceCodeInfo.value = null;
  isFetchingUrl.value = true;

  try {
    if (selectedConfig.value.flowType === "oauth_redirect") {
      const result = await dashboardApi.accounts.getAuthUrl({ provider: provider.value as "antigravity" | "gemini_cli" | "codex" | "kiro" });
      if (!result.success) throw new Error(result.error);
      authUrl.value = result.data.authUrl;
      oauthState.value = result.data.state;
      oauthCodeVerifier.value = result.data.codeVerifier;
      return;
    }

    if (selectedConfig.value.flowType === "device_code") {
      const result = await dashboardApi.accounts.initiateDeviceAuth({ provider: provider.value as "qwen_code" | "copilot" | "codex" });
      if (!result.success) throw new Error(result.error);
      deviceCodeInfo.value = {
        provider: provider.value as "qwen_code" | "copilot" | "codex",
        deviceCode: result.data.deviceCode,
        userCode: result.data.userCode,
        verificationUrl: result.data.verificationUrlComplete || result.data.verificationUrl,
        codeVerifier: "codeVerifier" in result.data && typeof result.data.codeVerifier === "string" ? result.data.codeVerifier : undefined,
      };
      return;
    }

    authUrl.value = selectedConfig.value.apiKeyPortalUrl ?? "";
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : "Failed to start account connection";
  } finally {
    isFetchingUrl.value = false;
  }
});

function resetForm() {
  step.value = minimumStep.value;
  provider.value = props.initialProvider;
  callbackUrl.value = "";
  apiKey.value = "";
  cfAccountId.value = "";
  authUrl.value = "";
  oauthState.value = null;
  oauthCodeVerifier.value = null;
  deviceCodeInfo.value = null;
  copiedLink.value = false;
  copiedDeviceCode.value = false;
  isApiKeyVisible.value = false;
  isLoading.value = false;
  isFetchingUrl.value = false;
  isPolling.value = false;
  errorMessage.value = "";
  if (pollingTimer) {
    clearTimeout(pollingTimer);
    pollingTimer = null;
  }
}

function closeAndReset() {
  open.value = false;
  resetForm();
}

async function refreshConnectedAccountData(providerKey: Provider) {
  const keys = [
    "dashboard-shell-accounts",
    "dashboard-accounts-summary",
    "dashboard-models",
    "dashboard-shell-model-family-counts",
    "layout-model-search",
    "dashboard-playground-options",
    "dashboard-api-keys",
  ];

  if (providerKey) {
    keys.push(`dashboard-accounts-detail-${providerKey}`);
  }

  await refreshNuxtData(keys);
}

function finishConnection(result: { email: string; isUpdate: boolean }) {
  const connectedProvider = provider.value;
  if (!connectedProvider) return;

  open.value = false;
  emit("connected", { provider: connectedProvider, ...result });
  void refreshConnectedAccountData(connectedProvider);
}

function selectProvider(providerKey: Provider) {
  provider.value = providerKey;
  step.value = 2;
}

function callbackPlaceholder(providerKey: Provider | null) {
  if (providerKey === "kiro") return "http://localhost:49153/oauth/callback?code=...";
  if (providerKey === "codex") return "http://localhost:1455/auth/callback?code=...";
  return "http://localhost:1/oauth2callback?code=...";
}

async function copyText(value: string, target: "link" | "code") {
  try {
    await navigator.clipboard.writeText(value);
    if (target === "link") {
      copiedLink.value = true;
      setTimeout(() => (copiedLink.value = false), 1800);
    } else {
      copiedDeviceCode.value = true;
      setTimeout(() => (copiedDeviceCode.value = false), 1800);
    }
  } catch {
    errorMessage.value = target === "link" ? "Failed to copy link" : "Failed to copy code";
    return;
  }

  if (target === "link" && selectedConfig.value && ["api_key", "api_key_with_account_id"].includes(selectedConfig.value.flowType) && step.value === 2) {
    step.value = 3;
  }

  if (target === "link" && selectedConfig.value?.flowType === "device_code") {
    startDevicePolling(null);
  }
}

function openPopup(url: string, name: string, width: number, height: number) {
  const left = Math.round((window.screen.width - width) / 2);
  const top = Math.round((window.screen.height - height) / 2);
  const popup = window.open(url, name, `width=${width},height=${height},left=${left},top=${top},scrollbars=yes,resizable=yes`);
  if (!popup || popup.closed) {
    window.open(url, "_blank");
    return null;
  }

  return popup;
}

function openOAuthUrl() {
  if (!authUrl.value) return;
  openPopup(authUrl.value, "oauth_popup", 600, 700);
  setTimeout(() => (step.value = 3), 600);
}

function openDeviceAuthUrl() {
  if (!deviceCodeInfo.value) return;
  const popup = openPopup(deviceCodeInfo.value.verificationUrl, "device_auth_popup", 600, 700);
  startDevicePolling(popup);
}

function openApiKeyPortal() {
  if (!selectedConfig.value?.apiKeyPortalUrl) return;
  openPopup(selectedConfig.value.apiKeyPortalUrl, "api_key_portal_popup", 1100, 760);
  if (step.value === 2) setTimeout(() => (step.value = 3), 600);
}

function startDevicePolling(popup: Window | null) {
  if (!deviceCodeInfo.value || isPolling.value) return;

  isPolling.value = true;
  errorMessage.value = "";
  const startedAt = Date.now();
  let intervalMs = 8000;

  const stopPolling = () => {
    isPolling.value = false;
    if (pollingTimer) {
      clearTimeout(pollingTimer);
      pollingTimer = null;
    }
  };

  const poll = async () => {
    if (!deviceCodeInfo.value) return;

    if (Date.now() - startedAt >= 900_000) {
      errorMessage.value = "Device code expired. Please try again.";
      stopPolling();
      return;
    }

    try {
      const result = await dashboardApi.accounts.pollDeviceAuth({
        provider: deviceCodeInfo.value.provider,
        deviceCode: deviceCodeInfo.value.deviceCode,
        userCode: deviceCodeInfo.value.userCode,
        codeVerifier: deviceCodeInfo.value.codeVerifier,
      });

      if (!result.success) throw new Error(result.error);

      if (result.data.status === "success") {
        if (popup && !popup.closed) popup.close();
        finishConnection({ email: result.data.email, isUpdate: result.data.isUpdate });
        return;
      }

      if (result.data.status === "error") {
        errorMessage.value = result.data.message;
        stopPolling();
        return;
      }

      if (typeof result.data.retryAfterSeconds === "number" && result.data.retryAfterSeconds > 0) {
        intervalMs = result.data.retryAfterSeconds * 1000;
      }
    } catch (error) {
      errorMessage.value = error instanceof Error ? error.message : "Failed to check authorization status";
    }

    pollingTimer = setTimeout(poll, intervalMs);
  };

  pollingTimer = setTimeout(poll, intervalMs);
}

async function handleConnectApiKey() {
  if (!provider.value || !selectedConfig.value) return;

  errorMessage.value = "";
  if (!apiKey.value.trim()) {
    errorMessage.value = selectedConfig.value.flowType === "api_key_with_account_id" ? "Please enter an API token" : "Please enter an API key";
    return;
  }

  if (selectedConfig.value.flowType === "api_key_with_account_id" && !cfAccountId.value.trim()) {
    errorMessage.value = `Please enter the ${selectedConfig.value.accountIdLabel}`;
    return;
  }

  isLoading.value = true;
  try {
    const result = await dashboardApi.accounts.create({ provider: provider.value, token: apiKey.value.trim(), cfAccountId: cfAccountId.value.trim() || undefined });
    if (!result.success) throw new Error(result.error);
    finishConnection(result.data);
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : "Failed to connect account";
  } finally {
    isLoading.value = false;
  }
}

async function handleExchangeOAuth() {
  if (!provider.value) return;

  errorMessage.value = "";
  if (!callbackUrl.value.trim()) {
    errorMessage.value = "Please paste the callback URL";
    return;
  }

  if (!callbackUrl.value.includes("code=")) {
    errorMessage.value = "Invalid URL. Make sure the URL contains 'code=' parameter.";
    return;
  }

  isLoading.value = true;
  try {
    const result = await dashboardApi.accounts.exchangeOAuth({ provider: provider.value as "antigravity" | "gemini_cli" | "codex" | "kiro", callbackUrl: callbackUrl.value.trim(), state: oauthState.value, codeVerifier: oauthCodeVerifier.value });
    if (!result.success) throw new Error(result.error);
    finishConnection(result.data);
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : "Failed to connect account";
  } finally {
    isLoading.value = false;
  }
}

function goBack() {
  step.value = Math.max(minimumStep.value, step.value - 1);
}

onBeforeUnmount(() => {
  if (pollingTimer) {
    clearTimeout(pollingTimer);
    pollingTimer = null;
  }
});
</script>

<template>
  <UiButton :class="cn('gap-2', triggerClass)" @click="open = true">
    <UiIcon name="i-lucide-plus" class="size-4" />
    Add Account
  </UiButton>

  <UiDialog
    v-model:open="dialogOpen"
    :prevent-outside-close="shouldPreventOutsideClose"
    :prevent-escape-close="isPolling"
    :ui="{ content: 'max-h-[calc(100dvh-1rem)] p-4 sm:max-w-md sm:p-6' }"
  >
    <template #content>
      <div class="space-y-1.5 pr-6">
        <h2 class="text-lg font-semibold leading-none tracking-tight">
          {{ selectedConfig ? `Add ${selectedConfig.name} Account` : 'Add Provider Account' }}
        </h2>
        <p class="sr-only">
          {{ selectedConfig ? `Connect a new ${selectedConfig.name} account for load balancing` : 'Connect a new AI provider account for load balancing' }}
        </p>
      </div>

      <div class="flex items-center justify-center">
        <template v-for="(stepNumber, index) in displayedSteps" :key="stepNumber">
          <div class="flex items-center">
            <div
              :class="cn(
                'flex h-8 w-8 items-center justify-center rounded-full text-sm font-medium transition-colors',
                step >= stepNumber ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground',
              )"
            >
              <UiIcon v-if="step > stepNumber" name="i-lucide-check" class="size-4" />
              <span v-else>{{ index + 1 }}</span>
            </div>
            <div v-if="index < displayedSteps.length - 1" :class="cn('h-px w-10 transition-colors', step > stepNumber ? 'bg-primary' : 'bg-border')" />
          </div>
        </template>
      </div>

      <div class="min-h-0 flex-1 space-y-4 overflow-y-auto">
        <div v-if="step === 1" class="space-y-4">
          <div class="space-y-2">
            <p class="text-sm font-medium">OAuth Providers</p>
            <div class="grid grid-cols-2 gap-3 sm:grid-cols-3">
              <button
                v-for="providerKey in oauthProviders"
                :key="providerKey"
                type="button"
                :class="cn(
                  'flex cursor-pointer flex-col items-center gap-2 rounded-lg border-2 p-3 text-center transition-all hover:border-primary hover:bg-accent',
                  provider === providerKey ? 'border-primary bg-accent' : 'border-border',
                )"
                @click="selectProvider(providerKey)"
              >
                <span class="text-sm font-medium">{{ providerConfigs[providerKey].name }}</span>
              </button>
            </div>
          </div>

          <div class="space-y-2">
            <p class="text-sm font-medium">API Key Providers</p>
            <div class="grid grid-cols-2 gap-3 sm:grid-cols-3">
              <button
                v-for="providerKey in apiKeyProviders"
                :key="providerKey"
                type="button"
                :class="cn(
                  'flex cursor-pointer flex-col items-center gap-2 rounded-lg border-2 p-3 text-center transition-all hover:border-primary hover:bg-accent',
                  provider === providerKey ? 'border-primary bg-accent' : 'border-border',
                )"
                @click="selectProvider(providerKey)"
              >
                <span class="text-sm font-medium">{{ providerConfigs[providerKey].name }}</span>
              </button>
            </div>
          </div>
        </div>

        <div v-if="step === 2 && selectedConfig" class="space-y-4">
          <template v-if="selectedConfig.flowType === 'oauth_redirect'">
            <div class="space-y-2">
              <p class="text-sm font-medium">Login to {{ selectedConfig.name }}</p>
              <p class="text-sm text-muted-foreground">
                Click the button below to open the login page in a new window. After logging in, you'll be redirected to a page that shows an error - this is expected.
              </p>
            </div>
            <div class="flex gap-2">
              <UiButton variant="outline" class="flex-1" :disabled="isFetchingUrl || !authUrl" @click="openOAuthUrl">
                <UiIcon :name="isFetchingUrl ? 'i-lucide-loader-2' : 'i-lucide-external-link'" :class="['size-4', isFetchingUrl ? 'animate-spin' : '']" />
                Open {{ selectedConfig.name }} Login
              </UiButton>
              <UiButton variant="outline" :disabled="isFetchingUrl || !authUrl" :title="copiedLink ? 'Copied!' : 'Copy login link'" @click="copyText(authUrl, 'link')">
                <UiIcon :name="copiedLink ? 'i-lucide-check' : 'i-lucide-copy'" class="size-4" />
              </UiButton>
            </div>
            <div class="relative w-full rounded-lg border px-4 py-3 text-sm">
              <UiIcon name="i-lucide-alert-circle" class="absolute left-4 top-4 size-4" />
              <div class="pl-7 text-xs">
                After login, copy the URL from address bar:
                <code class="rounded bg-muted px-1">{{ callbackPlaceholder(provider) }}</code>
              </div>
            </div>
          </template>

          <template v-else-if="selectedConfig.flowType === 'device_code'">
            <div class="space-y-2">
              <p class="text-sm font-medium">Login to {{ selectedConfig.name }}</p>
              <p class="text-sm text-muted-foreground">
                Click the button below to open the provider login page. Enter the code shown below on the provider login page. After you complete the login, authorization will be detected automatically.
              </p>
            </div>
            <div v-if="deviceCodeInfo?.userCode" class="rounded-md border border-border bg-muted/30 p-3">
              <p class="text-xs text-muted-foreground">Enter this code on the provider page:</p>
              <div class="mt-2 flex flex-wrap items-center gap-2">
                <code class="rounded bg-background px-2 py-1 font-mono text-sm font-semibold tracking-[0.15em]">{{ deviceCodeInfo.userCode }}</code>
                <UiButton type="button" size="sm" variant="outline" :title="copiedDeviceCode ? 'Copied!' : 'Copy code'" @click="copyText(deviceCodeInfo.userCode, 'code')">
                  <UiIcon :name="copiedDeviceCode ? 'i-lucide-check' : 'i-lucide-copy'" class="size-3.5" />
                  {{ copiedDeviceCode ? 'Copied' : 'Copy code' }}
                </UiButton>
              </div>
            </div>
            <div class="flex gap-2">
              <UiButton variant="outline" class="flex-1" :disabled="isFetchingUrl || !deviceCodeInfo || isPolling" @click="openDeviceAuthUrl">
                <UiIcon :name="isFetchingUrl || isPolling ? 'i-lucide-loader-2' : 'i-lucide-external-link'" :class="['size-4', isFetchingUrl || isPolling ? 'animate-spin' : '']" />
                {{ isPolling ? 'Waiting for login...' : `Open ${selectedConfig.name} Login` }}
              </UiButton>
              <UiButton variant="outline" :disabled="isFetchingUrl || !deviceCodeInfo" :title="copiedLink ? 'Copied!' : 'Copy login link'" @click="deviceCodeInfo && copyText(deviceCodeInfo.verificationUrl, 'link')">
                <UiIcon :name="copiedLink ? 'i-lucide-check' : 'i-lucide-copy'" class="size-4" />
              </UiButton>
            </div>
            <div v-if="isPolling" class="relative w-full rounded-lg border px-4 py-3 text-sm">
              <UiIcon name="i-lucide-loader-2" class="absolute left-4 top-4 size-4 animate-spin" />
              <div class="pl-7 text-xs">
                Complete the login in your browser. This dialog will close automatically when authorization is complete.
              </div>
            </div>
          </template>

          <template v-else>
            <div class="space-y-2">
              <p class="text-sm font-medium">Get {{ selectedConfig.name }} API Key</p>
              <p class="text-sm text-muted-foreground">
                Open the provider page below and create or copy your API key. You will continue to the next step automatically.
              </p>
            </div>
            <div class="rounded-md border border-border bg-muted/30 p-3">
              <p class="break-all text-xs text-muted-foreground">{{ selectedConfig.apiKeyPortalUrl }}</p>
            </div>
            <div class="flex gap-2">
              <UiButton type="button" variant="outline" class="flex-1" @click="openApiKeyPortal">
                <UiIcon name="i-lucide-external-link" class="size-4" />
                Open {{ selectedConfig.name }} Portal
              </UiButton>
              <UiButton type="button" variant="outline" :title="copiedLink ? 'Copied!' : 'Copy API key portal link'" @click="authUrl && copyText(authUrl, 'link')">
                <UiIcon :name="copiedLink ? 'i-lucide-check' : 'i-lucide-copy'" class="size-4" />
              </UiButton>
            </div>
          </template>

          <div v-if="errorMessage" class="relative w-full rounded-lg border border-destructive/50 px-4 py-3 text-sm text-destructive">
            <UiIcon name="i-lucide-alert-circle" class="absolute left-4 top-4 size-4" />
            <div class="pl-7 text-xs">{{ errorMessage }}</div>
          </div>
        </div>

        <form v-if="step === 3 && selectedConfig?.flowType === 'oauth_redirect'" class="space-y-4" @submit.prevent="handleExchangeOAuth">
          <div class="space-y-2">
            <label for="callback-url" class="text-sm font-medium">
              Paste Callback URL <span aria-hidden="true" class="text-destructive">*</span>
            </label>
            <p class="text-sm text-muted-foreground">Paste the URL from your browser after the OAuth redirect.</p>
            <input
              id="callback-url"
              v-model="callbackUrl"
              type="text"
              :placeholder="callbackPlaceholder(provider)"
              :disabled="isLoading"
              autofocus
              class="h-9 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:opacity-50"
            >
            <p v-if="errorMessage" class="text-sm text-destructive">{{ errorMessage }}</p>
          </div>
          <UiButton type="submit" class="w-full" :disabled="isLoading">
            <UiIcon v-if="isLoading" name="i-lucide-loader-2" class="size-4 animate-spin" />
            {{ isLoading ? 'Connecting...' : `Connect ${selectedConfig.name} Account` }}
          </UiButton>
        </form>

        <form
          v-if="step === 3 && selectedConfig && (selectedConfig.flowType === 'api_key' || selectedConfig.flowType === 'api_key_with_account_id')"
          class="space-y-4"
          autocomplete="off"
          data-lpignore="true"
          data-1p-ignore="true"
          @submit.prevent="handleConnectApiKey"
        >
          <div class="space-y-2">
            <p class="text-sm font-medium">Connect {{ selectedConfig.name }}</p>
            <p class="text-sm text-muted-foreground">
              {{ selectedConfig.flowType === 'api_key_with_account_id' ? 'Paste your API token and Account ID. Credentials will be stored encrypted.' : 'Paste your provider API key directly. The key will be stored encrypted.' }}
            </p>
          </div>

          <div class="space-y-2">
            <label for="provider-api-key" class="text-sm font-medium">
              {{ selectedConfig.flowType === 'api_key_with_account_id' ? 'API Token' : 'API Key' }} <span aria-hidden="true" class="text-destructive">*</span>
            </label>
            <div class="relative">
              <input
                id="provider-api-key"
                v-model="apiKey"
                type="text"
                name="provider-token"
                autocomplete="off"
                autocorrect="off"
                autocapitalize="none"
                spellcheck="false"
                data-lpignore="true"
                data-1p-ignore="true"
                :placeholder="selectedConfig.apiKeyPlaceholder"
                :disabled="isLoading"
                autofocus
                :class="cn(
                  'h-9 w-full rounded-md border border-input bg-background px-3 pr-9 text-sm outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:opacity-50',
                  isApiKeyVisible ? '' : '[text-security:disc] [-webkit-text-security:disc]',
                )"
              >
              <button
                type="button"
                :disabled="isLoading"
                class="absolute right-2.5 top-1/2 -translate-y-1/2 text-muted-foreground transition-colors hover:text-foreground disabled:opacity-50"
                :aria-label="isApiKeyVisible ? 'Hide API key' : 'Show API key'"
                @click="isApiKeyVisible = !isApiKeyVisible"
              >
                <UiIcon :name="isApiKeyVisible ? 'i-lucide-eye-off' : 'i-lucide-eye'" class="size-4" />
              </button>
            </div>
          </div>

          <div v-if="selectedConfig.flowType === 'api_key_with_account_id'" class="space-y-2">
            <label for="provider-account-id" class="text-sm font-medium">
              {{ selectedConfig.accountIdLabel }} <span aria-hidden="true" class="text-destructive">*</span>
            </label>
            <input
              id="provider-account-id"
              v-model="cfAccountId"
              type="text"
              name="provider-account-id"
              autocomplete="off"
              autocorrect="off"
              autocapitalize="none"
              spellcheck="false"
              data-lpignore="true"
              data-1p-ignore="true"
              :placeholder="selectedConfig.accountIdPlaceholder"
              :disabled="isLoading"
              class="h-9 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:opacity-50"
            >
          </div>

          <p v-if="errorMessage" class="text-sm text-destructive">{{ errorMessage }}</p>

          <UiButton type="submit" class="w-full" :disabled="isLoading">
            <UiIcon v-if="isLoading" name="i-lucide-loader-2" class="size-4 animate-spin" />
            {{ isLoading ? 'Connecting...' : `Connect ${selectedConfig.name} Account` }}
          </UiButton>
        </form>
      </div>

      <div class="flex flex-row items-center justify-between gap-2">
        <UiButton v-if="isPolling" type="button" variant="ghost" @click="closeAndReset">Cancel</UiButton>

        <UiButton v-if="step > minimumStep && !isPolling" type="button" variant="ghost" :disabled="isLoading" @click="goBack">
          <UiIcon name="i-lucide-arrow-left" class="size-4" />
          Back
        </UiButton>

        <UiButton v-if="step === 2 && selectedConfig && selectedConfig.flowType !== 'device_code'" type="button" variant="ghost" class="ml-auto" @click="step = 3">
          Next
          <UiIcon name="i-lucide-arrow-right" class="size-4" />
        </UiButton>
      </div>
    </template>
  </UiDialog>
</template>

// components/dashboard/accounts/add-account-dialog.tsx
"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Alert, AlertDescription } from "@/components/ui/alert";
import {
  Loader2,
  ExternalLink,
  AlertCircle,
  Plus,
  ArrowLeft,
  ArrowRight,
  Check,
  Copy,
} from "lucide-react";
import { toast } from "sonner";
import {
  exchangeIflowOAuthCode,
  exchangeAntigravityOAuthCode,
  exchangeGeminiCliOAuthCode,
  exchangeCodexOAuthCode,
  getIflowAuthUrl,
  getAntigravityAuthUrl,
  getGeminiCliAuthUrl,
  getCodexAuthUrl,
  initiateQwenCodeAuth,
  pollQwenCodeAuth,
} from "@/lib/actions/accounts";
import { cn } from "@/lib/utils";

type Provider = "iflow" | "antigravity" | "qwen_code" | "gemini_cli" | "codex" | null;

interface OAuthRedirectConfig {
  flowType: "oauth_redirect";
  getAuthUrl: () => Promise<{ success: true; data: { authUrl: string } } | { success: false; error: string }>;
  exchangeAction: (callbackUrl: string) => Promise<{ success: true; data: { email: string; isUpdate: boolean } } | { success: false; error: string }>;
}

interface DeviceCodeConfig {
  flowType: "device_code";
}

interface ProviderConfig {
  name: string;
  description: string;
}

type ProviderFullConfig = ProviderConfig & (OAuthRedirectConfig | DeviceCodeConfig);

const PROVIDERS: Record<Exclude<Provider, null>, ProviderFullConfig> = {
  iflow: {
    name: "Iflow",
    description: "Access OpenAI compatible API",
    flowType: "oauth_redirect",
    getAuthUrl: getIflowAuthUrl,
    exchangeAction: exchangeIflowOAuthCode,
  },
  antigravity: {
    name: "Antigravity",
    description: "Access Gemini & Claude via Google OAuth",
    flowType: "oauth_redirect",
    getAuthUrl: getAntigravityAuthUrl,
    exchangeAction: exchangeAntigravityOAuthCode,
  },
  gemini_cli: {
    name: "Gemini CLI",
    description: "Access Gemini 2.5 Pro & 3 models",
    flowType: "oauth_redirect",
    getAuthUrl: getGeminiCliAuthUrl,
    exchangeAction: exchangeGeminiCliOAuthCode,
  },
  qwen_code: {
    name: "Qwen Code",
    description: "Access Qwen Coder models",
    flowType: "device_code",
  },
  codex: {
    name: "Codex",
    description: "Access GPT-5 Codex models",
    flowType: "oauth_redirect",
    getAuthUrl: getCodexAuthUrl,
    exchangeAction: exchangeCodexOAuthCode,
  },
};



export function AddAccountDialog() {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [step, setStep] = useState(1);
  const [provider, setProvider] = useState<Provider>(null);
  const [callbackUrl, setCallbackUrl] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  
  // OAuth redirect flow state
  const [authUrl, setAuthUrl] = useState("");
  const [isFetchingUrl, setIsFetchingUrl] = useState(false);
  
  // Device code flow state
  const [deviceCodeInfo, setDeviceCodeInfo] = useState<{
    deviceCode: string;
    verificationUrl: string;
    codeVerifier?: string; // Qwen Code only (stored client-side)
  } | null>(null);
  const [isPolling, setIsPolling] = useState(false);
  const pollingRef = useRef<NodeJS.Timeout | null>(null);

  const providerConfig = provider ? PROVIDERS[provider] : null;

  // Cleanup polling on unmount or dialog close
  useEffect(() => {
    return () => {
      if (pollingRef.current) {
        clearInterval(pollingRef.current);
        pollingRef.current = null;
      }
    };
  }, []);

  // Fetch auth URL or initiate device code when entering step 2
  useEffect(() => {
    if (step === 2 && provider && providerConfig) {
      if (providerConfig.flowType === "oauth_redirect") {
        setIsFetchingUrl(true);
        setAuthUrl("");
        providerConfig.getAuthUrl()
          .then((result) => {
            if (result.success) {
              setAuthUrl(result.data.authUrl);
            } else {
              setError(result.error);
            }
          })
          .finally(() => setIsFetchingUrl(false));
      } else if (providerConfig.flowType === "device_code") {
        setIsFetchingUrl(true);
        setDeviceCodeInfo(null);

        // Qwen Code device code flow
        initiateQwenCodeAuth()
          .then((result) => {
            if (result.success) {
              setDeviceCodeInfo({
                deviceCode: result.data.deviceCode,
                verificationUrl: result.data.verificationUrlComplete,
                codeVerifier: result.data.codeVerifier,
              });
            } else {
              setError(result.error);
            }
          })
          .finally(() => setIsFetchingUrl(false));
      }
    }
  }, [step, provider, providerConfig]);

  const resetForm = useCallback(() => {
    setStep(1);
    setProvider(null);
    setCallbackUrl("");
    setError("");
    setIsLoading(false);
    setAuthUrl("");
    setIsFetchingUrl(false);
    setDeviceCodeInfo(null);
    setIsPolling(false);
    if (pollingRef.current) {
      clearInterval(pollingRef.current);
      pollingRef.current = null;
    }
  }, []);

  const handleOpenChange = (isOpen: boolean) => {
    if (!isLoading && !isPolling) {
      setOpen(isOpen);
      if (!isOpen) {
        resetForm();
      }
    }
  };

  const handleSelectProvider = (selectedProvider: Provider) => {
    setProvider(selectedProvider);
    setStep(2);
  };

  const handleStartOAuth = () => {
    if (!authUrl) return;

    const width = 600;
    const height = 700;
    const left = Math.round((window.screen.width - width) / 2);
    const top = Math.round((window.screen.height - height) / 2);

    const popup = window.open(
      authUrl,
      "oauth_popup",
      `width=${width},height=${height},left=${left},top=${top},scrollbars=yes,resizable=yes`
    );

    if (!popup || popup.closed) {
      window.open(authUrl, "_blank");
    }

    setStep(3);
  };

  const handleStartDeviceCodeAuth = () => {
    if (!deviceCodeInfo) return;

    // Open in centered popup window (same as OAuth flow)
    const width = 600;
    const height = 700;
    const left = Math.round((window.screen.width - width) / 2);
    const top = Math.round((window.screen.height - height) / 2);

    const popup = window.open(
      deviceCodeInfo.verificationUrl,
      "device_auth_popup",
      `width=${width},height=${height},left=${left},top=${top},scrollbars=yes,resizable=yes`
    );

    // Fallback to new tab if popup blocked
    if (!popup || popup.closed) {
      window.open(deviceCodeInfo.verificationUrl, "_blank");
      startPolling(null);
    } else {
      startPolling(popup);
    }
  };

  const startPolling = useCallback((popup: Window | null) => {
    if (!deviceCodeInfo || isPolling) return;

    setIsPolling(true);
    setError("");

    const poll = async () => {
      if (!deviceCodeInfo) return;

      // Check if popup was closed by user
      if (popup && popup.closed) {
        setIsPolling(false);
        setError("");
        if (pollingRef.current) {
          clearInterval(pollingRef.current);
          pollingRef.current = null;
        }
        return;
      }

      try {
        const result = await pollQwenCodeAuth(
          deviceCodeInfo.deviceCode,
          deviceCodeInfo.codeVerifier || ""
        );

        if (!result.success) {
          setError(result.error);
          setIsPolling(false);
          if (pollingRef.current) {
            clearInterval(pollingRef.current);
            pollingRef.current = null;
          }
          return;
        }

        if (result.data.status === "success") {
          // Close popup if still open
          if (popup && !popup.closed) {
            popup.close();
          }
          toast.success(
            result.data.isUpdate
              ? "Qwen Code account updated successfully!"
              : "Qwen Code account connected successfully!"
          );
          setOpen(false);
          resetForm();
          router.refresh();
          return;
        }

        if (result.data.status === "error") {
          const msg = typeof result.data.message === "string"
            ? result.data.message
            : "An error occurred";
          setError(msg);
          setIsPolling(false);
          if (pollingRef.current) {
            clearInterval(pollingRef.current);
            pollingRef.current = null;
          }
          return;
        }

        // status === "pending" - continue polling
      } catch (err) {
        console.error("Polling error:", err);
      }
    };

    // Initial poll
    poll();

    // Set up interval polling every 5 seconds
    pollingRef.current = setInterval(poll, 5000);
  }, [deviceCodeInfo, isPolling, resetForm, router]);

  const handleCopyLink = async () => {
    const urlToCopy = providerConfig?.flowType === "device_code" 
      ? deviceCodeInfo?.verificationUrl 
      : authUrl;
    
    if (urlToCopy) {
      await navigator.clipboard.writeText(urlToCopy);
      toast.success("Link copied to clipboard");
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");

    if (!provider || !providerConfig || providerConfig.flowType !== "oauth_redirect") {
      setError("Invalid provider configuration");
      return;
    }

    if (!callbackUrl.trim()) {
      setError("Please paste the callback URL");
      return;
    }

    if (!callbackUrl.includes("code=")) {
      setError("Invalid URL. Make sure the URL contains 'code=' parameter.");
      return;
    }

    setIsLoading(true);

    try {
      const result = await providerConfig.exchangeAction(callbackUrl.trim());

      if (!result.success) {
        throw new Error(result.error);
      }

      const message = result.data.isUpdate
        ? `${providerConfig.name} account updated successfully!`
        : `${providerConfig.name} account connected successfully!`;

      toast.success(message);
      setOpen(false);
      resetForm();
      router.refresh();
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to connect account";
      setError(message);
      toast.error(message);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogTrigger asChild>
        <Button className="gap-2">
          <Plus className="h-4 w-4" />
          Add Account
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Add Provider Account</DialogTitle>
          <DialogDescription>
            Connect a new AI provider account for load balancing
          </DialogDescription>
        </DialogHeader>

        {/* Step Indicator */}
        <div className="flex items-center justify-center gap-2">
          {[1, 2, 3].map((s) => (
            <div key={s} className="flex items-center">
              <div
                className={cn(
                  "flex h-8 w-8 items-center justify-center rounded-full text-sm font-medium transition-colors",
                  step > s
                    ? "bg-primary text-primary-foreground"
                    : step === s
                      ? "bg-primary text-primary-foreground"
                      : "bg-muted text-muted-foreground"
                )}
              >
                {step > s ? <Check className="h-4 w-4" /> : s}
              </div>
              {s < 3 && (
                <div
                  className={cn(
                    "h-px w-8 transition-colors",
                    step > s ? "bg-primary" : "bg-border"
                  )}
                />
              )}
            </div>
          ))}
        </div>

        {/* Step Content */}
        <div className="min-h-[200px] space-y-4">
          {/* Step 1: Select Provider */}
          {step === 1 && (
            <div className="space-y-4">
              <Label className="text-sm font-medium">Choose a provider</Label>
              <div className="grid grid-cols-3 gap-3">
                {(Object.entries(PROVIDERS) as [Exclude<Provider, null>, ProviderFullConfig][]).map(
                  ([key, config]) => (
                    <button
                      key={key}
                      type="button"
                      onClick={() => handleSelectProvider(key)}
                      className={cn(
                        "flex flex-col items-center gap-2 rounded-lg border-2 p-3 text-center transition-all hover:border-primary hover:bg-accent",
                        provider === key
                          ? "border-primary bg-accent"
                          : "border-border"
                      )}
                    >
                      <div className="text-sm font-medium">{config.name}</div>
                    </button>
                  )
                )}
              </div>
            </div>
          )}

          {/* Step 2: OAuth Login / Device Code */}
          {step === 2 && providerConfig && (
            <div className="space-y-4">
              {providerConfig.flowType === "oauth_redirect" ? (
                // OAuth Redirect Flow
                <>
                  <div className="space-y-2">
                    <Label className="text-sm font-medium">
                      Login to {providerConfig.name}
                    </Label>
                    <p className="text-sm text-muted-foreground">
                      Click the button below to open the login page in a new window.
                      After logging in, you&apos;ll be redirected to a page that shows
                      an error - this is expected.
                    </p>
                  </div>
                  <div className="flex gap-2">
                    <Button
                      onClick={handleStartOAuth}
                      variant="outline"
                      className="flex-1"
                      disabled={isFetchingUrl || !authUrl}
                    >
                      {isFetchingUrl ? (
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      ) : (
                        <ExternalLink className="mr-2 h-4 w-4" />
                      )}
                      Open {providerConfig.name} Login
                    </Button>
                    <Button
                      onClick={handleCopyLink}
                      variant="outline"
                      disabled={isFetchingUrl || !authUrl}
                      title="Copy login link"
                    >
                      <Copy className="h-4 w-4" />
                    </Button>
                  </div>
                  <Alert>
                    <AlertCircle className="h-4 w-4" />
                    <AlertDescription className="text-xs">
                      After login, copy the URL from address bar:{" "}
                      <code className="rounded bg-muted px-1">
                        {provider === "codex"
                          ? "http://localhost:1455/auth/callback?code=..."
                          : "http://localhost:1/oauth2callback?code=..."}
                      </code>
                    </AlertDescription>
                  </Alert>
                </>
              ) : (
                // Device Code Flow
                <>
                  <div className="space-y-2">
                    <Label className="text-sm font-medium">
                      Login to {providerConfig.name}
                    </Label>
                    <p className="text-sm text-muted-foreground">
                      Click the button below to open the Qwen login page. After
                      you complete the login, authorization will be detected
                      automatically.
                    </p>
                  </div>
                  <div className="flex gap-2">
                    <Button
                      onClick={handleStartDeviceCodeAuth}
                      variant="outline"
                      className="flex-1"
                      disabled={isFetchingUrl || !deviceCodeInfo || isPolling}
                    >
                      {isFetchingUrl ? (
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      ) : isPolling ? (
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      ) : (
                        <ExternalLink className="mr-2 h-4 w-4" />
                      )}
                      {isPolling ? "Waiting for login..." : `Open ${providerConfig.name} Login`}
                    </Button>
                    <Button
                      onClick={handleCopyLink}
                      variant="outline"
                      disabled={isFetchingUrl || !deviceCodeInfo}
                      title="Copy login link"
                    >
                      <Copy className="h-4 w-4" />
                    </Button>
                  </div>
                  {isPolling && (
                    <Alert>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      <AlertDescription className="text-xs">
                        Complete the login in your browser. This dialog will close
                        automatically when authorization is complete.
                      </AlertDescription>
                    </Alert>
                  )}
                  {error && (
                    <Alert variant="destructive">
                      <AlertCircle className="h-4 w-4" />
                      <AlertDescription className="text-xs">{error}</AlertDescription>
                    </Alert>
                  )}
                </>
              )}
            </div>
          )}

          {/* Step 3: Paste URL (OAuth Redirect only) */}
          {step === 3 && providerConfig && providerConfig.flowType === "oauth_redirect" && (
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="space-y-2">
                <Label className="text-sm font-medium">Paste Callback URL</Label>
                <p className="text-sm text-muted-foreground">
                  Paste the URL from your browser after the OAuth redirect.
                </p>
                <Input
                  placeholder={
                    provider === "codex"
                      ? "http://localhost:1455/auth/callback?code=..."
                      : "http://localhost:1/oauth2callback?code=..."
                  }
                  value={callbackUrl}
                  onChange={(e) => setCallbackUrl(e.target.value)}
                  disabled={isLoading}
                  autoFocus
                />
                {error && <p className="text-sm text-destructive">{error}</p>}
              </div>
              <Button type="submit" className="w-full" disabled={isLoading}>
                {isLoading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Connecting...
                  </>
                ) : (
                  <>
                    Connect {providerConfig.name} Account
                  </>
                )}
              </Button>
            </form>
          )}
        </div>

        <DialogFooter className="sm:justify-between">
          <div>
            {step > 1 && !isPolling && (
              <Button
                type="button"
                variant="ghost"
                onClick={() => setStep(step - 1)}
                disabled={isLoading}
              >
                <ArrowLeft className="mr-2 h-4 w-4" />
                Back
              </Button>
            )}
          </div>
          <div>
            {step === 2 && providerConfig?.flowType === "oauth_redirect" && (
              <Button
                type="button"
                variant="ghost"
                onClick={() => setStep(3)}
              >
                Next
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            )}
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
