// apps/dashboard/components/dashboard/api-keys/api-key-model-access.tsx
"use client";

import { useMemo, useState } from "react";
import { Check, ChevronDown, ListFilter, RotateCcw, X } from "lucide-react";
import { toast } from "sonner";
import { updateApiKeyModelAccess, type ApiKeyModelAccessMode } from "@/lib/actions/api-keys";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { cn } from "@/lib/utils";

interface ApiKeyModelAccessProps {
  apiKeyId: string;
  availableModels: string[];
  initialMode: ApiKeyModelAccessMode;
  initialModels: string[];
}

function normalizeModels(models: string[]): string[] {
  return Array.from(new Set(models)).sort((a, b) => a.localeCompare(b));
}

function sameModelList(left: string[], right: string[]): boolean {
  if (left.length !== right.length) {
    return false;
  }

  return left.every((model, index) => model === right[index]);
}

function getModeLabel(mode: ApiKeyModelAccessMode): string {
  if (mode === "all") {
    return "All models";
  }

  if (mode === "whitelist") {
    return "Whitelist";
  }

  return "Blacklist";
}

export function ApiKeyModelAccess({
  apiKeyId,
  availableModels,
  initialMode,
  initialModels,
}: ApiKeyModelAccessProps) {
  const normalizedInitialModels = useMemo(() => normalizeModels(initialModels), [initialModels]);

  const [modelPickerOpen, setModelPickerOpen] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  const [savedMode, setSavedMode] = useState<ApiKeyModelAccessMode>(initialMode);
  const [savedModels, setSavedModels] = useState<string[]>(normalizedInitialModels);

  const [draftMode, setDraftMode] = useState<ApiKeyModelAccessMode>(initialMode);
  const [draftModels, setDraftModels] = useState<string[]>(normalizedInitialModels);

  const normalizedDraftModels = useMemo(() => normalizeModels(draftModels), [draftModels]);
  const normalizedSavedModels = useMemo(() => normalizeModels(savedModels), [savedModels]);

  const modelsForSave = draftMode === "all" ? [] : normalizedDraftModels;
  const hasChanges =
    draftMode !== savedMode ||
    !sameModelList(modelsForSave, draftMode === "all" ? [] : normalizedSavedModels);

  const resetDraftState = () => {
    setDraftMode(savedMode);
    setDraftModels(normalizedSavedModels);
    setModelPickerOpen(false);
  };

  const toggleModel = (modelId: string) => {
    setDraftModels((current) => {
      if (current.includes(modelId)) {
        return current.filter((model) => model !== modelId);
      }
      return [...current, modelId];
    });
  };

  const handleSave = async () => {
    if (draftMode !== "all" && modelsForSave.length === 0) {
      toast.error("Select at least one model");
      return;
    }

    setIsSaving(true);
    try {
      const result = await updateApiKeyModelAccess(apiKeyId, draftMode, modelsForSave);
      if (!result.success) {
        throw new Error(result.error);
      }

      const nextModels = normalizeModels(result.data.models);
      setSavedMode(result.data.mode);
      setSavedModels(nextModels);
      setDraftMode(result.data.mode);
      setDraftModels(nextModels);
      setModelPickerOpen(false);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to update model access");
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <section className="flex h-full flex-col rounded-xl border border-border/70 bg-muted/20 p-4 lg:border lg:border-border/70 lg:bg-muted/20 max-lg:border-0 max-lg:bg-transparent max-lg:p-0">
      <div className="hidden items-start justify-between gap-3 lg:flex">
        <div className="inline-flex items-center gap-2 text-sm font-semibold">
          <ListFilter className="h-4 w-4 text-muted-foreground" />
          <span>Model Access</span>
        </div>
        <Badge variant="outline" className="shrink-0">
          {getModeLabel(savedMode)}
        </Badge>
      </div>

      <div className="grid grid-cols-2 gap-2 text-xs lg:mt-4">
        <div className="rounded-lg border border-border/60 bg-background/80 px-3 py-2">
          <p className="text-[11px] text-muted-foreground">Mode</p>
          <p className="mt-1 font-medium">{getModeLabel(savedMode)}</p>
        </div>
        <div className="rounded-lg border border-border/60 bg-background/80 px-3 py-2">
          <p className="text-[11px] text-muted-foreground">Selected</p>
          <p className="mt-1 font-medium">
            {savedMode === "all" ? "All models" : `${normalizedSavedModels.length} model`}
            {savedMode !== "all" && normalizedSavedModels.length !== 1 ? "s" : ""}
          </p>
        </div>
      </div>

      <div className="space-y-3 flex-1 lg:mt-4">
        <div className="space-y-1.5">
          <p className="text-xs font-medium">Mode</p>
          <ToggleGroup
            type="single"
            variant="outline"
            size="sm"
            value={draftMode}
            onValueChange={(value) => {
              if (value === "all" || value === "whitelist" || value === "blacklist") {
                setDraftMode(value);
              }
            }}
            className="w-full justify-start"
          >
            <ToggleGroupItem value="all" className="flex-1">All</ToggleGroupItem>
            <ToggleGroupItem value="whitelist" className="flex-1">Whitelist</ToggleGroupItem>
            <ToggleGroupItem value="blacklist" className="flex-1">Blacklist</ToggleGroupItem>
          </ToggleGroup>
        </div>

        {draftMode !== "all" && (
          <div className="space-y-2">
            <div className="flex items-center justify-between gap-2">
              <p className="text-xs font-medium">Models</p>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="h-7 px-2 text-[11px]"
                onClick={() => setDraftModels([])}
                disabled={normalizedDraftModels.length === 0 || isSaving}
              >
                Clear
              </Button>
            </div>

            <Popover open={modelPickerOpen} onOpenChange={setModelPickerOpen}>
              <PopoverTrigger asChild>
                <Button
                  variant="outline"
                  className="h-9 w-full justify-between px-3 text-xs"
                  disabled={isSaving}
                >
                  <span className="truncate">
                    {normalizedDraftModels.length > 0
                      ? `${normalizedDraftModels.length} model selected`
                      : "Select models"}
                  </span>
                  <ChevronDown className="h-3.5 w-3.5 text-muted-foreground" />
                </Button>
              </PopoverTrigger>
              <PopoverContent align="start" className="w-[min(90vw,28rem)] p-0">
                <Command>
                  <CommandInput placeholder="Search model..." />
                  <CommandList>
                    <CommandEmpty>No model found.</CommandEmpty>
                    <CommandGroup>
                      {availableModels.map((modelId) => {
                        const selected = normalizedDraftModels.includes(modelId);
                        return (
                          <CommandItem
                            key={modelId}
                            value={modelId}
                            onSelect={() => toggleModel(modelId)}
                            className="gap-2"
                          >
                            <Check
                              className={cn(
                                "h-3.5 w-3.5",
                                selected ? "opacity-100" : "opacity-0"
                              )}
                            />
                            <span className="truncate font-mono text-[11px]">{modelId}</span>
                          </CommandItem>
                        );
                      })}
                    </CommandGroup>
                  </CommandList>
                </Command>
              </PopoverContent>
            </Popover>

            <div className="max-h-40 overflow-y-auto rounded-lg border border-border/60 bg-background/80 p-2">
              {normalizedDraftModels.length === 0 ? (
                <p className="px-1 text-[11px] text-muted-foreground">No models selected</p>
              ) : (
                <div className="flex flex-wrap gap-1.5">
                  {normalizedDraftModels.map((modelId) => (
                    <Badge
                      key={modelId}
                      variant="secondary"
                      className="max-w-full gap-1 pr-1 font-normal text-[10px]"
                    >
                      <span className="min-w-0 truncate font-mono">{modelId}</span>
                      <button
                        type="button"
                        className="inline-flex h-4 w-4 items-center justify-center rounded-sm text-muted-foreground hover:text-foreground"
                        onClick={() => toggleModel(modelId)}
                        aria-label={`Remove ${modelId}`}
                      >
                        <X className="h-2.5 w-2.5" />
                      </button>
                    </Badge>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}
      </div>

      <div className="flex items-center justify-end gap-2 border-t border-border/60 pt-3 lg:mt-4">
        <Button
          variant="outline"
          size="sm"
          onClick={resetDraftState}
          disabled={isSaving || !hasChanges}
        >
          <RotateCcw className="h-3.5 w-3.5" />
          Reset
        </Button>
        <Button size="sm" onClick={handleSave} disabled={isSaving || !hasChanges}>
          {isSaving ? "Saving..." : "Save"}
        </Button>
      </div>
    </section>
  );
}

// apps/web/app/components/api-key/ApiKeyModelAccess.vue
<script setup lang="ts">
import { compareModelIds } from "~~/lib/model-sort";

type AccessMode = "all" | "whitelist" | "blacklist";

const props = defineProps<{
  apiKeyId: string;
  availableModels: string[];
  initialMode: AccessMode;
  initialModels: string[];
  readonly?: boolean;
}>();

const emit = defineEmits<{
  updated: [value: { mode: AccessMode; models: string[] }];
}>();

const api = useApi();
const modelPickerOpen = ref(false);
const modelSearch = ref("");
const isSaving = ref(false);
const savedMode = ref<AccessMode>(props.initialMode);
const savedModels = ref<string[]>(normalizeModels(props.initialModels));
const draftMode = ref<AccessMode>(props.initialMode);
const draftModels = ref<string[]>(normalizeModels(props.initialModels));
const errorMessage = ref("");

function normalizeModels(models: string[]): string[] {
  return Array.from(new Set(models)).sort(compareModelIds);
}

function sameList(left: string[], right: string[]): boolean {
  return left.length === right.length && left.every((item, index) => item === right[index]);
}

function setDraftMode(value: AccessMode) {
  if (props.readonly) return;
  draftMode.value = value;
}

function toggleModel(modelId: string) {
  if (props.readonly) return;
  draftModels.value = draftModels.value.includes(modelId)
    ? draftModels.value.filter((model) => model !== modelId)
    : normalizeModels([...draftModels.value, modelId]);
}

function resetDraftState() {
  draftMode.value = savedMode.value;
  draftModels.value = [...savedModels.value];
  modelPickerOpen.value = false;
  modelSearch.value = "";
  errorMessage.value = "";
}

async function save() {
  if (props.readonly) return;
  const modelsForSave = draftMode.value === "all" ? [] : normalizedDraftModels.value;
  if (draftMode.value !== "all" && modelsForSave.length === 0) {
    errorMessage.value = "Select at least one model";
    return;
  }

  isSaving.value = true;
  errorMessage.value = "";
  try {
    const result = await api.apiKeys.updateModelAccess({ id: props.apiKeyId, mode: draftMode.value, models: modelsForSave });
    if (!result.success) throw new Error(result.error);
    savedMode.value = result.data.mode;
    savedModels.value = normalizeModels(result.data.models);
    draftMode.value = result.data.mode;
    draftModels.value = [...savedModels.value];
    modelPickerOpen.value = false;
    emit("updated", { mode: result.data.mode, models: savedModels.value });
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : "Failed to update model access";
  } finally {
    isSaving.value = false;
  }
}

const normalizedDraftModels = computed(() => normalizeModels(draftModels.value));
const normalizedSavedModels = computed(() => normalizeModels(savedModels.value));
const hasChanges = computed(() => draftMode.value !== savedMode.value || !sameList(draftMode.value === "all" ? [] : normalizedDraftModels.value, savedMode.value === "all" ? [] : normalizedSavedModels.value));
const filteredModels = computed(() => {
  const query = modelSearch.value.trim().toLowerCase();
  if (!query) return props.availableModels;
  return props.availableModels.filter((model) => model.toLowerCase().includes(query));
});
</script>

<template>
  <section class="flex h-full flex-col">
    <div class="flex-1 space-y-3">
      <div class="grid grid-cols-3 gap-1 rounded-md border border-border/70 bg-card/30 p-1">
        <button v-for="mode in ['all', 'whitelist', 'blacklist']" :key="mode" type="button" :disabled="readonly" :class="['h-8 rounded-sm border px-2 text-xs font-medium disabled:cursor-default disabled:pointer-events-none disabled:opacity-60', draftMode === mode ? 'border-primary/35 bg-primary/10 text-primary' : 'border-transparent text-muted-foreground']" @click="setDraftMode(mode as AccessMode)">
          {{ mode === 'all' ? 'All' : mode === 'whitelist' ? 'Whitelist' : 'Blacklist' }}
        </button>
      </div>

      <div v-if="draftMode !== 'all'" class="space-y-2">
        <div class="flex items-center justify-between gap-2">
          <p class="text-xs font-medium">Models</p>
          <UiButton type="button" variant="ghost" size="sm" class="h-7 px-2 text-[11px]" :disabled="normalizedDraftModels.length === 0 || isSaving || readonly" @click="draftModels = []">Clear</UiButton>
        </div>

        <UiPopover v-model:open="modelPickerOpen" :content="{ align: 'start', class: 'w-[min(90vw,28rem)] p-0' }">
          <UiButton variant="outline" class="h-9 w-full justify-between px-3 text-xs" :disabled="isSaving || readonly">
            <span class="truncate">{{ normalizedDraftModels.length > 0 ? `${normalizedDraftModels.length} model selected` : 'Select models' }}</span>
            <UiIcon name="i-lucide-chevron-down" class="size-3.5 text-muted-foreground" />
          </UiButton>
          <template #content>
            <div class="border-b border-border p-2">
              <input v-model="modelSearch" placeholder="Search model..." class="h-8 w-full rounded-md bg-background px-2 text-xs outline-none focus-visible:ring-2 focus-visible:ring-ring">
            </div>
            <div class="max-h-72 overflow-y-auto p-1">
              <button v-for="modelId in filteredModels" :key="modelId" type="button" :disabled="readonly" class="flex w-full items-center gap-2 rounded-sm px-2 py-1.5 text-left hover:bg-accent disabled:cursor-default disabled:pointer-events-none disabled:opacity-60" @click="toggleModel(modelId)">
                <UiIcon name="i-lucide-check" :class="['size-3.5', normalizedDraftModels.includes(modelId) ? 'opacity-100' : 'opacity-0']" />
                <span class="truncate font-mono text-[11px]">{{ modelId }}</span>
              </button>
              <p v-if="filteredModels.length === 0" class="px-2 py-6 text-center text-xs text-muted-foreground">No model found.</p>
            </div>
          </template>
        </UiPopover>

        <div class="max-h-40 overflow-y-auto py-1">
          <p v-if="normalizedDraftModels.length === 0" class="px-1 text-[11px] text-muted-foreground">No models selected</p>
          <div v-else class="flex flex-wrap gap-1.5">
            <UiBadge v-for="modelId in normalizedDraftModels" :key="modelId" variant="outline" class="max-w-full gap-1 pr-1 text-[10px] font-normal">
              <span class="min-w-0 truncate font-mono">{{ modelId }}</span>
              <UiTooltip text="Remove" :disabled="readonly">
                <button type="button" :disabled="readonly" :aria-label="`Remove model ${modelId}`" class="inline-flex size-4 items-center justify-center rounded-sm text-muted-foreground hover:text-foreground disabled:cursor-default disabled:pointer-events-none disabled:opacity-60" @click="toggleModel(modelId)">
                  <UiIcon name="i-lucide-x" class="size-2.5" />
                </button>
              </UiTooltip>
            </UiBadge>
          </div>
        </div>
      </div>
      <p v-if="errorMessage" class="text-xs text-destructive">{{ errorMessage }}</p>
    </div>

    <div class="flex items-center justify-end gap-2 border-t border-border/60 pt-3 lg:mt-4">
      <UiButton variant="outline" size="sm" :disabled="isSaving || !hasChanges || readonly" @click="resetDraftState">Cancel</UiButton>
      <UiButton size="sm" :disabled="isSaving || !hasChanges || readonly" @click="save">{{ isSaving ? 'Saving...' : 'Save' }}</UiButton>
    </div>
  </section>
</template>
