// apps/dashboard/components/dashboard/api-keys/editable-api-key-name.tsx
"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Pencil } from "lucide-react";
import { toast } from "sonner";
import { updateApiKeyName } from "@/lib/actions/api-keys";

interface EditableApiKeyNameProps {
  id: string;
  name: string | null;
  showTitle?: boolean;
  showEditButton?: boolean;
}

export function EditableApiKeyName({
  id,
  name,
  showTitle = true,
  showEditButton = true,
}: EditableApiKeyNameProps) {
  const [editDialogOpen, setEditDialogOpen] = useState(false);
  const [newName, setNewName] = useState(name ?? "");
  const [isUpdating, setIsUpdating] = useState(false);

  const handleUpdateName = async () => {
    setIsUpdating(true);
    try {
      const result = await updateApiKeyName(id, newName);

      if (!result.success) {
        throw new Error(result.error);
      }

      setEditDialogOpen(false);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to update API key name");
    } finally {
      setIsUpdating(false);
    }
  };

  return (
    <Dialog
      open={editDialogOpen}
      onOpenChange={(open) => {
        setEditDialogOpen(open);
        if (open) setNewName(name ?? "");
      }}
    >
      <div className="flex min-w-0 items-center gap-1.5">
        {showTitle && (
          <span className="min-w-0 truncate text-lg font-semibold">{name ?? "Unnamed key"}</span>
        )}
        {showEditButton && (
          <DialogTrigger asChild>
            <Button
              variant="outline"
              size="icon"
              className="h-9 w-9 text-muted-foreground"
              title="Edit name"
              aria-label="Edit name"
            >
              <Pencil className="h-4 w-4" />
            </Button>
          </DialogTrigger>
        )}
      </div>
      <DialogContent className="sm:max-w-[400px]">
        <DialogHeader>
          <DialogTitle>Edit API Key Name</DialogTitle>
          <DialogDescription className="sr-only">
            Change the name of your API key.
          </DialogDescription>
        </DialogHeader>
        <div className="py-3">
          <Label htmlFor="apiKeyName">Name</Label>
          <Input
            id="apiKeyName"
            value={newName}
            onChange={(e) => setNewName(e.target.value)}
            placeholder="My API Key"
            className="mt-1.5"
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                e.preventDefault();
                handleUpdateName();
              }
            }}
          />
        </div>
        <DialogFooter>
          <Button variant="outline" size="sm" onClick={() => setEditDialogOpen(false)}>
            Cancel
          </Button>
          <Button
            size="sm"
            onClick={handleUpdateName}
            disabled={isUpdating}
          >
            {isUpdating ? "Saving..." : "Save"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// apps/web/app/components/api-key/EditableApiKeyName.vue
<script setup lang="ts">
import type { MeData } from "~~/lib/api-types";

const props = withDefaults(
  defineProps<{
    id: string;
    name: string | null;
    keyPreview?: string;
    showTitle?: boolean;
    showEditButton?: boolean;
    readonly?: boolean;
  }>(),
  {
    showTitle: true,
    showEditButton: true,
    keyPreview: "",
  }
);

const emit = defineEmits<{
  updated: [value: { name: string | null; keyPreview?: string }];
}>();

const api = useApi();
const { data: me } = useNuxtData<MeData>(dataKeys.me);
const API_KEY_MIN_LENGTH = 3;
const API_KEY_MAX_LENGTH = 100;
const API_KEY_UPDATE_POINT_COST = 20;
const API_KEY_ALLOWED_PATTERN = /^[A-Za-z0-9_-]+$/;
const editDialogOpen = ref(false);
const newName = ref(props.name ?? "");
const apiKeyValue = ref("");
const revealedApiKey = ref<string | null>(null);
const isApiKeyDirty = ref(false);
const isUpdating = ref(false);
const isRevealingApiKey = ref(false);
const errorMessage = ref("");
const maskedApiKey = computed(() => props.keyPreview || "********");
const normalizedApiKeyValue = computed(() => apiKeyValue.value.trim());
const saveCostsPoints = computed(() => isApiKeyDirty.value && normalizedApiKeyValue.value !== revealedApiKey.value);
const pointBalance = computed(() => me.value?.points?.balance ?? 0);
const formattedApiKeyUpdatePointCost = computed(() => API_KEY_UPDATE_POINT_COST.toLocaleString("en-US"));
const hasInsufficientPoints = computed(() => saveCostsPoints.value && pointBalance.value < API_KEY_UPDATE_POINT_COST);
const apiKeyValidationError = computed(() => {
  if (!saveCostsPoints.value) return "";
  if (normalizedApiKeyValue.value.length < API_KEY_MIN_LENGTH) return `API key must be at least ${API_KEY_MIN_LENGTH} characters`;
  if (normalizedApiKeyValue.value.length > API_KEY_MAX_LENGTH) return `API key must be at most ${API_KEY_MAX_LENGTH} characters`;
  if (!API_KEY_ALLOWED_PATTERN.test(normalizedApiKeyValue.value)) return "API key can only contain letters, numbers, hyphen, and underscore";
  return "";
});

watch(editDialogOpen, (open) => {
  if (open) {
    newName.value = props.name ?? "";
    apiKeyValue.value = maskedApiKey.value;
    revealedApiKey.value = null;
    isApiKeyDirty.value = false;
    errorMessage.value = "";
  }
});

async function revealApiKeyForEdit() {
  if (props.readonly || revealedApiKey.value || isRevealingApiKey.value) return;
  isRevealingApiKey.value = true;
  errorMessage.value = "";
  try {
    const result = await api.apiKeys.reveal({ id: props.id });
    if (!result.success) throw new Error(result.error);
    revealedApiKey.value = result.data.key;
    apiKeyValue.value = result.data.key;
    isApiKeyDirty.value = false;
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : "Failed to reveal API key";
  } finally {
    isRevealingApiKey.value = false;
  }
}

function markApiKeyDirty() {
  if (!revealedApiKey.value) return;
  isApiKeyDirty.value = true;
}

async function updateName() {
  if (props.readonly) return;
  if (apiKeyValidationError.value) return;
  if (hasInsufficientPoints.value) return;
  isUpdating.value = true;
  errorMessage.value = "";
  try {
    const result = await api.apiKeys.updateName({ id: props.id, name: newName.value, ...(saveCostsPoints.value ? { key: normalizedApiKeyValue.value } : {}) });
    if (!result.success) throw new Error(result.error);
    editDialogOpen.value = false;
    if (saveCostsPoints.value) void refreshNuxtData(dataKeys.me);
    emit("updated", { name: result.data.name, keyPreview: result.data.keyPreview });
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : "Failed to update API key";
  } finally {
    isUpdating.value = false;
  }
}
</script>

<template>
  <div class="flex min-w-0 items-center gap-1.5">
    <span v-if="showTitle" class="min-w-0 truncate text-lg font-semibold">{{ name ?? '' }}</span>
    <UiTooltip v-if="showEditButton" text="Edit" :disabled="readonly">
      <UiButton variant="outline" size="icon-sm" class="h-8 w-8" :disabled="readonly" @click="editDialogOpen = true">
        <UiIcon name="i-lucide-pencil" class="size-4" />
      </UiButton>
    </UiTooltip>
  </div>

  <UiDialog v-model:open="editDialogOpen" :ui="{ content: 'sm:max-w-md' }">
    <template #content>
      <div v-if="errorMessage" class="rounded-lg border border-destructive/50 bg-destructive/10 px-3 py-2 text-sm text-destructive">
        {{ errorMessage }}
      </div>
      <label class="grid gap-1 text-sm font-medium"><span>Name <span class="text-destructive">*</span></span><input v-model="newName" class="h-9 rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50" placeholder="My API Key" @keydown.enter.prevent="updateName"></label>
      <label class="grid gap-1 text-sm font-medium">
        <span>API Key</span>
        <div class="relative">
          <input
            v-model="apiKeyValue"
            :class="[
              'h-9 w-full rounded-md border bg-background px-3 pr-9 font-mono text-sm outline-none focus-visible:ring-[3px]',
              apiKeyValidationError ? 'border-destructive focus-visible:border-destructive focus-visible:ring-destructive/20' : 'border-input focus-visible:border-ring focus-visible:ring-ring/50',
            ]"
            :readonly="!revealedApiKey || isRevealingApiKey"
            @focus="revealApiKeyForEdit"
            @click="revealApiKeyForEdit"
            @input="markApiKeyDirty"
            @keydown.enter.prevent="updateName"
          >
          <UiIcon v-if="isRevealingApiKey" name="i-lucide-loader-2" class="absolute right-3 top-1/2 size-4 -translate-y-1/2 animate-spin text-muted-foreground" />
        </div>
        <span v-if="apiKeyValidationError" class="text-xs font-normal text-destructive">{{ apiKeyValidationError }}</span>
        <span v-else-if="hasInsufficientPoints" class="text-xs font-normal text-destructive">Not enough points.</span>
      </label>
      <div class="flex justify-end gap-2">
        <UiButton variant="outline" @click="editDialogOpen = false">Cancel</UiButton>
        <UiButton class="w-24 transition-colors" :disabled="isUpdating || isRevealingApiKey || Boolean(apiKeyValidationError) || hasInsufficientPoints" @click="updateName">
          <template v-if="isUpdating">Saving...</template>
          <template v-else-if="saveCostsPoints">
            <PointCoinIcon reverse class="size-5 shrink-0 text-foreground/85 drop-shadow-[0_0_0.35rem_rgba(255,255,255,0.18)]" />
            {{ formattedApiKeyUpdatePointCost }}
          </template>
          <template v-else>Save</template>
        </UiButton>
      </div>
    </template>
  </UiDialog>
</template>
