// apps/dashboard/app/components/MaintenerAuditDialog.vue
<script setup lang="ts">
import type { MaintenerAuditSearchUser, MaintenerAuditUser } from "../../lib/dashboard-api-types";

const open = defineModel<boolean>("open", { default: false });

const emit = defineEmits<{
  selected: [user: MaintenerAuditUser];
}>();

const dashboardApi = useDashboardApi();
const PAGE_SIZE = 12;
const SCROLL_LOAD_THRESHOLD = 48;

const query = ref("");
const users = ref<MaintenerAuditSearchUser[]>([]);
const isSearching = ref(false);
const isLoadingMore = ref(false);
const hasMore = ref(false);
const nextOffset = ref(0);
const selectingUserId = ref<string | null>(null);
const errorMessage = ref("");
let searchRequestId = 0;
let searchTimer: ReturnType<typeof setTimeout> | null = null;

function userInitial(user: MaintenerAuditSearchUser) {
  return (user.name?.[0] || user.email?.[0] || "U").toUpperCase();
}

function canLoadQuery(value: string) {
  return value.length === 0 || value.length >= 2;
}

function clearSearchTimer() {
  if (!searchTimer) return;
  clearTimeout(searchTimer);
  searchTimer = null;
}

function resetUsers() {
  users.value = [];
  hasMore.value = false;
  nextOffset.value = 0;
}

async function loadUsers(requestId: number, append = false) {
  const normalizedQuery = query.value.trim();
  if (!canLoadQuery(normalizedQuery)) {
    resetUsers();
    isSearching.value = false;
    isLoadingMore.value = false;
    return;
  }

  if (append) {
    if (isLoadingMore.value || isSearching.value || !hasMore.value) return;
    isLoadingMore.value = true;
  } else {
    resetUsers();
    isSearching.value = true;
  }

  errorMessage.value = "";

  try {
    const result = await dashboardApi.maintener.users.search({
      q: normalizedQuery || undefined,
      offset: append ? nextOffset.value : 0,
      limit: PAGE_SIZE,
    });
    if (requestId !== searchRequestId) return;

    users.value = append ? [...users.value, ...result.users] : result.users;
    hasMore.value = result.hasMore;
    nextOffset.value = result.nextOffset;
  } catch (error) {
    if (requestId !== searchRequestId) return;
    errorMessage.value = error instanceof Error ? error.message : "Failed to load users";
    if (!append) resetUsers();
  } finally {
    if (requestId === searchRequestId) {
      isSearching.value = false;
      isLoadingMore.value = false;
    }
  }
}

function handleUsersScroll(event: Event) {
  const target = event.currentTarget as HTMLElement;
  const distanceFromBottom = target.scrollHeight - target.scrollTop - target.clientHeight;
  if (distanceFromBottom > SCROLL_LOAD_THRESHOLD) return;
  void loadUsers(searchRequestId, true);
}

watch(open, (value) => {
  clearSearchTimer();

  if (value) {
    const requestId = ++searchRequestId;
    query.value = "";
    void loadUsers(requestId);
    return;
  }

  searchRequestId++;
  query.value = "";
  resetUsers();
  errorMessage.value = "";
  selectingUserId.value = null;
  isSearching.value = false;
  isLoadingMore.value = false;
});

watch(query, (value) => {
  if (!open.value) return;

  const normalizedQuery = value.trim();
  const requestId = ++searchRequestId;
  clearSearchTimer();

  errorMessage.value = "";
  if (!canLoadQuery(normalizedQuery)) {
    resetUsers();
    isSearching.value = false;
    isLoadingMore.value = false;
    return;
  }

  resetUsers();
  isSearching.value = true;
  isLoadingMore.value = false;
  searchTimer = setTimeout(() => {
    if (requestId !== searchRequestId) return;
    void loadUsers(requestId);
  }, 250);
});

onBeforeUnmount(() => {
  clearSearchTimer();
});

async function selectUser(user: MaintenerAuditSearchUser) {
  selectingUserId.value = user.id;
  errorMessage.value = "";

  try {
    const result = await dashboardApi.maintener.audit.start({ userId: user.id });
    if (!result.success) throw new Error(result.error);
    open.value = false;
    emit("selected", result.data.user);
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : "Failed to start audit mode";
  } finally {
    selectingUserId.value = null;
  }
}
</script>

<template>
  <UiDialog v-model:open="open" :ui="{ content: 'sm:max-w-lg' }">
    <template #content>
      <div class="space-y-1.5 pr-6">
        <h2 class="text-lg font-semibold leading-none tracking-tight">Auditing</h2>
        <p class="text-sm text-muted-foreground sm:hidden">Search account for audit mode.</p>
        <p class="hidden text-sm text-muted-foreground sm:block">Search an account to view it in read-only audit mode.</p>
      </div>

      <label class="grid gap-1.5 text-sm font-medium">
        User
        <div class="relative">
          <UiIcon name="i-lucide-search" class="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
          <input
            v-model="query"
            class="h-10 w-full rounded-md border border-input bg-background pl-9 pr-3 text-sm outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50"
            placeholder="Search name or email"
            autocomplete="off"
          >
        </div>
      </label>

      <p v-if="errorMessage" class="text-sm text-destructive">{{ errorMessage }}</p>

      <div class="h-72 overflow-y-auto rounded-md border border-border bg-muted/10 p-1" @scroll="handleUsersScroll">
        <p v-if="query.trim().length > 0 && query.trim().length < 2" class="px-3 py-6 text-center text-sm text-muted-foreground">Type at least 2 characters.</p>
        <p v-else-if="isSearching && users.length === 0" class="px-3 py-6 text-center text-sm text-muted-foreground">Loading users...</p>
        <p v-else-if="users.length === 0" class="px-3 py-6 text-center text-sm text-muted-foreground">No users found.</p>
        <template v-else>
          <button
            v-for="user in users"
            :key="user.id"
            type="button"
            class="flex w-full cursor-pointer items-center gap-3 rounded-sm px-2 py-2 text-left transition-colors hover:bg-accent hover:text-accent-foreground disabled:cursor-default disabled:pointer-events-none disabled:opacity-50"
            :disabled="Boolean(selectingUserId)"
            @click="selectUser(user)"
          >
            <span class="relative flex size-9 shrink-0 select-none">
              <span class="flex size-9 overflow-hidden rounded-full">
                <img v-if="user.image" :src="user.image" alt="" class="aspect-square size-full">
                <span v-else class="flex size-full items-center justify-center rounded-full bg-muted text-sm text-muted-foreground">
                  {{ userInitial(user) }}
                </span>
              </span>
              <span v-if="user.hasProviderIssue" class="absolute bottom-0 left-0 z-10 flex h-2.5 w-2.5 shrink-0" aria-hidden="true">
                <span class="absolute inset-0 inline-flex h-full w-full animate-ping rounded-full bg-red-500 opacity-75" />
                <span class="relative inline-flex h-2.5 w-2.5 rounded-full bg-red-500" />
              </span>
            </span>
            <span class="min-w-0 flex-1">
              <span class="block truncate text-sm font-medium">{{ user.name || user.email || 'Unnamed user' }}</span>
              <span class="block truncate text-xs text-muted-foreground">{{ user.email }}</span>
            </span>
            <UiIcon v-if="selectingUserId === user.id" name="i-lucide-loader-circle" class="size-4 animate-spin text-muted-foreground" />
          </button>
          <p v-if="isLoadingMore" class="px-3 py-3 text-center text-sm text-muted-foreground">Loading more...</p>
        </template>
      </div>
    </template>
  </UiDialog>
</template>

// apps/web/src/components/MaintenerAuditDialog.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import type { MaintenerAuditSearchUser, MaintenerAuditUser } from "../lib/dashboard-api-types";
import { useDashboardApi } from "../hooks/useDashboardApi";
import { UiDialog } from "./ui/UiDialog";
import { UiIcon } from "./ui/UiIcon";

const PAGE_SIZE = 12;
const SCROLL_LOAD_THRESHOLD = 48;

function userInitial(user: MaintenerAuditSearchUser) {
  return (user.name?.[0] || user.email?.[0] || "U").toUpperCase();
}

function canLoadQuery(value: string) {
  return value.length === 0 || value.length >= 2;
}

export interface MaintenerAuditDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSelected: (user: MaintenerAuditUser) => void;
}

export function MaintenerAuditDialog({ open, onOpenChange, onSelected }: MaintenerAuditDialogProps) {
  const dashboardApi = useDashboardApi();
  const [query, setQuery] = useState("");
  const [users, setUsers] = useState<MaintenerAuditSearchUser[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [isLoadingMore, setIsLoadingMore] = useState(false);
  const [hasMore, setHasMore] = useState(false);
  const [nextOffset, setNextOffset] = useState(0);
  const [selectingUserId, setSelectingUserId] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState("");
  const searchRequestId = useRef(0);
  const searchTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const resetUsers = useCallback(() => {
    setUsers([]);
    setHasMore(false);
    setNextOffset(0);
  }, []);

  const loadUsers = useCallback(async (requestId: number, append = false) => {
    const normalizedQuery = query.trim();
    if (!canLoadQuery(normalizedQuery)) {
      resetUsers();
      setIsSearching(false);
      setIsLoadingMore(false);
      return;
    }
    if (append) {
      if (isLoadingMore || isSearching || !hasMore) return;
      setIsLoadingMore(true);
    } else {
      resetUsers();
      setIsSearching(true);
    }
    setErrorMessage("");

    try {
      const result = await dashboardApi.maintener.users.search({
        q: normalizedQuery || undefined,
        offset: append ? nextOffset : 0,
        limit: PAGE_SIZE,
      });
      if (requestId !== searchRequestId.current) return;
      setUsers((current) => (append ? [...current, ...result.users] : result.users));
      setHasMore(result.hasMore);
      setNextOffset(result.nextOffset);
    } catch (error) {
      if (requestId !== searchRequestId.current) return;
      setErrorMessage(error instanceof Error ? error.message : "Failed to load users");
      if (!append) resetUsers();
    } finally {
      if (requestId === searchRequestId.current) {
        setIsSearching(false);
        setIsLoadingMore(false);
      }
    }
  }, [query, isLoadingMore, isSearching, hasMore, nextOffset, dashboardApi, resetUsers]);

  useEffect(() => {
    if (!open) return;
    const requestId = ++searchRequestId.current;
    setQuery("");
    void loadUsers(requestId);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  useEffect(() => {
    if (!open) return;
    const requestId = ++searchRequestId.current;
    setErrorMessage("");
    if (!canLoadQuery(query.trim())) {
      resetUsers();
      setIsSearching(false);
      setIsLoadingMore(false);
      return;
    }
    resetUsers();
    setIsSearching(true);
    setIsLoadingMore(false);
    if (searchTimer.current) clearTimeout(searchTimer.current);
    searchTimer.current = setTimeout(() => {
      if (requestId !== searchRequestId.current) return;
      void loadUsers(requestId);
    }, 250);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [query, open]);

  useEffect(() => {
    return () => {
      if (searchTimer.current) clearTimeout(searchTimer.current);
    };
  }, []);

  const selectUser = async (user: MaintenerAuditSearchUser) => {
    setSelectingUserId(user.id);
    setErrorMessage("");
    try {
      const result = await dashboardApi.maintener.audit.start({ userId: user.id });
      if (!result.success) throw new Error(result.error);
      onOpenChange(false);
      onSelected(result.data.user);
    } catch (error) {
      setErrorMessage(error instanceof Error ? error.message : "Failed to start audit mode");
    } finally {
      setSelectingUserId(null);
    }
  };

  const handleUsersScroll = (event: React.UIEvent<HTMLDivElement>) => {
    const target = event.currentTarget;
    const distanceFromBottom = target.scrollHeight - target.scrollTop - target.clientHeight;
    if (distanceFromBottom > SCROLL_LOAD_THRESHOLD) return;
    void loadUsers(searchRequestId.current, true);
  };

  return (
    <UiDialog open={open} onOpenChange={onOpenChange} ui={{ content: "sm:max-w-lg" }}>
      <div className="space-y-1.5 pr-6">
        <h2 className="text-lg font-semibold leading-none tracking-tight">Auditing</h2>
        <p className="text-sm text-muted-foreground sm:hidden">Search account for audit mode.</p>
        <p className="hidden text-sm text-muted-foreground sm:block">Search an account to view it in read-only audit mode.</p>
      </div>

      <label className="grid gap-1.5 text-sm font-medium">
        User
        <div className="relative">
          <UiIcon name="i-lucide-search" className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
          <input
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            className="h-10 w-full rounded-md border border-input bg-background pl-9 pr-3 text-sm outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50"
            placeholder="Search name or email"
            autoComplete="off"
          />
        </div>
      </label>

      {errorMessage ? <p className="text-sm text-destructive">{errorMessage}</p> : null}

      <div className="h-72 overflow-y-auto rounded-md border border-border bg-muted/10 p-1" onScroll={handleUsersScroll}>
        {query.trim().length > 0 && query.trim().length < 2 ? (
          <p className="px-3 py-6 text-center text-sm text-muted-foreground">Type at least 2 characters.</p>
        ) : isSearching && users.length === 0 ? (
          <p className="px-3 py-6 text-center text-sm text-muted-foreground">Loading users...</p>
        ) : users.length === 0 ? (
          <p className="px-3 py-6 text-center text-sm text-muted-foreground">No users found.</p>
        ) : (
          <>
            {users.map((user) => (
              <button
                key={user.id}
                type="button"
                disabled={Boolean(selectingUserId)}
                className="flex w-full cursor-pointer items-center gap-3 rounded-sm px-2 py-2 text-left transition-colors hover:bg-accent hover:text-accent-foreground disabled:cursor-default disabled:pointer-events-none disabled:opacity-50"
                onClick={() => void selectUser(user)}
              >
                <span className="relative flex size-9 shrink-0 select-none">
                  <span className="flex size-9 overflow-hidden rounded-full">
                    {user.image ? <img src={user.image} alt="" className="aspect-square size-full" /> : <span className="flex size-full items-center justify-center rounded-full bg-muted text-sm text-muted-foreground">{userInitial(user)}</span>}
                  </span>
                  {user.hasProviderIssue ? (
                    <span className="absolute bottom-0 left-0 z-10 flex h-2.5 w-2.5 shrink-0" aria-hidden="true">
                      <span className="absolute inset-0 inline-flex h-full w-full animate-ping rounded-full bg-red-500 opacity-75" />
                      <span className="relative inline-flex h-2.5 w-2.5 rounded-full bg-red-500" />
                    </span>
                  ) : null}
                </span>
                <span className="min-w-0 flex-1">
                  <span className="block truncate text-sm font-medium">{user.name || user.email || "Unnamed user"}</span>
                  <span className="block truncate text-xs text-muted-foreground">{user.email}</span>
                </span>
                {selectingUserId === user.id ? <UiIcon name="i-lucide-loader-circle" className="size-4 shrink-0 animate-spin text-muted-foreground" /> : null}
              </button>
            ))}
            {isLoadingMore ? <p className="px-3 py-3 text-center text-sm text-muted-foreground">Loading more...</p> : null}
          </>
        )}
      </div>
    </UiDialog>
  );
}
