// apps/dashboard/app/components/ProviderPinButton.vue
<script setup lang="ts">
import type { ProviderAccountKey } from "../../lib/provider-accounts";
import { cn } from "../../lib/utils";

const props = defineProps<{
  providerKey: ProviderAccountKey;
  pinned: boolean;
  readonly?: boolean;
  class?: string | string[];
}>();

const emit = defineEmits<{
  toggled: [providerKey: ProviderAccountKey, pinned: boolean];
}>();

const dashboardApi = useDashboardApi();
const dashboardInvalidation = useDashboardDataInvalidation();
const localPinned = ref(props.pinned);
const pending = ref(false);
const pinButtonLabel = computed(() => (localPinned.value ? "Unpin provider" : "Pin provider"));

watch(
  () => props.pinned,
  (value) => {
    localPinned.value = value;
  }
);

async function togglePin(event: Event) {
  event.preventDefault();
  event.stopPropagation();
  if (props.readonly) return;

  const previous = localPinned.value;
  localPinned.value = !previous;
  pending.value = true;
  try {
    const result = await dashboardApi.accounts.togglePinned({ providerKey: props.providerKey });
    if (!result.success) throw new Error(result.error);
    localPinned.value = result.data.pinned;
    dashboardInvalidation.patchPinnedProvider(props.providerKey, result.data.pinned);
    emit("toggled", props.providerKey, result.data.pinned);
  } catch {
    localPinned.value = previous;
  } finally {
    pending.value = false;
  }
}
</script>

<template>
  <UiTooltip :text="localPinned ? 'Unpin' : 'Pin'" :disabled="readonly">
    <button
      type="button"
      :class="cn(
        'cursor-pointer rounded-md p-1 transition-colors disabled:cursor-default disabled:opacity-50',
        localPinned ? 'text-foreground hover:text-muted-foreground' : 'text-muted-foreground/40 hover:text-muted-foreground',
        props.class,
      )"
      :aria-label="pinButtonLabel"
      :aria-pressed="localPinned"
      :disabled="pending || readonly"
      @click="togglePin"
    >
      <UiIcon :name="localPinned ? 'i-lucide-pin' : 'i-lucide-pin-off'" class="size-4" />
    </button>
  </UiTooltip>
</template>

// apps/web/src/components/ProviderPinButton.tsx
import { useState } from "react";
import type { ProviderAccountKey, ProviderAccountDefinition } from "../lib/provider-accounts";
import { useDashboardApi } from "../hooks/useDashboardApi";
import { useDashboardDataInvalidation } from "../hooks/useDashboardDataInvalidation";
import { UiIcon } from "./ui/UiIcon";
import { UiTooltip } from "./ui/UiTooltip";
import { cn } from "../lib/utils";

export interface ProviderPinButtonProps {
  providerKey: ProviderAccountKey;
  pinned: boolean;
  readonly?: boolean;
  className?: string;
  onToggled?: (providerKey: ProviderAccountKey, pinned: boolean) => void;
}

export function ProviderPinButton({ providerKey, pinned, readonly, className, onToggled }: ProviderPinButtonProps) {
  const dashboardApi = useDashboardApi();
  const dashboardInvalidation = useDashboardDataInvalidation();
  const [localPinned, setLocalPinned] = useState(pinned);
  const [pending, setPending] = useState(false);

  const togglePin = async (event: React.MouseEvent) => {
    event.preventDefault();
    event.stopPropagation();
    if (readonly) return;
    const previous = localPinned;
    setLocalPinned(!previous);
    setPending(true);
    try {
      const result = await dashboardApi.accounts.togglePinned({ providerKey });
      if (!result.success) throw new Error(result.error);
      setLocalPinned(result.data.pinned);
      dashboardInvalidation.refreshDashboardData([dashboardInvalidation.keys.shellAccounts, dashboardInvalidation.keys.accountsOverview]);
      onToggled?.(providerKey, result.data.pinned);
    } catch {
      setLocalPinned(previous);
    } finally {
      setPending(false);
    }
  };

  const button = (
    <button
      type="button"
      className={cn(
        "cursor-pointer rounded-md p-1 transition-colors disabled:cursor-default disabled:opacity-50",
        localPinned ? "text-foreground hover:text-muted-foreground" : "text-muted-foreground/40 hover:text-muted-foreground",
        className,
      )}
      aria-label={localPinned ? "Unpin provider" : "Pin provider"}
      aria-pressed={localPinned}
      disabled={pending || readonly}
      onClick={(event) => void togglePin(event)}
    >
      <UiIcon name={localPinned ? "i-lucide-pin" : "i-lucide-pin-off"} className="size-4" />
    </button>
  );

  if (readonly) return button;
  return <UiTooltip text={localPinned ? "Unpin" : "Pin"}>{button}</UiTooltip>;
}
