// apps/dashboard/app/components/ApiKeyExpiration.vue
<script setup lang="ts">
import { format } from "date-fns";

const props = defineProps<{
  apiKeyId: string;
  initialExpiresAt: string | Date | null;
}>();

const emit = defineEmits<{
  updated: [];
}>();

const { $client } = useNuxtApp();
const open = ref(false);
const isSaving = ref(false);
const expiresAt = ref<Date | null>(props.initialExpiresAt ? new Date(props.initialExpiresAt) : null);
const draftDate = ref(expiresAt.value ? format(expiresAt.value, "yyyy-MM-dd") : "");
const errorMessage = ref("");

watch(open, (value) => {
  if (value) {
    draftDate.value = expiresAt.value ? format(expiresAt.value, "yyyy-MM-dd") : "";
    errorMessage.value = "";
  }
});

const isExpired = computed(() => expiresAt.value != null && expiresAt.value < new Date());
const displayText = computed(() => (expiresAt.value ? format(expiresAt.value, "MMM d, yyyy") : "No expiry"));

function parseDraftDate(): Date | null {
  if (!draftDate.value) return null;
  const date = new Date(`${draftDate.value}T00:00:00`);
  return Number.isNaN(date.getTime()) ? null : date;
}

async function saveExpiration(value: Date | null) {
  isSaving.value = true;
  errorMessage.value = "";
  try {
    const result = await $client.apiKeys.updateExpiration.mutate({ id: props.apiKeyId, expiresAt: value });
    if (!result.success) throw new Error(result.error);
    expiresAt.value = result.data.expiresAt ? new Date(result.data.expiresAt) : null;
    open.value = false;
    emit("updated");
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : "Failed to update expiration";
  } finally {
    isSaving.value = false;
  }
}
</script>

<template>
  <UiPopover v-model:open="open" :content="{ align: 'start', class: 'w-72 p-0' }">
    <button
      type="button"
      :class="[
        'inline-flex cursor-pointer items-center gap-1 text-sm transition-colors hover:text-primary disabled:pointer-events-none disabled:opacity-50',
        isExpired ? 'text-destructive' : 'text-muted-foreground',
      ]"
      :disabled="isSaving"
    >
      <UiIcon name="i-lucide-calendar" class="size-3" />
      <span>{{ displayText }}</span>
    </button>
    <template #content>
      <div class="space-y-3 p-3">
        <label class="grid gap-1.5 text-xs font-medium text-muted-foreground">
          Expiration date
          <input v-model="draftDate" type="date" class="h-9 rounded-md border border-input bg-background px-3 text-sm text-foreground outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50">
        </label>
        <p v-if="errorMessage" class="text-xs text-destructive">{{ errorMessage }}</p>
        <div class="flex items-center justify-between gap-2 border-t pt-2">
          <UiButton variant="ghost" size="sm" class="h-7 gap-1 text-xs" :disabled="isSaving || !expiresAt" @click="saveExpiration(null)">
            <UiIcon name="i-lucide-x" class="size-3" />
            Remove expiration
          </UiButton>
          <UiButton size="sm" class="h-7 text-xs" :disabled="isSaving" @click="saveExpiration(parseDraftDate())">
            Save
          </UiButton>
        </div>
      </div>
    </template>
  </UiPopover>
</template>

// apps/dashboard/components/dashboard/api-keys/api-key-expiration.tsx
"use client";

import { useState } from "react";
import { format } from "date-fns";
import { Button } from "@/components/ui/button";
import { Calendar } from "@/components/ui/calendar";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { CalendarIcon, X } from "lucide-react";
import { toast } from "sonner";
import { updateApiKeyExpiration } from "@/lib/actions/api-keys";
import { cn } from "@/lib/utils";

interface ApiKeyExpirationProps {
  apiKeyId: string;
  initialExpiresAt: Date | null;
}

export function ApiKeyExpiration({
  apiKeyId,
  initialExpiresAt,
}: ApiKeyExpirationProps) {
  const [expiresAt, setExpiresAt] = useState<Date | null>(initialExpiresAt);
  const [open, setOpen] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  const now = new Date();
  const isExpired = expiresAt != null && expiresAt < now;

  const tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);
  tomorrow.setHours(0, 0, 0, 0);

  const handleSelect = async (date: Date | undefined) => {
    const newDate = date ?? null;
    setIsSaving(true);
    try {
      const result = await updateApiKeyExpiration(apiKeyId, newDate);
      if (!result.success) {
        throw new Error(result.error);
      }
      setExpiresAt(result.data.expiresAt);
      setOpen(false);
    } catch (error) {
      toast.error(
        error instanceof Error ? error.message : "Failed to update expiration"
      );
    } finally {
      setIsSaving(false);
    }
  };

  const handleClearExpiry = async () => {
    setIsSaving(true);
    try {
      const result = await updateApiKeyExpiration(apiKeyId, null);
      if (!result.success) {
        throw new Error(result.error);
      }
      setExpiresAt(null);
      setOpen(false);
    } catch (error) {
      toast.error(
        error instanceof Error ? error.message : "Failed to update expiration"
      );
    } finally {
      setIsSaving(false);
    }
  };

  const displayText = expiresAt
    ? format(expiresAt, "MMM d, yyyy")
    : "No expiry";

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <button
          type="button"
          className={cn(
            "inline-flex items-center gap-1 text-sm transition-colors cursor-pointer hover:text-primary",
            isExpired
              ? "text-destructive"
              : "text-muted-foreground"
          )}
          disabled={isSaving}
        >
          <CalendarIcon className="h-3 w-3" />
          <span>{displayText}</span>
        </button>
      </PopoverTrigger>
      <PopoverContent className="w-auto p-0" align="start">
        <div className="p-2 space-y-2">
          <Calendar
            mode="single"
            selected={expiresAt ?? undefined}
            onSelect={handleSelect}
            disabled={(date) => date < tomorrow || isSaving}
            initialFocus
          />
          {expiresAt && (
            <div className="flex justify-center border-t pt-2">
              <Button
                variant="ghost"
                size="sm"
                className="h-7 text-xs gap-1"
                onClick={handleClearExpiry}
                disabled={isSaving}
              >
                <X className="h-3 w-3" />
                Remove expiration
              </Button>
            </div>
          )}
        </div>
      </PopoverContent>
    </Popover>
  );
}
