// apps/dashboard/app/components/EditableApiKeyName.vue
<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    id: string;
    name: string | null;
    showTitle?: boolean;
    showEditButton?: boolean;
  }>(),
  {
    showTitle: true,
    showEditButton: true,
  }
);

const emit = defineEmits<{
  updated: [];
}>();

const { $client } = useNuxtApp();
const editDialogOpen = ref(false);
const newName = ref(props.name ?? "");
const isUpdating = ref(false);
const errorMessage = ref("");

watch(editDialogOpen, (open) => {
  if (open) {
    newName.value = props.name ?? "";
    errorMessage.value = "";
  }
});

async function updateName() {
  isUpdating.value = true;
  errorMessage.value = "";
  try {
    const result = await $client.apiKeys.updateName.mutate({ id: props.id, name: newName.value });
    if (!result.success) throw new Error(result.error);
    editDialogOpen.value = false;
    emit("updated");
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : "Failed to update API key name";
  } finally {
    isUpdating.value = false;
  }
}
</script>

<template>
  <div class="flex min-w-0 items-center gap-1.5">
    <span v-if="showTitle" class="min-w-0 truncate text-lg font-semibold">{{ name ?? 'Unnamed key' }}</span>
    <UiButton v-if="showEditButton" variant="outline" size="icon" class="h-9 w-9" title="Edit name" @click="editDialogOpen = true">
      <UiIcon name="i-lucide-pencil" class="size-4" />
    </UiButton>
  </div>

  <UiDialog v-model:open="editDialogOpen" :ui="{ content: 'sm:max-w-[400px]' }">
    <template #content>
      <div class="space-y-1.5 pr-6">
        <h2 class="text-lg font-semibold leading-none tracking-tight">Edit API Key Name</h2>
        <p class="sr-only">Change the name of your API key.</p>
      </div>
      <div v-if="errorMessage" class="rounded-lg border border-destructive/50 bg-destructive/10 px-3 py-2 text-sm text-destructive">
        {{ errorMessage }}
      </div>
      <div class="py-3">
        <label class="grid gap-1.5 text-sm font-medium">
          Name
          <input
            v-model="newName"
            class="h-9 rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50"
            placeholder="My API Key"
            @keydown.enter.prevent="updateName"
          >
        </label>
      </div>
      <div class="flex justify-end gap-2">
        <UiButton variant="outline" size="sm" @click="editDialogOpen = false">Cancel</UiButton>
        <UiButton size="sm" :disabled="isUpdating" @click="updateName">{{ isUpdating ? 'Saving...' : 'Save' }}</UiButton>
      </div>
    </template>
  </UiDialog>
</template>

// apps/dashboard/components/dashboard/api-keys/editable-api-key-name.tsx
"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Pencil } from "lucide-react";
import { toast } from "sonner";
import { updateApiKeyName } from "@/lib/actions/api-keys";

interface EditableApiKeyNameProps {
  id: string;
  name: string | null;
  showTitle?: boolean;
  showEditButton?: boolean;
}

export function EditableApiKeyName({
  id,
  name,
  showTitle = true,
  showEditButton = true,
}: EditableApiKeyNameProps) {
  const [editDialogOpen, setEditDialogOpen] = useState(false);
  const [newName, setNewName] = useState(name ?? "");
  const [isUpdating, setIsUpdating] = useState(false);

  const handleUpdateName = async () => {
    setIsUpdating(true);
    try {
      const result = await updateApiKeyName(id, newName);

      if (!result.success) {
        throw new Error(result.error);
      }

      setEditDialogOpen(false);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to update API key name");
    } finally {
      setIsUpdating(false);
    }
  };

  return (
    <Dialog
      open={editDialogOpen}
      onOpenChange={(open) => {
        setEditDialogOpen(open);
        if (open) setNewName(name ?? "");
      }}
    >
      <div className="flex min-w-0 items-center gap-1.5">
        {showTitle && (
          <span className="min-w-0 truncate text-lg font-semibold">{name ?? "Unnamed key"}</span>
        )}
        {showEditButton && (
          <DialogTrigger asChild>
            <Button
              variant="outline"
              size="icon"
              className="h-9 w-9"
              title="Edit name"
              aria-label="Edit name"
            >
              <Pencil className="h-4 w-4" />
            </Button>
          </DialogTrigger>
        )}
      </div>
      <DialogContent className="sm:max-w-[400px]">
        <DialogHeader>
          <DialogTitle>Edit API Key Name</DialogTitle>
          <DialogDescription className="sr-only">
            Change the name of your API key.
          </DialogDescription>
        </DialogHeader>
        <div className="py-3">
          <Label htmlFor="apiKeyName">Name</Label>
          <Input
            id="apiKeyName"
            value={newName}
            onChange={(e) => setNewName(e.target.value)}
            placeholder="My API Key"
            className="mt-1.5"
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                e.preventDefault();
                handleUpdateName();
              }
            }}
          />
        </div>
        <DialogFooter>
          <Button variant="outline" size="sm" onClick={() => setEditDialogOpen(false)}>
            Cancel
          </Button>
          <Button
            size="sm"
            onClick={handleUpdateName}
            disabled={isUpdating}
          >
            {isUpdating ? "Saving..." : "Save"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
