// app/dashboard/accounts/add-account-dialog.tsx
"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Alert, AlertDescription } from "@/components/ui/alert";
import {
  Loader2,
  ExternalLink,
  AlertCircle,
  Plus,
  ArrowLeft,
  ArrowRight,
  Zap,
  Sparkles,
  Terminal,
  Check,
  Copy,
  Cpu,
  Bot,
} from "lucide-react";
import { toast } from "sonner";
import {
  exchangeIflowOAuthCode,
  exchangeAntigravityOAuthCode,
  exchangeGeminiCliOAuthCode,
  getIflowAuthUrl,
  getAntigravityAuthUrl,
  getGeminiCliAuthUrl,
  initiateQwenCodeAuth,
  pollQwenCodeAuth,
  initiateCodexAuth,
  pollCodexAuth,
} from "@/lib/actions/accounts";
import { cn } from "@/lib/utils";

type Provider = "iflow" | "antigravity" | "qwen_code" | "gemini_cli" | "codex" | null;

interface OAuthRedirectConfig {
  flowType: "oauth_redirect";
  getAuthUrl: () => Promise<{ success: true; data: { authUrl: string } } | { success: false; error: string }>;
  exchangeAction: (callbackUrl: string) => Promise<{ success: true; data: { email: string; isUpdate: boolean } } | { success: false; error: string }>;
}

interface DeviceCodeConfig {
  flowType: "device_code";
}

interface ProviderConfig {
  name: string;
  icon: typeof Zap;
  description: string;
}

type ProviderFullConfig = ProviderConfig & (OAuthRedirectConfig | DeviceCodeConfig);

const PROVIDERS: Record<Exclude<Provider, null>, ProviderFullConfig> = {
  iflow: {
    name: "Iflow",
    icon: Zap,
    description: "Access OpenAI compatible API",
    flowType: "oauth_redirect",
    getAuthUrl: getIflowAuthUrl,
    exchangeAction: exchangeIflowOAuthCode,
  },
  antigravity: {
    name: "Antigravity",
    icon: Sparkles,
    description: "Access Gemini & Claude via Google OAuth",
    flowType: "oauth_redirect",
    getAuthUrl: getAntigravityAuthUrl,
    exchangeAction: exchangeAntigravityOAuthCode,
  },
  gemini_cli: {
    name: "Gemini CLI",
    icon: Cpu,
    description: "Access Gemini 2.5 Pro & 3 models",
    flowType: "oauth_redirect",
    getAuthUrl: getGeminiCliAuthUrl,
    exchangeAction: exchangeGeminiCliOAuthCode,
  },
  qwen_code: {
    name: "Qwen Code",
    icon: Terminal,
    description: "Access Qwen Coder models",
    flowType: "device_code",
  },
  codex: {
    name: "ChatGPT Codex",
    icon: Bot,
    description: "Access GPT-5 Codex models",
    flowType: "device_code",
  },
};



export function AddAccountDialog() {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [step, setStep] = useState(1);
  const [provider, setProvider] = useState<Provider>(null);
  const [callbackUrl, setCallbackUrl] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  
  // OAuth redirect flow state
  const [authUrl, setAuthUrl] = useState("");
  const [isFetchingUrl, setIsFetchingUrl] = useState(false);
  
  // Device code flow state
  const [deviceCodeInfo, setDeviceCodeInfo] = useState<{
    deviceCode: string;
    verificationUrl: string;
    codeVerifier?: string; // Qwen Code only (stored client-side)
    userCode?: string; // Codex only (displayed to user)
  } | null>(null);
  const [isPolling, setIsPolling] = useState(false);
  const pollingRef = useRef<NodeJS.Timeout | null>(null);

  const providerConfig = provider ? PROVIDERS[provider] : null;

  // Cleanup polling on unmount or dialog close
  useEffect(() => {
    return () => {
      if (pollingRef.current) {
        clearInterval(pollingRef.current);
        pollingRef.current = null;
      }
    };
  }, []);

  // Fetch auth URL or initiate device code when entering step 2
  useEffect(() => {
    if (step === 2 && provider && providerConfig) {
      if (providerConfig.flowType === "oauth_redirect") {
        setIsFetchingUrl(true);
        setAuthUrl("");
        providerConfig.getAuthUrl()
          .then((result) => {
            if (result.success) {
              setAuthUrl(result.data.authUrl);
            } else {
              setError(result.error);
            }
          })
          .finally(() => setIsFetchingUrl(false));
      } else if (providerConfig.flowType === "device_code") {
        setIsFetchingUrl(true);
        setDeviceCodeInfo(null);
        
        if (provider === "codex") {
          // Codex device code flow
          initiateCodexAuth()
            .then((result) => {
              if (result.success) {
                setDeviceCodeInfo({
                  deviceCode: result.data.deviceAuthId,
                  verificationUrl: result.data.verificationUrl,
                  userCode: result.data.userCode,
                });
              } else {
                setError(result.error);
              }
            })
            .finally(() => setIsFetchingUrl(false));
        } else {
          // Qwen Code device code flow
          initiateQwenCodeAuth()
            .then((result) => {
              if (result.success) {
                setDeviceCodeInfo({
                  deviceCode: result.data.deviceCode,
                  verificationUrl: result.data.verificationUrlComplete,
                  codeVerifier: result.data.codeVerifier,
                });
              } else {
                setError(result.error);
              }
            })
            .finally(() => setIsFetchingUrl(false));
        }
      }
    }
  }, [step, provider, providerConfig]);

  const resetForm = useCallback(() => {
    setStep(1);
    setProvider(null);
    setCallbackUrl("");
    setError("");
    setIsLoading(false);
    setAuthUrl("");
    setIsFetchingUrl(false);
    setDeviceCodeInfo(null);
    setIsPolling(false);
    if (pollingRef.current) {
      clearInterval(pollingRef.current);
      pollingRef.current = null;
    }
  }, []);

  const handleOpenChange = (isOpen: boolean) => {
    if (!isLoading && !isPolling) {
      setOpen(isOpen);
      if (!isOpen) {
        resetForm();
      }
    }
  };

  const handleSelectProvider = (selectedProvider: Provider) => {
    setProvider(selectedProvider);
    setStep(2);
  };

  const handleStartOAuth = () => {
    if (!authUrl) return;

    const width = 600;
    const height = 700;
    const left = Math.round((window.screen.width - width) / 2);
    const top = Math.round((window.screen.height - height) / 2);

    const popup = window.open(
      authUrl,
      "oauth_popup",
      `width=${width},height=${height},left=${left},top=${top},scrollbars=yes,resizable=yes`
    );

    if (!popup || popup.closed) {
      window.open(authUrl, "_blank");
    }

    setStep(3);
  };

  const handleStartDeviceCodeAuth = () => {
    if (!deviceCodeInfo) return;

    // Open in centered popup window (same as OAuth flow)
    const width = 600;
    const height = 700;
    const left = Math.round((window.screen.width - width) / 2);
    const top = Math.round((window.screen.height - height) / 2);

    const popup = window.open(
      deviceCodeInfo.verificationUrl,
      "device_auth_popup",
      `width=${width},height=${height},left=${left},top=${top},scrollbars=yes,resizable=yes`
    );

    // Fallback to new tab if popup blocked
    if (!popup || popup.closed) {
      window.open(deviceCodeInfo.verificationUrl, "_blank");
      startPolling(null);
    } else {
      startPolling(popup);
    }
  };

  const startPolling = useCallback((popup: Window | null) => {
    if (!deviceCodeInfo || isPolling) return;

    setIsPolling(true);
    setError("");

    const poll = async () => {
      if (!deviceCodeInfo) return;

      // Check if popup was closed by user
      if (popup && popup.closed) {
        setIsPolling(false);
        setError("");
        if (pollingRef.current) {
          clearInterval(pollingRef.current);
          pollingRef.current = null;
        }
        return;
      }

      try {
        // Use the correct polling action based on provider
        const result = provider === "codex"
          ? await pollCodexAuth(
              deviceCodeInfo.deviceCode,
              deviceCodeInfo.userCode || ""
            )
          : await pollQwenCodeAuth(
              deviceCodeInfo.deviceCode,
              deviceCodeInfo.codeVerifier || ""
            );

        if (!result.success) {
          setError(result.error);
          setIsPolling(false);
          if (pollingRef.current) {
            clearInterval(pollingRef.current);
            pollingRef.current = null;
          }
          return;
        }

        if (result.data.status === "success") {
          // Close popup if still open
          if (popup && !popup.closed) {
            popup.close();
          }
          const providerDisplayName = provider === "codex" ? "ChatGPT Codex" : "Qwen Code";
          toast.success(
            result.data.isUpdate
              ? `${providerDisplayName} account updated successfully!`
              : `${providerDisplayName} account connected successfully!`
          );
          setOpen(false);
          resetForm();
          router.refresh();
          return;
        }

        if (result.data.status === "error") {
          const msg = typeof result.data.message === "string"
            ? result.data.message
            : "An error occurred";
          setError(msg);
          setIsPolling(false);
          if (pollingRef.current) {
            clearInterval(pollingRef.current);
            pollingRef.current = null;
          }
          return;
        }

        // status === "pending" - continue polling
      } catch (err) {
        console.error("Polling error:", err);
      }
    };

    // Initial poll
    poll();

    // Set up interval polling every 5 seconds
    pollingRef.current = setInterval(poll, 5000);
  }, [deviceCodeInfo, isPolling, provider, resetForm, router]);

  const handleCopyLink = async () => {
    const urlToCopy = providerConfig?.flowType === "device_code" 
      ? deviceCodeInfo?.verificationUrl 
      : authUrl;
    
    if (urlToCopy) {
      await navigator.clipboard.writeText(urlToCopy);
      toast.success("Link copied to clipboard");
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");

    if (!provider || !providerConfig || providerConfig.flowType !== "oauth_redirect") {
      setError("Invalid provider configuration");
      return;
    }

    if (!callbackUrl.trim()) {
      setError("Please paste the callback URL");
      return;
    }

    if (!callbackUrl.includes("code=")) {
      setError("Invalid URL. Make sure the URL contains 'code=' parameter.");
      return;
    }

    setIsLoading(true);

    try {
      const result = await providerConfig.exchangeAction(callbackUrl.trim());

      if (!result.success) {
        throw new Error(result.error);
      }

      const message = result.data.isUpdate
        ? `${providerConfig.name} account updated successfully!`
        : `${providerConfig.name} account connected successfully!`;

      toast.success(message);
      setOpen(false);
      resetForm();
      router.refresh();
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to connect account";
      setError(message);
      toast.error(message);
    } finally {
      setIsLoading(false);
    }
  };

  const renderProviderIcon = (config: ProviderConfig, className?: string) => {
    const Icon = config.icon;
    return <Icon className={className} />;
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogTrigger asChild>
        <Button className="gap-2">
          <Plus className="h-4 w-4" />
          Add Account
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Add Provider Account</DialogTitle>
          <DialogDescription>
            Connect a new AI provider account for load balancing
          </DialogDescription>
        </DialogHeader>

        {/* Step Indicator */}
        <div className="flex items-center justify-center gap-2">
          {[1, 2, 3].map((s) => (
            <div key={s} className="flex items-center">
              <div
                className={cn(
                  "flex h-8 w-8 items-center justify-center rounded-full text-sm font-medium transition-colors",
                  step > s
                    ? "bg-primary text-primary-foreground"
                    : step === s
                      ? "bg-primary text-primary-foreground"
                      : "bg-muted text-muted-foreground"
                )}
              >
                {step > s ? <Check className="h-4 w-4" /> : s}
              </div>
              {s < 3 && (
                <div
                  className={cn(
                    "h-px w-8 transition-colors",
                    step > s ? "bg-primary" : "bg-border"
                  )}
                />
              )}
            </div>
          ))}
        </div>

        {/* Step Content */}
        <div className="min-h-[200px] space-y-4">
          {/* Step 1: Select Provider */}
          {step === 1 && (
            <div className="space-y-4">
              <Label className="text-sm font-medium">Choose a provider</Label>
              <div className="grid grid-cols-3 gap-3">
                {(Object.entries(PROVIDERS) as [Exclude<Provider, null>, ProviderFullConfig][]).map(
                  ([key, config]) => (
                    <button
                      key={key}
                      type="button"
                      onClick={() => handleSelectProvider(key)}
                      className={cn(
                        "flex flex-col items-center gap-2 rounded-lg border-2 p-3 text-center transition-all hover:border-primary hover:bg-accent",
                        provider === key
                          ? "border-primary bg-accent"
                          : "border-border"
                      )}
                    >
                      {renderProviderIcon(config, "h-6 w-6")}
                      <div>
                        <div className="text-sm font-medium">{config.name}</div>
                        <div className="text-[10px] text-muted-foreground leading-tight">
                          {config.description}
                        </div>
                      </div>
                    </button>
                  )
                )}
              </div>
            </div>
          )}

          {/* Step 2: OAuth Login / Device Code */}
          {step === 2 && providerConfig && (
            <div className="space-y-4">
              {providerConfig.flowType === "oauth_redirect" ? (
                // OAuth Redirect Flow
                <>
                  <div className="space-y-2">
                    <Label className="text-sm font-medium">
                      Login to {providerConfig.name}
                    </Label>
                    <p className="text-sm text-muted-foreground">
                      Click the button below to open the login page in a new window.
                      After logging in, you&apos;ll be redirected to a page that shows
                      an error - this is expected.
                    </p>
                  </div>
                  <div className="flex gap-2">
                    <Button
                      onClick={handleStartOAuth}
                      variant="outline"
                      className="flex-1"
                      disabled={isFetchingUrl || !authUrl}
                    >
                      {isFetchingUrl ? (
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      ) : (
                        <ExternalLink className="mr-2 h-4 w-4" />
                      )}
                      Open {providerConfig.name} Login
                    </Button>
                    <Button
                      onClick={handleCopyLink}
                      variant="outline"
                      disabled={isFetchingUrl || !authUrl}
                      title="Copy login link"
                    >
                      <Copy className="h-4 w-4" />
                    </Button>
                  </div>
                  <Alert>
                    <AlertCircle className="h-4 w-4" />
                    <AlertDescription className="text-xs">
                      After login, copy the URL from address bar:{" "}
                      <code className="rounded bg-muted px-1">localhost:11451/...?code=...</code>
                    </AlertDescription>
                  </Alert>
                </>
              ) : (
                // Device Code Flow
                <>
                  <div className="space-y-2">
                    <Label className="text-sm font-medium">
                      Login to {providerConfig.name}
                    </Label>
                    <p className="text-sm text-muted-foreground">
                      {provider === "codex"
                        ? "Click the button below to open the OpenAI login page. Enter the code shown below when prompted."
                        : "Click the button below to open the Qwen login page. After you complete the login, authorization will be detected automatically."}
                    </p>
                  </div>
                  {/* Show user code for Codex (user must enter it on OpenAI page) */}
                  {provider === "codex" && deviceCodeInfo?.userCode && (
                    <div className="flex items-center justify-center gap-3 rounded-lg border-2 border-dashed border-primary/50 bg-muted/50 p-4">
                      <code className="text-2xl font-mono font-bold tracking-widest">
                        {deviceCodeInfo.userCode}
                      </code>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={async () => {
                          await navigator.clipboard.writeText(deviceCodeInfo.userCode || "");
                          toast.success("Code copied to clipboard");
                        }}
                      >
                        <Copy className="h-4 w-4" />
                      </Button>
                    </div>
                  )}
                  <div className="flex gap-2">
                    <Button
                      onClick={handleStartDeviceCodeAuth}
                      variant="outline"
                      className="flex-1"
                      disabled={isFetchingUrl || !deviceCodeInfo || isPolling}
                    >
                      {isFetchingUrl ? (
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      ) : isPolling ? (
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      ) : (
                        <ExternalLink className="mr-2 h-4 w-4" />
                      )}
                      {isPolling ? "Waiting for login..." : `Open ${providerConfig.name} Login`}
                    </Button>
                    <Button
                      onClick={handleCopyLink}
                      variant="outline"
                      disabled={isFetchingUrl || !deviceCodeInfo}
                      title="Copy login link"
                    >
                      <Copy className="h-4 w-4" />
                    </Button>
                  </div>
                  {isPolling && (
                    <Alert>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      <AlertDescription className="text-xs">
                        Complete the login in your browser. This dialog will close
                        automatically when authorization is complete.
                      </AlertDescription>
                    </Alert>
                  )}
                  {error && (
                    <Alert variant="destructive">
                      <AlertCircle className="h-4 w-4" />
                      <AlertDescription className="text-xs">{error}</AlertDescription>
                    </Alert>
                  )}
                </>
              )}
            </div>
          )}

          {/* Step 3: Paste URL (OAuth Redirect only) */}
          {step === 3 && providerConfig && providerConfig.flowType === "oauth_redirect" && (
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="space-y-2">
                <Label className="text-sm font-medium">Paste Callback URL</Label>
                <p className="text-sm text-muted-foreground">
                  Paste the URL from your browser after the OAuth redirect.
                </p>
                <Input
                  placeholder="http://localhost:11451/oauth2callback?code=..."
                  value={callbackUrl}
                  onChange={(e) => setCallbackUrl(e.target.value)}
                  disabled={isLoading}
                  autoFocus
                />
                {error && <p className="text-sm text-destructive">{error}</p>}
              </div>
              <Button type="submit" className="w-full" disabled={isLoading}>
                {isLoading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Connecting...
                  </>
                ) : (
                  <>
                    {renderProviderIcon(providerConfig, "mr-2 h-4 w-4")}
                    Connect {providerConfig.name} Account
                  </>
                )}
              </Button>
            </form>
          )}
        </div>

        <DialogFooter className="sm:justify-between">
          <div>
            {step > 1 && !isPolling && (
              <Button
                type="button"
                variant="ghost"
                onClick={() => setStep(step - 1)}
                disabled={isLoading}
              >
                <ArrowLeft className="mr-2 h-4 w-4" />
                Back
              </Button>
            )}
          </div>
          <div>
            {step === 2 && providerConfig?.flowType === "oauth_redirect" && (
              <Button
                type="button"
                variant="ghost"
                onClick={() => setStep(3)}
              >
                Next
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            )}
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// apps/web/app/components/account/AddAccountDialog.vue
<script setup lang="ts">
import { cn } from "~~/lib/utils";
import type { Provider } from "~~/lib/provider-auth-config";

const props = withDefaults(
  defineProps<{
    initialProvider?: Provider | null;
    triggerClass?: string;
    readonly?: boolean;
  }>(),
  {
    initialProvider: null,
    triggerClass: "",
    readonly: false,
  }
);

const emit = defineEmits<{
  connected: [result: { provider: Provider; email: string; isUpdate: boolean }];
  customCreated: [slug: string];
}>();

const {
  customList,
  open,
  customMode,
  minimumStep,
  step,
  provider,
  callbackUrl,
  chatgptSessionJson,
  apiKey,
  platformKey,
  cfAccountId,
  authUrl,
  selectedMethod,
  deviceCodeInfo,
  copiedLink,
  copiedDeviceCode,
  copiedCallbackUrl,
  isApiKeyVisible,
  isLoading,
  isFetchingUrl,
  isPolling,
  errorMessage,
  selectedConfig,
  activeFlowType,
  authStep,
  finishStep,
  dialogOpen,
  displayedSteps,
  shouldPreventOutsideClose,
  handleCustomCreated,
  selectProvider,
  selectCustom,
  selectLoginMethod,
  copyText,
  openPopup,
  openOAuthUrl,
  openDeviceAuthUrl,
  openApiKeyPortal,
  handleConnectApiKey,
  handleConnectCodexSession,
  handleCallbackInput,
  pasteCallbackUrl,
  handleCallbackPaste,
  goBack,
  goBackFromDevicePolling,
  providerOptions,
  chatgptSessionPlaceholder,
  providerConfigs,
  callbackPlaceholder,
} = useAccountConnect(props, {
  onConnected: (result) => emit("connected", result),
  onCustomCreated: (slug) => emit("customCreated", slug),
});
</script>

<template>
  <UiButton variant="outline" :class="cn('gap-2', triggerClass)" :disabled="readonly" @click="open = true">
    <UiIcon name="i-lucide-plus" class="size-4" />
    Add Account
  </UiButton>

  <UiDialog
    v-model:open="dialogOpen"
    :prevent-outside-close="shouldPreventOutsideClose"
    :prevent-escape-close="isPolling"
    :ui="{ content: 'max-h-[calc(100dvh-1rem)] p-4 sm:max-w-lg sm:p-6' }"
  >
    <template #content>
      <div class="space-y-1.5 pr-6">
        <h2 class="text-lg font-semibold leading-none tracking-tight">
          {{ customMode ? 'Add Custom Provider' : selectedConfig ? `Add ${selectedConfig.name} Account` : 'Add Provider Account' }}
        </h2>
        <p class="sr-only">
          {{ selectedConfig ? `Connect a new ${selectedConfig.name} account for load balancing` : 'Connect a new AI provider account for load balancing' }}
        </p>
      </div>

      <template v-if="!customMode">
      <div class="flex items-center justify-center py-2">
        <template v-for="(stepNumber, index) in displayedSteps" :key="stepNumber">
          <div class="flex items-center">
            <div
              :class="cn(
                'flex h-8 w-8 items-center justify-center rounded-full text-sm font-medium transition-colors',
                step >= stepNumber ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground',
              )"
            >
              <UiIcon v-if="step > stepNumber" name="i-lucide-check" class="size-4" />
              <span v-else>{{ index + 1 }}</span>
            </div>
            <div v-if="index < displayedSteps.length - 1" :class="cn('h-px w-10 transition-colors', step > stepNumber ? 'bg-primary' : 'bg-border')" />
          </div>
        </template>
      </div>

      <div class="min-h-0 flex-1 space-y-4 overflow-y-auto">
        <div v-if="step === 1" class="space-y-4">
          <div class="grid grid-cols-2 gap-3 sm:grid-cols-3">
            <button
              v-for="providerKey in providerOptions"
              :key="providerKey"
              type="button"
              :class="cn(
                'flex cursor-pointer flex-col items-center gap-2 rounded-lg border p-3 text-center transition-colors hover:bg-muted/40',
                provider === providerKey ? 'border-foreground/30 bg-muted/30' : 'border-border',
              )"
              @click="selectProvider(providerKey)"
            >
              <span class="text-sm font-medium">{{ providerConfigs[providerKey]?.name }}</span>
            </button>
            <button
              v-for="row in customList"
              :key="row.slug"
              type="button"
              :class="cn(
                'flex cursor-pointer flex-col items-center gap-2 rounded-lg border p-3 text-center transition-colors hover:bg-muted/40',
                provider === row.slug ? 'border-foreground/30 bg-muted/30' : 'border-border',
              )"
              @click="selectProvider(row.slug)"
            >
              <span class="text-sm font-medium">{{ row.name }}</span>
            </button>
            <button
              v-if="!readonly"
              type="button"
              :class="cn(
                'flex cursor-pointer flex-col items-center gap-2 rounded-lg border p-3 text-center transition-colors hover:bg-muted/40',
                customMode ? 'border-foreground/30 bg-muted/30' : 'border-border',
              )"
              @click="selectCustom"
            >
              <span class="flex items-center gap-2 text-sm font-medium">
                <UiIcon name="i-lucide-plus" class="size-4" />
                Custom
              </span>
            </button>
          </div>
        </div>

        <div v-if="step === 2 && selectedConfig" class="space-y-4">
          <div class="space-y-2">
            <p class="text-sm font-medium">Choose {{ selectedConfig.name }} method</p>
          </div>
          <div class="grid gap-3">
            <button
              v-for="method in selectedConfig.methods"
              :key="method.key"
              type="button"
              :disabled="method.disabled"
              :class="cn(
                'flex cursor-pointer items-start gap-3 rounded-lg border p-3 text-left transition-colors hover:bg-muted/40 disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:bg-transparent',
                selectedMethod === method.key ? 'border-foreground/30 bg-muted/30' : 'border-border',
              )"
              @click="selectLoginMethod(method.key)"
            >
              <span class="flex items-center gap-2 text-sm font-medium">
                {{ method.name }}
                <span v-if="method.tag" class="rounded bg-muted px-1.5 py-0.5 text-[10px] font-medium text-muted-foreground">{{ method.tag }}</span>
                <span v-if="method.disabled" class="rounded bg-muted px-1.5 py-0.5 text-[10px] font-medium text-muted-foreground">Unavailable</span>
              </span>
            </button>
          </div>
        </div>

        <div v-if="(step === authStep || (step === finishStep && activeFlowType === 'device_code' && isPolling)) && selectedConfig && activeFlowType" class="space-y-4">
          <template v-if="activeFlowType === 'oauth_redirect'">
            <div class="space-y-2">
              <p class="text-sm font-medium">Login to {{ selectedConfig.name }}</p>
              <p class="text-sm text-muted-foreground">
                Click the button below to open the login page in a new window. After logging in, you'll be redirected to a page that shows an error - this is expected.
              </p>
            </div>
            <div class="flex gap-2">
              <UiButton variant="outline" class="flex-1" :disabled="isFetchingUrl || !authUrl" @click="openOAuthUrl">
                <UiIcon :name="isFetchingUrl ? 'i-lucide-loader-2' : 'i-lucide-external-link'" :class="['size-4', isFetchingUrl ? 'animate-spin' : '']" />
                Open {{ selectedConfig.name }} Login
              </UiButton>
              <UiTooltip :text="copiedLink ? 'Copied' : 'Copy link'">
                <UiButton variant="outline" :disabled="isFetchingUrl || !authUrl" @click="copyText(authUrl, 'link')">
                  <UiIcon :name="copiedLink ? 'i-lucide-check' : 'i-lucide-copy'" class="size-4" />
                </UiButton>
              </UiTooltip>
            </div>
            <div class="relative w-full rounded-lg border px-4 py-3 text-sm">
              <UiIcon name="i-lucide-alert-circle" class="absolute left-4 top-4 size-4" />
              <div class="pl-7 text-xs">
                After login, copy the URL from address bar:
                <code class="rounded bg-muted px-1">{{ callbackPlaceholder(provider) }}</code>
              </div>
            </div>
          </template>

          <template v-else-if="activeFlowType === 'device_code'">
            <div class="space-y-2">
              <p class="text-sm font-medium">Login to {{ selectedConfig.name }}</p>
              <p class="text-sm text-muted-foreground">
                Click the button below to open the provider login page. Enter the code shown below on the provider login page. After you complete the login, authorization will be detected automatically.
              </p>
            </div>
            <div v-if="deviceCodeInfo?.userCode" class="rounded-md border border-border bg-muted/30 p-3">
              <p class="text-xs text-muted-foreground">Enter this code on the provider page:</p>
              <div class="mt-2 flex flex-wrap items-center gap-2">
                <code class="rounded bg-background px-2 py-1 font-mono text-sm font-semibold tracking-[0.15em]">{{ deviceCodeInfo.userCode }}</code>
                <UiButton type="button" size="sm" variant="outline" @click="copyText(deviceCodeInfo.userCode, 'code')">
                  <UiIcon :name="copiedDeviceCode ? 'i-lucide-check' : 'i-lucide-copy'" class="size-3.5" />
                  {{ copiedDeviceCode ? 'Copied' : 'Copy code' }}
                </UiButton>
              </div>
            </div>
            <div class="flex gap-2">
              <UiButton variant="outline" class="flex-1" :disabled="isFetchingUrl || !deviceCodeInfo" @click="openDeviceAuthUrl">
                <UiIcon :name="isFetchingUrl ? 'i-lucide-loader-2' : 'i-lucide-external-link'" :class="['size-4', isFetchingUrl ? 'animate-spin' : '']" />
                Open {{ selectedConfig.name }} Login
              </UiButton>
              <UiTooltip :text="copiedLink ? 'Copied' : 'Copy link'">
                <UiButton variant="outline" :disabled="isFetchingUrl || !deviceCodeInfo" @click="deviceCodeInfo && copyText(deviceCodeInfo.verificationUrl, 'link')">
                  <UiIcon :name="copiedLink ? 'i-lucide-check' : 'i-lucide-copy'" class="size-4" />
                </UiButton>
              </UiTooltip>
            </div>
            <div v-if="isPolling" class="relative w-full rounded-lg border px-4 py-3 text-sm">
              <UiIcon name="i-lucide-loader-2" class="absolute left-4 top-4 size-4 animate-spin" />
              <div class="pl-7 text-xs">
                Complete the login in your browser. This dialog will close automatically when authorization is complete.
              </div>
            </div>
          </template>

          <template v-else-if="activeFlowType === 'chatgpt_session'">
            <div class="space-y-2">
              <p class="text-sm font-medium">Copy ChatGPT session</p>
              <p class="text-sm text-muted-foreground">
                Open the session page while logged in to ChatGPT, copy the full response, then paste it here. This method has no refresh token, so reconnect when the access token expires.
              </p>
            </div>
            <div class="rounded-md border border-border bg-muted/30 p-3">
              <p class="break-all text-xs text-muted-foreground">https://chatgpt.com/api/auth/session</p>
            </div>
            <div class="flex gap-2">
              <UiButton type="button" variant="outline" class="flex-1" @click="openPopup('https://chatgpt.com/api/auth/session', 'chatgpt_session', 1100, 760)">
                <UiIcon name="i-lucide-external-link" class="size-4" />
                Open Session Page
              </UiButton>
              <UiTooltip :text="copiedLink ? 'Copied' : 'Copy link'">
                <UiButton type="button" variant="outline" @click="copyText('https://chatgpt.com/api/auth/session', 'link')">
                  <UiIcon :name="copiedLink ? 'i-lucide-check' : 'i-lucide-copy'" class="size-4" />
                </UiButton>
              </UiTooltip>
            </div>
          </template>

          <template v-else>
            <div class="space-y-2">
              <p class="text-sm font-medium">Get {{ selectedConfig.name }} API Key</p>
              <p class="text-sm text-muted-foreground">
                Open the provider page below and create or copy your API key. You will continue to the next step automatically.
              </p>
            </div>
            <div class="rounded-md border border-border bg-muted/30 p-3">
              <p class="break-all text-xs text-muted-foreground">{{ selectedConfig.apiKeyPortalUrl }}</p>
            </div>
            <div class="flex gap-2">
              <UiButton type="button" variant="outline" class="flex-1" @click="openApiKeyPortal">
                <UiIcon name="i-lucide-external-link" class="size-4" />
                Open {{ selectedConfig.name }} Portal
              </UiButton>
              <UiTooltip :text="copiedLink ? 'Copied' : 'Copy link'">
                <UiButton type="button" variant="outline" @click="authUrl && copyText(authUrl, 'link')">
                  <UiIcon :name="copiedLink ? 'i-lucide-check' : 'i-lucide-copy'" class="size-4" />
                </UiButton>
              </UiTooltip>
            </div>
          </template>

          <div v-if="errorMessage" class="relative w-full rounded-lg border border-destructive/50 px-4 py-3 text-sm text-destructive">
            <UiIcon name="i-lucide-alert-circle" class="absolute left-4 top-4 size-4" />
            <div class="pl-7 text-xs">{{ errorMessage }}</div>
          </div>
        </div>

        <form v-if="step === finishStep && selectedConfig && activeFlowType === 'oauth_redirect'" class="space-y-4" @submit.prevent>
          <div class="space-y-2">
            <label for="callback-url" class="text-sm font-medium">
              Paste Callback URL <span aria-hidden="true" class="text-destructive">*</span>
            </label>
            <p class="text-sm text-muted-foreground">Paste the URL from your browser after the OAuth redirect.</p>
            <div class="relative">
              <input
                id="callback-url"
                v-model="callbackUrl"
                type="text"
                :placeholder="callbackPlaceholder(provider)"
                :disabled="isLoading"
                class="h-9 w-full rounded-md border border-input bg-background px-3 pr-9 text-sm outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:opacity-50"
                @input="handleCallbackInput"
                @paste="handleCallbackPaste"
              >
              <UiTooltip :text="copiedCallbackUrl ? 'Pasted' : 'Paste'">
                <button
                  type="button"
                  :disabled="isLoading"
                  class="absolute right-2.5 top-1/2 -translate-y-1/2 text-muted-foreground transition-colors hover:text-foreground disabled:opacity-50"
                  aria-label="Paste callback URL"
                  @click="pasteCallbackUrl"
                >
                  <UiIcon :name="isLoading ? 'i-lucide-loader-2' : copiedCallbackUrl ? 'i-lucide-check' : 'i-lucide-clipboard-paste'" :class="['size-4', isLoading ? 'animate-spin' : '']" />
                </button>
              </UiTooltip>
            </div>
            <p v-if="errorMessage" class="text-sm text-destructive">{{ errorMessage }}</p>
          </div>
        </form>

        <form
          v-if="step === finishStep && selectedConfig && activeFlowType === 'chatgpt_session'"
          class="space-y-4"
          autocomplete="off"
          data-lpignore="true"
          data-1p-ignore="true"
          @submit.prevent="handleConnectCodexSession"
        >
          <div class="space-y-2">
            <label for="chatgpt-session-json" class="text-sm font-medium">
              Paste Session <span aria-hidden="true" class="text-destructive">*</span>
            </label>
            <p class="text-sm text-muted-foreground">Paste the full response from <code class="rounded bg-muted px-1">chatgpt.com/api/auth/session</code>.</p>
            <textarea
              id="chatgpt-session-json"
              v-model="chatgptSessionJson"
              name="chatgpt-session-json"
              autocomplete="off"
              autocorrect="off"
              autocapitalize="none"
              spellcheck="false"
              data-lpignore="true"
              data-1p-ignore="true"
              :disabled="isLoading"
              :placeholder="chatgptSessionPlaceholder"
              class="min-h-36 w-full resize-y rounded-md border border-input bg-background px-3 py-2 font-mono text-xs outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:opacity-50"
            />
          </div>

          <p v-if="errorMessage" class="text-sm text-destructive">{{ errorMessage }}</p>

          <UiButton type="submit" class="w-full" :disabled="isLoading">
            <UiIcon v-if="isLoading" name="i-lucide-loader-2" class="size-4 animate-spin" />
            {{ isLoading ? 'Connecting...' : 'Connect Codex Account' }}
          </UiButton>
        </form>

        <form
          v-if="step === finishStep && selectedConfig && (activeFlowType === 'api_key' || activeFlowType === 'api_key_with_account_id')"
          class="space-y-4"
          autocomplete="off"
          data-lpignore="true"
          data-1p-ignore="true"
          @submit.prevent="handleConnectApiKey"
        >
          <div class="space-y-2">
            <p class="text-sm font-medium">Connect {{ selectedConfig.name }}</p>
            <p class="text-sm text-muted-foreground">
              {{ activeFlowType === 'api_key_with_account_id' ? 'Paste your API token and Account ID. Credentials will be stored encrypted.' : 'Paste your provider API key directly. The key will be stored encrypted.' }}
            </p>
          </div>

          <div class="space-y-2">
            <label for="provider-api-key" class="text-sm font-medium">
              {{ activeFlowType === 'api_key_with_account_id' ? 'API Token' : 'API Key' }} <span aria-hidden="true" class="text-destructive">*</span>
            </label>
            <div class="relative">
              <input
                id="provider-api-key"
                v-model="apiKey"
                type="text"
                name="provider-token"
                autocomplete="off"
                autocorrect="off"
                autocapitalize="none"
                spellcheck="false"
                data-lpignore="true"
                data-1p-ignore="true"
                :placeholder="selectedConfig.apiKeyPlaceholder"
                :disabled="isLoading"
                :class="cn(
                  'h-9 w-full rounded-md border border-input bg-background px-3 pr-9 text-sm outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:opacity-50',
                  isApiKeyVisible ? '' : '[text-security:disc] [-webkit-text-security:disc]',
                )"
              >
              <UiTooltip :text="isApiKeyVisible ? 'Hide' : 'Show'">
                <button
                  type="button"
                  :disabled="isLoading"
                  class="absolute right-2.5 top-1/2 -translate-y-1/2 text-muted-foreground transition-colors hover:text-foreground disabled:opacity-50"
                  :aria-label="isApiKeyVisible ? 'Hide API key' : 'Show API key'"
                  @click="isApiKeyVisible = !isApiKeyVisible"
                >
                  <UiIcon :name="isApiKeyVisible ? 'i-lucide-eye-off' : 'i-lucide-eye'" class="size-4" />
                </button>
              </UiTooltip>
            </div>
          </div>

          <div v-if="provider === 'zenmux'" class="space-y-2">
            <label for="provider-platform-key" class="text-sm font-medium">
              Platform Key <span aria-hidden="true" class="text-destructive">*</span>
            </label>
            <p class="text-xs text-muted-foreground">
              For quota usage tracking.
              <a href="https://zenmux.ai/platform/management" target="_blank" class="underline">Get from ZenMux → Management → API Keys</a>
            </p>
            <input
              id="provider-platform-key"
              v-model="platformKey"
              type="text"
              name="provider-platform-key"
              autocomplete="off"
              autocorrect="off"
              autocapitalize="none"
              spellcheck="false"
              data-lpignore="true"
              data-1p-ignore="true"
              placeholder="sk-mg-v1-..."
              :disabled="isLoading"
              class="h-9 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:opacity-50"
            >
          </div>

          <div v-if="activeFlowType === 'api_key_with_account_id'" class="space-y-2">
            <label for="provider-account-id" class="text-sm font-medium">
              {{ selectedConfig.accountIdLabel }} <span aria-hidden="true" class="text-destructive">*</span>
            </label>
            <input
              id="provider-account-id"
              v-model="cfAccountId"
              type="text"
              name="provider-account-id"
              autocomplete="off"
              autocorrect="off"
              autocapitalize="none"
              spellcheck="false"
              data-lpignore="true"
              data-1p-ignore="true"
              :placeholder="selectedConfig.accountIdPlaceholder"
              :disabled="isLoading"
              class="h-9 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:opacity-50"
            >
          </div>

          <p v-if="errorMessage" class="text-sm text-destructive">{{ errorMessage }}</p>

          <UiButton type="submit" class="w-full" :disabled="isLoading">
            <UiIcon v-if="isLoading" name="i-lucide-loader-2" class="size-4 animate-spin" />
            {{ isLoading ? 'Connecting...' : `Connect ${selectedConfig.name} Account` }}
          </UiButton>
        </form>
      </div>

      <div class="flex flex-row items-center justify-between gap-2">
        <UiButton v-if="isPolling" type="button" variant="ghost" @click="goBackFromDevicePolling">
          <UiIcon name="i-lucide-arrow-left" class="size-4" />
          Back
        </UiButton>

        <UiButton v-if="step > minimumStep && !isPolling" type="button" variant="ghost" :disabled="isLoading" @click="goBack">
          <UiIcon name="i-lucide-arrow-left" class="size-4" />
          Back
        </UiButton>

        <UiButton v-if="step === authStep && selectedConfig && activeFlowType !== 'device_code'" type="button" variant="ghost" class="ml-auto" @click="step = finishStep">
          Next
          <UiIcon name="i-lucide-arrow-right" class="size-4" />
        </UiButton>
      </div>
      </template>
      <CustomProviderSetup v-else @cancel="customMode = false" @created="handleCustomCreated" />
    </template>
  </UiDialog>
</template>
