// apps/web/src/components/AccountStatusIndicator.tsx
import { cn } from "../lib/utils";

export interface AccountStatusIndicatorProps {
  accountCount?: number;
  activeAccountCount?: number;
  indicator?: "normal" | "warning" | "error";
  className?: string;
}

export function AccountStatusIndicator({ accountCount = 0, activeAccountCount = 0, indicator = "normal", className }: AccountStatusIndicatorProps) {
  return (
    <span className={cn("flex items-center gap-1.5", className)}>
      <span
        aria-hidden="true"
        className={cn(
          "size-1.5 rounded-full",
          indicator === "error" ? "bg-destructive" : indicator === "warning" ? "bg-amber-400" : activeAccountCount > 0 ? "bg-emerald-400" : "bg-muted-foreground/40",
        )}
      />
      <span className="text-[10px] tabular-nums text-muted-foreground">
        {accountCount}
        {activeAccountCount !== accountCount ? `/${activeAccountCount}` : ""}
      </span>
    </span>
  );
}

// apps/dashboard/app/components/AccountStatusIndicator.vue
<script setup lang="ts">
import type { ProviderAccountIndicator } from "../../lib/navigation";

const props = defineProps<{
  accountCount?: number;
  activeAccountCount?: number;
  indicator?: ProviderAccountIndicator;
}>();

const hasActiveAccounts = computed(
  () => typeof props.activeAccountCount === "number" && props.activeAccountCount > 0
);

const indicatorClass = computed(() => {
  if (props.indicator === "error") {
    return "bg-red-500";
  }

  if (props.indicator === "warning") {
    return "bg-yellow-500";
  }

  return "bg-primary";
});
</script>

<template>
  <span v-if="hasActiveAccounts && indicator" class="relative flex h-2.5 w-2.5 shrink-0" aria-hidden="true">
    <span :class="['absolute inline-flex h-full w-full animate-ping rounded-full opacity-75', indicatorClass]" />
    <span :class="['relative inline-flex h-2.5 w-2.5 rounded-full', indicatorClass]" />
  </span>
  <span v-else class="relative flex h-2.5 w-2.5 shrink-0" aria-hidden="true">
    <span class="relative inline-flex h-2.5 w-2.5 rounded-full bg-muted-foreground/30" />
  </span>
</template>
