// components/dashboard/api-keys/create-api-key-button.tsx
"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { format } from "date-fns";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Calendar } from "@/components/ui/calendar";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { Plus, Copy, Check, CalendarIcon, X } from "lucide-react";
import { toast } from "sonner";
import { createApiKey } from "@/lib/actions/api-keys";
import { cn } from "@/lib/utils";

export function CreateApiKeyButton() {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [name, setName] = useState("");
  const [expiresAt, setExpiresAt] = useState<Date | undefined>(undefined);
  const [isCreating, setIsCreating] = useState(false);
  const [createdKey, setCreatedKey] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  // Listen for hotkey-triggered create event
  useEffect(() => {
    const handler = () => setOpen(true);
    window.addEventListener("opendum:create-api-key", handler);
    return () => window.removeEventListener("opendum:create-api-key", handler);
  }, []);

  const handleCreate = async () => {
    setIsCreating(true);
    try {
      const result = await createApiKey(
        name.trim() || undefined,
        expiresAt ?? null
      );

      if (!result.success) {
        throw new Error(result.error);
      }

      // Show the created key in the modal
      setCreatedKey(result.data.key);
      toast.success("API key created!");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to create API key");
    } finally {
      setIsCreating(false);
    }
  };

  const handleCopy = async () => {
    if (!createdKey) return;

    try {
      await navigator.clipboard.writeText(createdKey);
      setCopied(true);
      toast.success("API key copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Failed to copy to clipboard");
    }
  };

  const handleClose = () => {
    setOpen(false);
    setName("");
    setExpiresAt(undefined);
    setCreatedKey(null);
    setCopied(false);
    // Refresh the page to show the new key in the list
    router.refresh();
  };

  // Minimum date is tomorrow
  const tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);
  tomorrow.setHours(0, 0, 0, 0);

  return (
    <Dialog open={open} onOpenChange={(isOpen) => {
      if (!isOpen) {
        handleClose();
      } else {
        setOpen(true);
      }
    }}>
      <DialogTrigger asChild>
        <Button>
          <Plus className="mr-2 h-4 w-4" />
          Create API Key
          <kbd className="bg-primary-foreground/20 ml-2 hidden rounded px-1.5 py-0.5 font-mono text-[10px] sm:inline-block">C</kbd>
        </Button>
      </DialogTrigger>
      <DialogContent>
        {createdKey ? (
          // Success state - show the created key
          <>
            <DialogHeader>
              <DialogTitle>API Key Created!</DialogTitle>
              <DialogDescription>
                Your new API key is ready to use.
              </DialogDescription>
            </DialogHeader>
            <div className="py-4">
              <Label>Your API Key</Label>
              <div className="mt-2 flex items-center gap-2">
                <code className="flex-1 rounded bg-muted px-3 py-2 text-sm font-mono break-all">
                  {createdKey}
                </code>
                <Button
                  variant="outline"
                  size="icon"
                  onClick={handleCopy}
                  title="Copy key"
                >
                  {copied ? (
                    <Check className="h-4 w-4 text-green-500" />
                  ) : (
                    <Copy className="h-4 w-4" />
                  )}
                </Button>
              </div>
              <p className="mt-2 text-sm text-muted-foreground">
                You can reveal and copy this key anytime from the list.
              </p>
            </div>
            <DialogFooter>
              <Button onClick={handleClose}>Done</Button>
            </DialogFooter>
          </>
        ) : (
          // Create state - input name and expiration
          <>
            <DialogHeader>
              <DialogTitle>Create API Key</DialogTitle>
              <DialogDescription>
                Create a new API key for accessing Opendum.
              </DialogDescription>
            </DialogHeader>
            <div className="py-4 space-y-4">
              <div>
                <Label htmlFor="keyName">Name (optional)</Label>
                <Input
                  id="keyName"
                  placeholder="e.g., MacBook Pro, Work PC"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  className="mt-2"
                  onKeyDown={(e) => {
                    if (e.key === "Enter") {
                      e.preventDefault();
                      handleCreate();
                    }
                  }}
                />
              </div>
              <div>
                <Label>Expiration (optional)</Label>
                <div className="mt-2 flex items-center gap-2">
                  <Popover>
                    <PopoverTrigger asChild>
                      <Button
                        variant="outline"
                        className={cn(
                          "w-full justify-start text-left font-normal",
                          !expiresAt && "text-muted-foreground"
                        )}
                      >
                        <CalendarIcon className="mr-2 h-4 w-4" />
                        {expiresAt ? format(expiresAt, "PPP") : "No expiration"}
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0" align="start">
                      <Calendar
                        mode="single"
                        selected={expiresAt}
                        onSelect={setExpiresAt}
                        disabled={(date) => date < tomorrow}
                        initialFocus
                      />
                    </PopoverContent>
                  </Popover>
                  {expiresAt && (
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={() => setExpiresAt(undefined)}
                      title="Clear expiration"
                    >
                      <X className="h-4 w-4" />
                    </Button>
                  )}
                </div>
                <p className="mt-1 text-xs text-muted-foreground">
                  Leave empty for a key that never expires.
                </p>
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setOpen(false)}>
                Cancel
              </Button>
              <Button onClick={handleCreate} disabled={isCreating}>
                {isCreating ? "Creating..." : "Create"}
              </Button>
            </DialogFooter>
          </>
        )}
      </DialogContent>
    </Dialog>
  );
}

// apps/dashboard/app/components/CreateApiKeyButton.vue
<script setup lang="ts">
const emit = defineEmits<{
  created: [];
}>();

const { $client } = useNuxtApp();
const open = ref(false);
const name = ref("");
const isCreating = ref(false);
const createdKey = ref<string | null>(null);
const copied = ref(false);
const errorMessage = ref("");

function reset() {
  name.value = "";
  createdKey.value = null;
  copied.value = false;
  errorMessage.value = "";
}

watch(open, (value) => {
  if (!value) {
    reset();
    emit("created");
  }
});

async function createKey() {
  isCreating.value = true;
  errorMessage.value = "";
  try {
    const result = await $client.apiKeys.create.mutate({ name: name.value.trim() || undefined });
    if (!result.success) throw new Error(result.error);
    createdKey.value = result.data.key;
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : "Failed to create API key";
  } finally {
    isCreating.value = false;
  }
}

async function copyCreatedKey() {
  if (!createdKey.value) return;
  await navigator.clipboard.writeText(createdKey.value);
  copied.value = true;
  setTimeout(() => (copied.value = false), 2000);
}

function closeDialog() {
  open.value = false;
}
</script>

<template>
  <UiButton size="sm" @click="open = true">
    <UiIcon name="i-lucide-plus" class="mr-1.5 size-3.5" />
    Create API Key
  </UiButton>

  <UiDialog v-model:open="open" :ui="{ content: 'sm:max-w-[440px]' }">
    <template #content>
      <template v-if="createdKey">
        <div class="space-y-1.5 pr-6">
          <h2 class="text-lg font-semibold leading-none tracking-tight">API Key Created</h2>
          <p class="sr-only">Your new API key is ready to use.</p>
        </div>
        <div class="py-3">
          <label class="text-sm font-medium">Your API Key</label>
          <div class="mt-1.5 flex items-center gap-2">
            <code class="flex-1 break-all rounded bg-muted px-2.5 py-1.5 font-mono text-xs">{{ createdKey }}</code>
            <UiButton variant="outline" size="sm" class="h-8 w-8 shrink-0 p-0" title="Copy key" @click="copyCreatedKey">
              <UiIcon :name="copied ? 'i-lucide-check' : 'i-lucide-copy'" :class="['size-3.5', copied ? 'text-green-500' : '']" />
            </UiButton>
          </div>
        </div>
        <div class="flex justify-end">
          <UiButton size="sm" @click="closeDialog">Done</UiButton>
        </div>
      </template>

      <template v-else>
        <div class="space-y-1.5 pr-6">
          <h2 class="text-lg font-semibold leading-none tracking-tight">Create API Key</h2>
          <p class="sr-only">Create a new API key for accessing Opendum.</p>
        </div>
        <div v-if="errorMessage" class="rounded-lg border border-destructive/50 bg-destructive/10 px-3 py-2 text-sm text-destructive">
          {{ errorMessage }}
        </div>
        <div class="space-y-3 py-3">
          <label class="grid gap-1.5 text-sm font-medium">
            Name
            <input
              v-model="name"
              class="h-9 rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50"
              placeholder="My API Key"
              @keydown.enter.prevent="createKey"
            >
          </label>
        </div>
        <div class="flex justify-end gap-2">
          <UiButton variant="outline" size="sm" @click="open = false">Cancel</UiButton>
          <UiButton size="sm" :disabled="isCreating" @click="createKey">{{ isCreating ? 'Creating...' : 'Create' }}</UiButton>
        </div>
      </template>
    </template>
  </UiDialog>
</template>
