// components/dashboard/api-keys/editable-api-key-name.tsx
"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Pencil } from "lucide-react";
import { toast } from "sonner";
import { updateApiKeyName } from "@/lib/actions/api-keys";

interface EditableApiKeyNameProps {
  id: string;
  name: string | null;
}

export function EditableApiKeyName({ id, name }: EditableApiKeyNameProps) {
  const [editDialogOpen, setEditDialogOpen] = useState(false);
  const [newName, setNewName] = useState(name ?? "");
  const [isUpdating, setIsUpdating] = useState(false);

  const handleUpdateName = async () => {
    setIsUpdating(true);
    try {
      const result = await updateApiKeyName(id, newName);

      if (!result.success) {
        throw new Error(result.error);
      }

      toast.success("API key name updated");
      setEditDialogOpen(false);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to update API key name");
    } finally {
      setIsUpdating(false);
    }
  };

  return (
    <div className="flex items-center gap-1">
      <span className="text-lg font-semibold">{name ?? "Unnamed Key"}</span>
      <Dialog open={editDialogOpen} onOpenChange={(open) => {
        setEditDialogOpen(open);
        if (open) setNewName(name ?? "");
      }}>
        <DialogTrigger asChild>
          <Button 
            variant="ghost" 
            size="sm" 
            className="h-6 w-6 p-0 text-muted-foreground hover:text-foreground" 
            title="Edit name"
          >
            <Pencil className="h-3.5 w-3.5" />
          </Button>
        </DialogTrigger>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Edit API Key Name</DialogTitle>
            <DialogDescription>
              Change the name of your API key for easier identification.
            </DialogDescription>
          </DialogHeader>
          <div className="py-4">
            <Label htmlFor="apiKeyName">Name</Label>
            <Input
              id="apiKeyName"
              value={newName}
              onChange={(e) => setNewName(e.target.value)}
              placeholder="My API Key"
              className="mt-2"
            />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setEditDialogOpen(false)}>
              Cancel
            </Button>
            <Button
              onClick={handleUpdateName}
              disabled={isUpdating}
            >
              {isUpdating ? "Saving..." : "Save"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// apps/dashboard/app/components/EditableApiKeyName.vue
<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    id: string;
    name: string | null;
    showTitle?: boolean;
    showEditButton?: boolean;
  }>(),
  {
    showTitle: true,
    showEditButton: true,
  }
);

const emit = defineEmits<{
  updated: [];
}>();

const { $client } = useNuxtApp();
const editDialogOpen = ref(false);
const newName = ref(props.name ?? "");
const isUpdating = ref(false);
const errorMessage = ref("");

watch(editDialogOpen, (open) => {
  if (open) {
    newName.value = props.name ?? "";
    errorMessage.value = "";
  }
});

async function updateName() {
  isUpdating.value = true;
  errorMessage.value = "";
  try {
    const result = await $client.apiKeys.updateName.mutate({ id: props.id, name: newName.value });
    if (!result.success) throw new Error(result.error);
    editDialogOpen.value = false;
    emit("updated");
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : "Failed to update API key name";
  } finally {
    isUpdating.value = false;
  }
}
</script>

<template>
  <div class="flex min-w-0 items-center gap-1.5">
    <span v-if="showTitle" class="min-w-0 truncate text-lg font-semibold">{{ name ?? 'Unnamed key' }}</span>
    <UiButton v-if="showEditButton" variant="outline" size="icon" class="h-9 w-9" title="Edit name" @click="editDialogOpen = true">
      <UiIcon name="i-lucide-pencil" class="size-4" />
    </UiButton>
  </div>

  <UiDialog v-model:open="editDialogOpen" :ui="{ content: 'sm:max-w-[400px]' }">
    <template #content>
      <div class="space-y-1.5 pr-6">
        <h2 class="text-lg font-semibold leading-none tracking-tight">Edit API Key Name</h2>
        <p class="sr-only">Change the name of your API key.</p>
      </div>
      <div v-if="errorMessage" class="rounded-lg border border-destructive/50 bg-destructive/10 px-3 py-2 text-sm text-destructive">
        {{ errorMessage }}
      </div>
      <div class="py-3">
        <label class="grid gap-1.5 text-sm font-medium">
          Name
          <input
            v-model="newName"
            class="h-9 rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50"
            placeholder="My API Key"
            @keydown.enter.prevent="updateName"
          >
        </label>
      </div>
      <div class="flex justify-end gap-2">
        <UiButton variant="outline" size="sm" @click="editDialogOpen = false">Cancel</UiButton>
        <UiButton size="sm" :disabled="isUpdating" @click="updateName">{{ isUpdating ? 'Saving...' : 'Save' }}</UiButton>
      </div>
    </template>
  </UiDialog>
</template>
