// apps/web/src/components/ui/UiDialog.tsx
import type { HTMLAttributes, ReactNode } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { cn } from "../../lib/utils";
import { UiIcon } from "./UiIcon";
import { UiButton } from "./UiButton";

export interface UiDialogProps {
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  modal?: boolean;
  ui?: { overlay?: string; content?: string; close?: string };
  children: ReactNode;
}

export function UiDialog({ open, onOpenChange, modal, ui, children }: UiDialogProps) {
  return (
    <Dialog.Root open={open} onOpenChange={onOpenChange} modal={modal}>
      <Dialog.Portal>
        <Dialog.Overlay
          className={cn(
            "fixed inset-0 z-50 bg-black/80 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0",
            ui?.overlay,
          )}
        />
        <Dialog.Content
          className={cn(
            "fixed left-1/2 top-1/2 z-50 flex max-h-[85dvh] w-full max-w-[calc(100%-2rem)] -translate-x-1/2 -translate-y-1/2 flex-col gap-4 overflow-hidden rounded-lg border border-border bg-background p-6 text-foreground shadow-lg outline-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 sm:max-w-lg",
            ui?.content,
          )}
        >
          {children}
          <Dialog.Close asChild>
            <UiButton
              size="icon-xs"
              variant="ghost"
              aria-label="Close"
              className={cn("absolute right-4 top-4 text-muted-foreground", ui?.close)}
            >
              <UiIcon name="i-lucide-x" className="size-3.5" />
            </UiButton>
          </Dialog.Close>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}

export function UiDialogTrigger({ children, className }: { children: ReactNode; className?: string }) {
  return (
    <Dialog.Trigger asChild>
      <span className={className}>{children}</span>
    </Dialog.Trigger>
  );
}

export function UiDialogClose({ children, className }: { children: ReactNode; className?: string }) {
  return (
    <Dialog.Close asChild>
      <span className={className}>{children}</span>
    </Dialog.Close>
  );
}

export function UiDialogTitle(props: HTMLAttributes<HTMLHeadingElement>) {
  return <Dialog.Title className="text-base font-semibold" {...props} />;
}

export function UiDialogDescription(props: HTMLAttributes<HTMLParagraphElement>) {
  return <Dialog.Description className="text-sm text-muted-foreground" {...props} />;
}

// apps/dashboard/app/components/UiDialog.vue
<script setup lang="ts">
import { DialogClose, DialogContent, DialogOverlay, DialogPortal, DialogRoot } from "reka-ui";
import { cn } from "../../lib/utils";

const props = withDefaults(
  defineProps<{
    modal?: boolean;
    ui?: {
      overlay?: string;
      content?: string;
      close?: string;
    };
    preventOutsideClose?: boolean;
    preventEscapeClose?: boolean;
    showClose?: boolean;
  }>(),
  {
    modal: true,
    ui: () => ({}),
    preventOutsideClose: false,
    preventEscapeClose: false,
    showClose: true,
  }
);

const open = defineModel<boolean>("open", { default: false });

function handleInteractOutside(event: Event) {
  if (props.preventOutsideClose) event.preventDefault();
}

function handleEscapeKeyDown(event: Event) {
  if (props.preventEscapeClose) event.preventDefault();
}
</script>

<template>
  <DialogRoot v-model:open="open" :modal="modal">
    <DialogPortal>
      <DialogOverlay
        :class="cn(
          'fixed inset-0 z-50 bg-black/80 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0',
          ui.overlay,
        )"
      />
      <DialogContent
        :class="cn(
          'fixed left-1/2 top-1/2 z-50 flex max-h-[85dvh] w-full max-w-[calc(100%-2rem)] -translate-x-1/2 -translate-y-1/2 flex-col gap-4 overflow-hidden rounded-lg border border-border bg-background p-6 text-foreground shadow-lg outline-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 sm:max-w-lg',
          props.ui.content,
        )"
        @interact-outside="handleInteractOutside"
        @escape-key-down="handleEscapeKeyDown"
      >
        <slot name="content">
          <slot />
        </slot>
        <DialogClose
          v-if="showClose"
          :class="cn(
            'absolute right-4 top-4 cursor-pointer rounded-xs opacity-70 transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none [&_svg]:pointer-events-none [&_svg]:shrink-0',
            props.ui.close,
          )"
        >
          <UiIcon name="i-lucide-x" class="size-4" />
          <span class="sr-only">Close</span>
        </DialogClose>
      </DialogContent>
    </DialogPortal>
  </DialogRoot>
</template>
