// apps/web/src/components/ui/UiSheet.tsx
import type { ReactNode } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { cn } from "../../lib/utils";
import { UiIcon } from "./UiIcon";
import { UiButton } from "./UiButton";

export interface UiSheetProps {
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  modal?: boolean;
  side?: "left" | "right" | "top" | "bottom";
  ui?: { overlay?: string; content?: string; close?: string };
  overlayStyle?: React.CSSProperties;
  children: ReactNode;
}

const sideClasses: Record<string, string> = {
  left: "inset-y-0 left-0 h-full w-3/4 border-r sm:max-w-sm data-[state=closed]:slide-out-to-left data-[state=open]:slide-in-from-left",
  right: "inset-y-0 right-0 h-full w-3/4 border-l sm:max-w-sm data-[state=closed]:slide-out-to-right data-[state=open]:slide-in-from-right",
  top: "inset-x-0 top-0 border-b data-[state=closed]:slide-out-to-top data-[state=open]:slide-in-from-top",
  bottom: "inset-x-0 bottom-0 border-t data-[state=closed]:slide-out-to-bottom data-[state=open]:slide-in-from-bottom",
};

export function UiSheet({ open, onOpenChange, modal, side = "right", ui, overlayStyle, children }: UiSheetProps) {
  return (
    <Dialog.Root open={open} onOpenChange={onOpenChange} modal={modal}>
      <Dialog.Portal>
        <Dialog.Overlay
          className={cn("fixed inset-0 z-50 bg-black/80 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0", ui?.overlay)}
          style={overlayStyle}
        />
        <Dialog.Content
          className={cn(
            "fixed z-50 gap-4 border-border bg-background text-foreground shadow-lg outline-none transition ease-in-out data-[state=closed]:duration-300 data-[state=open]:duration-500 data-[state=open]:animate-in data-[state=closed]:animate-out",
            sideClasses[side],
            ui?.content,
          )}
        >
          {children}
          <Dialog.Close asChild>
            <UiButton size="icon-xs" variant="ghost" aria-label="Close" className={cn("absolute right-4 top-4 text-muted-foreground", ui?.close)}>
              <UiIcon name="i-lucide-x" className="size-3.5" />
            </UiButton>
          </Dialog.Close>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}

// apps/dashboard/app/components/UiSheet.vue
<script setup lang="ts">
import { DialogContent, DialogOverlay, DialogPortal, DialogRoot } from "reka-ui";
import { cn } from "../../lib/utils";

type SheetSide = "top" | "right" | "bottom" | "left";

const props = withDefaults(
  defineProps<{
    side?: SheetSide;
    modal?: boolean;
    ui?: {
      overlay?: string;
      content?: string;
    };
  }>(),
  {
    side: "right",
    modal: true,
    ui: () => ({}),
  }
);

const open = defineModel<boolean>("open", { default: false });

const sideClasses: Record<SheetSide, string> = {
  top: "inset-x-0 top-0 h-auto border-b data-[state=closed]:slide-out-to-top data-[state=open]:slide-in-from-top",
  right: "inset-y-0 right-0 h-full w-3/4 border-l data-[state=closed]:slide-out-to-right data-[state=open]:slide-in-from-right sm:max-w-sm",
  bottom: "inset-x-0 bottom-0 h-auto border-t data-[state=closed]:slide-out-to-bottom data-[state=open]:slide-in-from-bottom",
  left: "inset-y-0 left-0 h-full w-3/4 border-r data-[state=closed]:slide-out-to-left data-[state=open]:slide-in-from-left sm:max-w-sm",
};
</script>

<template>
  <DialogRoot v-model:open="open" :modal="modal">
    <DialogPortal>
      <DialogOverlay
        :class="cn(
          'fixed inset-0 z-50 bg-black/80 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0',
          props.ui.overlay,
        )"
      />
      <DialogContent
        :class="cn(
          'fixed z-50 gap-4 border-border bg-background text-foreground shadow-lg outline-none transition ease-in-out data-[state=closed]:duration-300 data-[state=open]:duration-500 data-[state=open]:animate-in data-[state=closed]:animate-out',
          sideClasses[side],
          props.ui.content,
        )"
      >
        <slot name="content">
          <slot />
        </slot>
      </DialogContent>
    </DialogPortal>
  </DialogRoot>
</template>
